### ISSUE TITLE
type variables are unhygiene

### ISSUE THREAD

**Issue by yjqww6** [racket/typed-racket#1014]
### What version of Racket are you using?
7.9
### What program did you run?
```racket
#lang typed/racket
(define-syntax-rule (def id vars ...)
  (begin
    (: id (All (vars ... a) (-> vars ... a a)))
    (define (id vars ... a) a)))

(def f a)
(def g x)
```
then in repl:
```racket
> (f 1 "2")
- : (U One String)
"2"
> (g 1 "2")
- : String
"2"
```
@Syntacticlosure told me about this problem.
 If I understand correctly, type variables are treated as symbols currently, which is not intuitive. 
At least, it should report an error when duplicated type variables appear in `All`.

**Comment by capfredf** [comment]
Yes, you are right. Internally, the representation of a type variable comes down to a symbol, and operations for type variables have a similar assumption. Therefore, unfortunately changing symbols to identifiers would require a considerable amount of work. 
I would be push a pull request so the type checker would report an error in this scenario.
