### ISSUE TITLE
How to distinguish variable and type with the same name when they are provided or required?

### ISSUE THREAD

**Issue by NoahStoryM** [racket/typed-racket#1053]
### What version of Racket are you using?
`v8.0`

### What program did you run?
```
#lang typed/racket

(module exp typed/racket/base
  (provide (except-out (all-defined-out) Exp))
  (struct Exp ()))


(require 'exp)

(: test [-> Exp Any])
(define test (λ (arg) arg))

Exp
```

### What should have happened?
What should I do if I just want to provide/require all except the constructor/type?

**Comment by capfredf** [comment]
you can give a different to you structure types by specifying [`#:type-name` ](https://docs.racket-lang.org/ts-reference/special-forms.html?q=struct#%28form._%28%28lib._typed-racket%2Fbase-env%2Fprims..rkt%29._struct%29%29)

```racket
#lang typed/racket

(module exp typed/racket/base
  (provide (except-out (all-defined-out) exp))
  (provide (all-defined-out))
  (struct exp () #:type-name Exp))


(require 'exp)

(: test [-> Exp Any])
(define test (λ (arg) arg))
```

**Comment by NoahStoryM** [comment]
Hi capfredf,

Give the structure a different name is a good solution in most cases.

But what if I want to use some structure as an abstract structure from other's module?

For example, some people write `animal.rkt` which defines Animal structure:
```
#lang typed/racket

(provide (struct-out Animal))

(struct Animal ([name : Symbol]))

;; ...
;; Some code that uses Animal as a constructor and type.

```

And I want to use Animal type to define some sub-structure:
```
#lang typed/racket

(require "animal.rkt")

(struct Dog Animal ([Age : Natural]))

;; ...
;; Some code that only uses Animal as a type.

```

I don't know how to remove `Animal` constructor in my code, and I can't modify Animal's type-name or constructor-name because others' code may use `Animal` as both type and constructor.


By the way, If I want to define an abstract structure, is there a better way than defining it in a module and except-out its constructor?

**Comment by capfredf** [comment]
Since the author of the module `animal` decided to export both constructors and types, one possibility of access control would be writing another module to mediate the access from other modules to the bindings from `animal`.

I don't think there is a way to make an abstract `struct` in the sense of an abstract class in an OO language like Java.

**Comment by NoahStoryM** [comment]
I know how to deal with this problem, thank you very much!
