### ISSUE TITLE
vector->pseudo-random-generator fails when the vector is `read` at runtime

### ISSUE THREAD

**Issue by default-kramer** [racket/typed-racket#1063]
### What version of Racket are you using?
8.0.0.11--2021-03-15(c0cfd32/a) [cs]

### What program did you run?
```
(vector->pseudo-random-generator
 (let* ([port (open-input-string "#(2333968651 3517909795 3922866092 4084493319 924421228 2830068628)")]
        [datum (read port)])
   (println datum)
   (println (vector? datum))
   (cast datum (U (Immutable-Vector
                   Positive-Integer
                   Positive-Integer
                   Positive-Integer
                   Positive-Integer
                   Positive-Integer
                   Positive-Integer)
                  (Mutable-Vector
                   Positive-Integer
                   Positive-Integer
                   Positive-Integer
                   Positive-Integer
                   Positive-Integer
                   Positive-Integer)))))
```

### What should have happened?
It should create the pseudo-random-generator, just like the untyped Racket equivalent does.

The problem is not present when a runtime `read` is not involved.
```
(vector->pseudo-random-generator
 '#(2333968651 3517909795 3922866092 4084493319 924421228 2830068628))
```

### If you got an error message, please include it here.
`vector->pseudo-random-generator: not a valid pseudo-random generator state vector '#(2333968651 3517909795 3922866092 4084493319 924421228 2830068628)`

**Comment by default-kramer** [comment]
Looks like the problem is not related to `read` but to `cast`. This program works
```
(vector->pseudo-random-generator
 (let* ([port (open-input-string "#(2333968651 3517909795 3922866092 4084493319 924421228 2830068628)")]
        [datum (read port)])
   (let ([v (cast datum (Vectorof Positive-Integer))])
     (vector (vector-ref v 0)
             (vector-ref v 1)
             (vector-ref v 2)
             (vector-ref v 3)
             (vector-ref v 4)
             (vector-ref v 5)))))
```

**Comment by samth** [comment]
Yes, I think this is a bug in `vector->pseudo-random-generator`, which should accept chaperoned vectors but doesn't.

**Comment by mflatt** [comment]
I'll fix `vector->pseudo-random-generator`.

**Comment by samth** [comment]
This was fixed in https://github.com/racket/racket/commit/206577d701287c1e02251546c0188e6f2f3b28cf
