### ISSUE TITLE
TR needs a new type for pipe-port

### ISSUE THREAD

**Issue by capfredf** [racket/typed-racket#1087]
Because of lack of type Pipe-Port,  `make-pipe` has type `(->* () (Number Any Any) (values Input-Port Output-Port))`, and `pipe-contact-length` has type `(-> Port Nonnegative-Integer)`. These two types don't match the run time behavior of two functions. 
### What version of Racket are you using?
8.0

### What program did you run?
> (require typed/racket/base)
> (pipe-content-length (current-input-port))
### What should have happened?
A type error
### If you got an error message, please include it here.
; pipe-contact-length: contract violation
;   expected: (or/c pipe-input-port? pipe-output-port?)
;   given: #<input-port:readline-input>

**Comment by samth** [comment]
I'm unsure here. We don't necessarily have to try to rule out every runtime error. We don't have a separate type for string input ports, for example.

**Comment by capfredf** [comment]
I think that depends. For example,

```
(define (foo s)
  (open-input-file "./README.md"))
(read (make-input-port 'test
                       foo
                       #f
                       void))
```

This program gets stuck because the input-port from `(open-input-file "./README.md")` is a generic evt and always returns itself, so Racket simply keeps `sync`ing  it. The type of `make-input-port` uses `Input-Port` for this case. However, the [documentation](https://docs.racket-lang.org/reference/customport.html?q=make-input-port#%28def._%28%28quote._~23~25kernel%29._make-input-port%29%29) says:

> The procedure’s result is one of the following:
    the number of bytes read, as an exact, non-negative integer;
    eof;
    a procedure of arity four (representing a “special” result, as discussed further below), but a procedure result is allowed only when peek is not #f;
    a pipe input port that supplies bytes to be used as long as the pipe has content (see pipe-content-length) or until read-in or peek is called again; or
    a synchronizable event (see Events) other than a pipe input port or procedure of arity four; the event becomes ready when the read is complete (roughly): the event’s value can be one of the above three results or another event like itself; in the last case, a reading process loops with sync until it gets a non-event result.

My understanding is a type for pipe ports would be helpful for ruling out these unexpected behaviors of `make-input-port`.

**Comment by samth** [comment]
But it looks like there isn't a type error here. As you say, it's an event that always produces an event like itself; it's just that there's an implicit progress expectation that isn't met. This seems like a bad design somewhere but I don't think it's a type error.

**Comment by capfredf** [comment]
50% of me believed what your said made sense this morning, but the other half thought otherwise. After 6 hours, I agreed with you 100%.
