### ISSUE TITLE
Cannot use provided `define-struct/exec`

### ISSUE THREAD

**Issue by camoy** [racket/typed-racket#1088]
### What version of Racket are you using?

8.0

### What program did you run?

```
#lang typed/racket

(module foo typed/racket
  (provide (struct-out bar))
  (define-struct/exec
    bar () [(λ (self) 42) : (bar -> Integer)]))

(require 'foo)
(bar)
 ```

### What should have happened?

No error.

### If you got an error message, please include it here.

```
type-check: type name used out of context
  type: bar
 in: (bar) in: bar
```

**Comment by samth** [comment]
The error message is more helpful in 8.1, but you should use `make-bar` to get what you want for the moment.

**Comment by camoy** [comment]
Sounds good. I also just found that using a different name for `#:type-name` also gets around the problem.
