### ISSUE TITLE
Type inference in `let` bindings appears to be broken

### ISSUE THREAD

**Issue by lexi-lambda** [racket/typed-racket#11]
I present the following code sample: 

```racket
#lang typed/racket/base

(define-type ABC (U 'a 'b 'c))

(define-struct ABCWrapper ([abc : ABC]))

(: abc-123-define (ABCWrapper -> (U 1 2 3)))
(define (abc-123-define wrapper)
  (define abc (ABCWrapper-abc wrapper))
  (cond
    [(eq? abc 'a) 1]
    [(eq? abc 'b) 2]
    [(eq? abc 'c) 3]))

(: abc-123-let (ABCWrapper -> (U 1 2 3)))
(define (abc-123-let wrapper)
  (let ([abc (ABCWrapper-abc wrapper)])
    (cond
      [(eq? abc 'a) 1]
      [(eq? abc 'b) 2]
      [(eq? abc 'c) 3])))
```

The typechecker gives an error about `abc-123-let`, but not `abc-123-define`. If I add an explicit type annotation to the let binding (`[abc : ABC ...]`), then it typechecks properly.

This is new behavior, and it doesn't occur in Racket v6.1.1. I encountered it while trying to build whalesong, which depends on proper type inference in this instance.

**Comment by andmkent** [comment]
Sorry about that - it's a minor bug in struct type updating. I'm testing a fix I'll likely push shortly.

**Comment by andmkent** [comment]
Fixed https://github.com/racket/typed-racket/commit/e7d61bd982e4be3e4a2605af07febae953d7c0b3
