### ISSUE TITLE
< is unsound

### ISSUE THREAD

**Issue by endobson** [racket/typed-racket#112]
This typechecks

```
#lang typed/racket


(ann
  (let ([x : Flonum -5.0])
    (if (< x (ann +nan.0 Positive-Flonum))
        1.0
        x))
  Positive-Flonum)
;; and it returns -5.0, yikes!
```

edit: amk - added return value to code in comment

**Comment by pnwamk** [comment]
From a discussion on slack today when I asked about progress/thoughts on this issue:

```
@samth we should just relax the type of `<` (and all the other comparisons) on floats
we used to distinguish `NaN` in the types, but that was bad because too many things produce `NaN`
although that will probably break things like `(if (> x 0.0) (sqrt (* x x)) 1.0)`


@stamourv Yeah, relaxing the types of comparisons on floats is probably the right call.

```

**Comment by rfindler** [comment]
Is this program one that violates the TR numeric random testing property?

**Comment by samth** [comment]
Yes, I think so. It would be hard (but not impossible) to produce an expression with the type `Positive-Flonum` and the value `NaN` without using an explicit annotation, and the random generator doesn't look like it can generate annotations.

**Comment by stamourv** [comment]
The generator not generating annotations is one part of the problem. It also does not test comparisons in general.
