### ISSUE TITLE
`Any` is a subtype of a recursive type that doesn't contain `Any` and background expansion runs out of memory

### ISSUE THREAD

**Issue by mheiber** [racket/typed-racket#1130]
**What version of Racket are you using?**
7.8 [3m]

**What program did you run?**

```racket
#lang typed/racket

(define-type
  (Foo a)
  (U a (List (Foo 'nevermind))))

(define-type
  Recur
  (U (Foo Recur)))

(: questionable (-> Any Recur))
(define (questionable x) x)

(: out-of-memory (-> Recur Recur))
(define (out-of-memory x)
  (match x
    [(list (list a)) a]
   ))
```

**What should have happened?**

1. Background expansion should not run out of memory.

2. I expected a type error. Either of the following:
- if `Recur is not well-formed then `Recur` shouldn't type-check.
- if `Recur` is well-formed then it's not equivalent to `Any` and `questionable` shouldn't type-check

Re (2)
This very similar code is (correctly) rejected:

```
(define-type
  (Bar a)
  (U a 'ok))

(define-type
  Recur2
  (U 'a (Bar Recur2)))  
  
; Type Checker: parse error in type;
; recursive types are not allowed directly inside their definition in: Recur2
```

**If you got an error message, please include it here.**

Background expansion terminated abnormally (out of memory)

**Please include any other relevant details**
Using Mac OS and Dr. Racket

Thanks @ilya-klyuchnikov for collab on cooking up examples like this

**Comment by mheiber** [comment]
I'm very curious about the solution to this issue, since I'm working on a similar problem for another type checker.

Here's my guess at what's happening:
- It seems that non-recursive type aliases are eagerly unfolded, which is how the code in the `Recur2` example is (correctly) rejected: the validation "sees through" `Bar`.
- But recursive types can't be eagerly unfolded (being infinite), so the same validation cannot "see through" `Foo`, and so misses that `Recur2` is not contractive.

**Comment by samth** [comment]
The solution is indeed that Typed Racket should reject types that are not productive, even though it fails to here.

**Comment by mheiber** [comment]
> I don't think there's a formal account of what Typed Racket is doing, but we should try to come up with one.
> 
> Here's a recent paper that looks relevant: https://cambium.inria.fr/~scherer/research/constructor-unboxing/constructor-unboxing-ml-workshop-2021.pdf

Thanks! @ilyaklyuchnikov also found https://link.springer.com/chapter/10.1007/978-3-642-39212-2_28, which sketches a contractivity checker for a language with parameterized recursive types.

**Comment by capfredf** [comment]
@mheiber This issue has been fixed in the latest commit that added a kind system.  Also, thanks for the pointers to the literature.

**Comment by ilya-klyuchnikov** [comment]
For the history: the latest commit is d65ff8bd7146b15b79f31506f8aca410aed196e4
