### ISSUE TITLE
Rendered complex number in documentation causes confusion

### ISSUE THREAD

**Issue by rhcarvalho** [racket/typed-racket#1136]
### What version of Racket are you using?

Currently 8.2, latest docs at

https://docs.racket-lang.org/ts-guide/optimization.html

Section 7.2.1 Numeric types.

### What program did you run?

The documentation source reads

```
Note that both parts of a literal must be
present and
@tech[#:doc '(lib "scribblings/reference/reference.scrbl") #:key
"inexact numbers"]{inexact}
for the literal to be of type
@racket[Float-Complex]; @racket[0.0+1.0i] is of type
@racket[Float-Complex] but @racket[+1.0i] is not.
```

### What should have happened?

The distinction between `0.0+1.0i` and `+1.0i` should be clear in the HTML docs, however they are rendered the same, leading to confusion.

### If you got an error message, please include it here.

Here is how it reads in HTML:

> 0.0+1.0i is of type Float-Complex but 0.0+1.0i is not

**Comment by rhcarvalho** [comment]
First I thought there was a typo in the documentation, then I found the source and realized it's a problem with how the source is rendered in HTML:
 https://github.com/racket/typed-racket/blob/f603f89f50f483bc303307528f2ee495cae7d15f/typed-racket-doc/typed-racket/scribblings/guide/optimization.scrbl#L108-L109

**Comment by sorawee** [comment]
I think you can use `@racketvalfont` here. See https://github.com/racket/racket/pull/3751/files as an example. 

Do you want to submit a PR to fix the problem?

**Comment by samth** [comment]
The actual issue here is that Racket CS doesn't have mixed exactness complex numbers. That's a problem for the rendering, but more seriously the text is now inaccurate. I'll push a fix.

**Comment by rhcarvalho** [comment]
Thanks @sorawee and @samth
