### ISSUE TITLE
check-equal? not reporting error line

### ISSUE THREAD

**Issue by bestlem** [racket/typed-racket#1177]
### What version of Racket are you using?
8.3
### What program did you run?
#lang typed/racket/base

(module+ test
  (require typed/rackunit)
  (check-equal? (+ 1 1) 3))

### What should have happened?
Got an error message with error in line 5 of my file

### If you got an error message, please include it here.

; FAILURE
; /Applications/Racket v8.3/share/pkgs/rackunit-typed/rackunit/main.rkt:24:2
name:       check-equal?
location:
  /Applications/Racket v8.3/share/pkgs/rackunit-typed/rackunit/main.rkt:24:2
actual:     2
expected:   3

**Comment by AlexKnauth** [comment]
This is an issue with the `rackunit` repository which contains the `rackunit-typed` package, not the `typed-racket` repository. On the `rackunit` repository there is already an issue for this:
https://github.com/racket/rackunit/issues/120
and an open PR, though there are merge conflicts and changes requested:
https://github.com/racket/rackunit/pull/80

**Comment by bestlem** [comment]
Do the rackunit developers use typed-racket - I can't see why they would deal with something in a different language.

**Comment by capfredf** [comment]
closed in https://github.com/racket/rackunit/pull/153
