### ISSUE TITLE
hash-ref does not type check correctly

### ISSUE THREAD

**Issue by micahcantor** [racket/typed-racket#1180]
### What version of Racket are you using?
v8.3 (CS)

### What program did you run?
```rkt
(define table : (HashTable String Integer) (make-hash))
(hash-set! table "foo" 1)
(hash-ref table 5)
```
Result:
```
; hash-ref: no value found for key
;   key: 5
; [,bt for context]
```

### What should have happened?
Should have given type error since the literal `5` is not of type `String`.

**Comment by sorawee** [comment]
Note that #491 claims that the current behavior is intentional. Still, I would love to know what's the effect of taking `[(-HashTop a (-> c)) Univ]` out. Why is it required?

**Comment by samth** [comment]
It's not required; it would be a plausible design to leave it out. But
1. Leaving it in allows more programs to type check than otherwise. 
2. You get this same weirdness from immutable hash tables and simple inference + subtyping, making it seem more consistent to allow it for mutable ones too.
