### ISSUE TITLE
Support for `xml`/XExpressions

### ISSUE THREAD

**Issue by xgqt** [racket/typed-racket#1183]
Hi! I've made a quick port of `xml` to typed racket 
https://gitlab.com/xgqt/s-exp/-/blob/master/xml/typed.rkt

Is this something that could be merged to this repo or you are not interested in supporting xml/xexpressions.

**Comment by xgqt** [comment]
There may be problems with `xexpr->xml` returning `Any`.

**Comment by xgqt** [comment]
Should we assume that `permissive-xexprs` is always false?

**Comment by samth** [comment]
This seems like a useful thing to add to the `typed-racket-more` package. I would try to avoid `Any` wherever possible.
