### ISSUE TITLE
`with-linear-integer-arith2.rkt` takes forever to type check when `PLT_TR_CONSTRACTS` is on

### ISSUE THREAD

**Issue by capfredf** [racket/typed-racket#1245]
### What version of Racket are you using?
8.5.0.2+

### What program did you run?
1. recompile typed-racket-lib with `PLT_TR_CONSTRACTS` enabled

2. `racket typed-racket-test/succeed/with-linear-integer-arith2.rkt`

### What should have happened?
it should have taken `~10 seconds` to finish

### If you got an error message, please include it here.
seemingly a infinity loop

**Comment by capfredf** [comment]
the latest master https://github.com/racket/typed-racket/commit/816cd44688e843f76266d71fbd2dd89c68d685b4 should have this fixed.

**Comment by samth** [comment]
Should we reenable this test in various places then?

**Comment by capfredf** [comment]
I'll revert this https://github.com/racket/typed-racket/blob/master/typed-racket-test/info.rkt#L55. 

It is always enabled on the github ci. [It just does not run together with other integrated tests](https://github.com/racket/typed-racket/blob/master/.github/workflows/ci.yml#L38), but I'll move it back
