### ISSUE TITLE
Struct constructor from `require/typed` can't be used in untyped code

### ISSUE THREAD

**Issue by LLazarek** [racket/typed-racket#1270]
### What version of Racket are you using?

Racket v8.5 [cs]

### What program did you run?

```
#lang racket

(module def racket
  (provide (struct-out s))
  (struct s (x)))

(module interface typed/racket
  (require/typed/provide (submod ".." def)
    [#:struct s ([x : Integer])]))

(require 'interface)
(s 5)
```

### What should have happened?

No error.

### If you got an error message, please include it here.

```
test.rkt:12:0: Type Checker: Macro s from typed module used in untyped code
  in: (s 5)
  location...:
   test.rkt:12:0
  context...:
   racket-8.5/collects/syntax/wrap-modbeg.rkt:46:4
```

**Comment by mfelleisen** [comment]
This works for me in 8.6.02, 22 July

**Comment by capfredf** [comment]
this is should be fixed in https://github.com/racket/typed-racket/commit/76f4cc5915842764ebb5683b23bf02879f16178f. 

But if you come across any problems alike, feel free to open another issue
