### ISSUE TITLE
Type printing of math/array is subpar

### ISSUE THREAD

**Issue by sorawee** [racket/typed-racket#1289]
### What version of Racket are you using?

8.7 / 8.4

### What program did you run?

`(identity-matrix 3)`

### What should have happened?

In Racket 8.3, it outputs:

```
- : (Array (U One Zero))
```

After Racket 8.4, it outputs:

```
- : #(struct:Array
--
(Indexes Index (Boxof Boolean) (-> Void) (-> Indexes (U One Zero)))
#<syntax:.../array/typed-array-struct.rkt:56:13 prop:equal+hash>
#<syntax:.../array/typed-array-struct.rkt:55:13 prop:custom-write>
#<syntax:.../array/typed-array-struct.rkt:54:13 prop:custom-print-quotable>)
```

which is less readable.

### If you got an error message, please include it here.

N/A

**Comment by AlexKnauth** [comment]
This may be fixed in HEAD. In Racket version 8.6.0.1--2022-07-12 I can reproduce the ugly printout, but in Racket version 8.6.0.10--2022-08-29 I get `(Array (U One Zero))` as expected.

**Comment by sorawee** [comment]
Oh yeah, it looks fixed to me too. Closing then.
