### ISSUE TITLE
Performance regression 8.6 -> 8.7

### ISSUE THREAD

**Issue by philnguyen** [racket/typed-racket#1293]
### What version of Racket are you using?
8.7

### What program did you run?
Type-checking [philnguyen/soft-contract](https://github.com/philnguyen/soft-contract) from scratch
```
cd soft-contract/soft-contract
raco pkg install
rm compiled */compiled
time raco make -j 8 cmdline.rkt
```

### What should have happened?
Type-checking time should remain similar to 8.6

### If you got an error message, please include it here.
On a computer, with 8.6:
```
real	1m38.201s
user	4m14.191s
sys	0m31.089s
```
with 8.7:
```
real	5m4.759s
user	17m46.285s
sys	0m36.917s
```

While scv itself is dead software that nobody should use, the same regression might happen to other projects. Commit #1dde78d1 looks like the one that introduces the regression.

**Comment by jbclements** [comment]
@bennn wow, that is a pretty big slowdown...

**Comment by mfelleisen** [comment]
Wy are you @jbclements re-directing this to @bennn ? Shallow uses the exact same type-checker as the pre-existing Typed Racket; he wasn't supposed to change the type checker.

**Comment by jbclements** [comment]
@mfelleisen  It appears to me that @philnguyen was suggesting that Ben's Optional & shallow types commit was responsible for this slowdown; I was just tagging him to make it more likely that he saw the post.

**Comment by bennn** [comment]
Thanks for the report & tag. I don't know what this could be but I'll take a look.

**Comment by bennn** [comment]
Some of the cost came from adding a [`PolyRow` case to `types/subtype.rkt`](https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/types/subtype.rkt#L1133). We can probably remove that (not ideal); better  yet, maybe a fail-fast path will speed things up.

But that's only 150s of the total slowdown. Still have 600s left to track down.

**Comment by samth** [comment]
We could presumably move that case further down, which should make it happen less.

**Comment by bennn** [comment]
It was all from a `normalize-type` that checked whether Shallow could trust the results of a function.

With that removed, the PolyRow case doesn't make much difference. Keeping as-is vs. removing has about the same cost.

**Comment by bennn** [comment]
https://github.com/racket/typed-racket/pull/1296
