### ISSUE TITLE
< should accept one argument

### ISSUE THREAD

**Issue by sorawee** [racket/typed-racket#1298]
### What version of Racket are you using?

8.7

### What program did you run?

`(< 1)`

### What should have happened?

It runs fine. In untyped Racket, this produces `#t`.

### If you got an error message, please include it here.

```
 Type Checker: could not apply function;
 wrong number of arguments provided
  expected at least: 2
  given: 1 in: (< 1)
```

**Comment by sorawee** [comment]
`max` has the opposite issue. The untyped function accepts at least one argument, so in principle, an application of zero arguments could be a type error in Typed Racket. However, it doesn't do that--deferring the check to run-time.

**Comment by capfredf** [comment]
some updates: fixing the types for `min` and `max` would break code where `(apply max some-list)` and/or `(apply min some-list)` and `some-list` has type of `Listof ...` . So I will need to first fix libraries that have that issue.

**Comment by sorawee** [comment]
Perhaps it makes sense to split the PR into two parts: {`<`, `>`} and {`min`, `max`}? The improvements on the comparison operators don't need to wait for the fix on `min` and `max`.

(And perhaps we might want to reconsider if it's really a good idea to make the change to `min` and `max`).

**Comment by benknoble** [comment]
> some updates: fixing the types for `min` and `max` would break code where `(apply max some-list)` and/or `(apply min some-list)` and `some-list` has type of `Listof ...` . So I will need to first fix libraries that have that issue.

Just a comment that this is already an error if `some-list` is empty (as you know), so it seems to me that the change is warranted (but, as you said, could lead to large amounts errors).

**Comment by benknoble** [comment]
> some updates: fixing the types for `min` and `max` would break code where `(apply max some-list)` and/or `(apply min some-list)` and `some-list` has type of `Listof ...` . So I will need to first fix libraries that have that issue.

Just a comment that this is a runtime error if `some-list` is empty (as you know), so it seems to me that the change is warranted (but, as you said, could lead to large amounts errors).

**Comment by benknoble** [comment]
OTOH, if I write `(apply max xs)`, isn't the job of types to tell me that this could fail at runtime and that I need to handle the empty and non-empty cases appropriately? (Or otherwise signal that the non-empty case is impossible?)

**Comment by shhyou** [comment]
> OTOH, if I write `(apply max xs)`, isn't the job of types to tell me that this could fail at runtime and that I need to handle the empty and non-empty cases appropriately? (Or otherwise signal that the non-empty case is impossible?)

It depends, just like whether the type of `/` should only accepts non-zero divisor.

**Comment by samth** [comment]
I think there are good arguments on both sides about whether Typed Racket should prevent that particular runtime error (the way it does with `-`) or not (the way it does with `car`, which accepts arbitrary lists). But that discussion is very different when starting afresh vs changing an existing type which could break working code.
