### ISSUE TITLE
Arguably resyntax shouldn't need to run each time I edit the OP

### ISSUE THREAD

**Issue by Lazerbeak12345** [racket/typed-racket#1302]
Arguably resyntax shouldn't need to run each time I edit the OP

_Originally posted by @Lazerbeak12345 in https://github.com/racket/typed-racket/issues/1300#issuecomment-1409312035_

**Comment by samth** [comment]
I don't understand how else it would work. If the diff changes, then resyntax either re-runs or is out of date. Can you explain more about what you're suggesting?

**Comment by shhyou** [comment]
I think @Lazerbeak12345 didn't push any new diff but just edited their comment in the thread

**Comment by Lazerbeak12345** [comment]
> I think @Lazerbeak12345 didn't push any new diff but just edited their comment in the thread

Yes. This exactly

**Comment by shhyou** [comment]
> @Lazerbeak12345 said: 
> ```
>           Arguably resyntax shouldn't need to run each time I edit the OP
> ```

@Lazerbeak12345 I think you only need to remove this line

https://github.com/racket/typed-racket/blob/c2337fa807dda4f61551038878fa990096c1572c/.github/workflows/resyntax-analyze.yml#L17

The `synchronize` event:  
<https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads?actionType=synchronize#pull_request>
> A pull request's head branch was updated. For example, the head branch was updated from the base branch or new commits were pushed to the head branch.

The `edited` event:  
<https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads?actionType=edited#pull_request>:
> The title or body of a pull request was edited.
