### ISSUE TITLE
The `Nothing` type causes the type checker not to check the type.

### ISSUE THREAD

**Issue by NoahStoryM** [racket/typed-racket#1329]
### What version of Racket are you using?
`v8.9 [cs]`

### What program did you run?
I am writing a macro and I expect the type checker to check that `t2` is a subtype of `t1`, if it is not, then throw an error, so I expand the code to `(ann (ann e t2) t1)`. But I found that if the type of `e` is `Nothing`, then the type checker will not check `t1` and `t2`. I'm not sure if this is intentional.

```racket
Welcome to Racket v8.9 [cs].
> (λ () (ann (ann (or (error 'err) 123) Any) Real))
- : (-> Nothing)
#<procedure>
```

### What should have happened?
```racket
Welcome to Racket v8.9 [cs].
> (λ () (ann (ann (or (error 'err) 123) Any) Real))
string:1:16: Type Checker: type mismatch
  expected: Real
  given: Any
  in: (or (error (quote err)) 123)
 [,bt for context]
```

**Comment by capfredf** [comment]
Nothing is a subtype of any type and uninhabitable. The way `Nothing` is handled in this case is equivalent to that `False` implies `True` in classical logic.  From the perspective of program execution, any expressions after an expression of Nothing are unreachable, so whether they are ill-typed or not does not matter. 

For example, the following program type checks.
```
(lambda (x)
  (error 'hi)
  (+ 10 "hello"))
```
