### ISSUE TITLE
for/first won’t typecheck

### ISSUE THREAD

**Issue by mbutterick** [racket/typed-racket#135]
I’m aware that `for/last` cannot typecheck, but AFAIK `for/first` is supposed to work, yet does not:

```racket
#lang typed/racket/base

(for/first : Integer ([i (in-range 10)])
  i)

> Type Checker: Error in macro expansion -- insufficient type information to typecheck. 
please add more type annotations in: (for/first : Integer ((i (in-range 10))) i)
```

When typechecking is disabled, it works.

```racket
#lang typed/racket/base/no-check

(for/first : Integer ([i (in-range 10)])
  i)

> 0
```

**Comment by lexi-lambda** [comment]
This is known but undocumented, but it's noted in a comment within the code itself:

```
;; for/vector:, for/flvector:, for/and:, for/first: and
;; for/last:'s expansions can't currently be handled by the typechecker.
```

I don't know exactly what the details are that makes them unable to be typechecked, so I can't shed any more light on the problem there.

**Comment by AlexKnauth** [comment]
What's wrong with `for/vector:`? It works for me in version 6.2.0.2--2015-04-24(cd6be60/a) [3m].

**Comment by AlexKnauth** [comment]
Using the DrRacket macro stepper, it expands to the equivalent of this: (it actually uses for/fold/derived)
```racket
(let-values (((val _)
              (for/fold
               ((val #f) (stop? #f))
               ((i (stop-after (in-range 5) (lambda x stop?))))
                (values (let () i) #t))))   val)
```
If I annotate the two for/fold variables like this, it works:
```racket
(let-values (((val _)
              (for/fold
               ((val : (U Integer #f) #f) (stop? : Boolean #f))
               ((i (stop-after (in-range 10) (lambda x stop?))))
                (values (let () i) #t))))   val)
```
Should the typed versions of for/first etc. be reimplemented in terms of the typed version of `for/fold`?

**Comment by mbutterick** [comment]
> This is known but undocumented, but it's noted in a comment within the code itself:

Ah sorry, I overlooked that. 

Not clear why these functions are in the TR docs at all.
