### ISSUE TITLE
Internal Typechecker Error

### ISSUE THREAD

**Issue by AlexKnauth** [racket/typed-racket#140]
```
. . ../stuff/GitHub/repos/typed-racket/typed-racket-lib/typed-racket/utils/tc-utils.rkt:264:0: Internal Typechecker Error: type table: number of values don't agree (Byte) (Integer Integer)
while typechecking:
(#%app pos->vals pos)
originally:
(in-hash av-poss)
```

The `(in-hash av-poss)` comes from my code here:
```
    for/list ([(x y) (in-hash av-poss)]
              #:when (not {y = 0})) : (Listof Pos)
      define y-1 (assert {y - 1} y-value?)
      p(x y-1)
```

The error points to:
https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/utils/tc-utils.rkt#L263
```racket
;; raise an internal error - typechecker bug!
(define (int-err msg . args)
  (raise (make-exn:fail:tc
          (string-append
           "Internal Typechecker Error: "
           (apply format msg args)
           (format "\nwhile typechecking:\n~a\noriginally:\n~a"
                   (syntax->datum (current-orig-stx))
                   (syntax->datum (locate-stx (current-orig-stx)))))
          (current-continuation-marks))))
```

The next thing in the stack trace:
https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/types/type-table.rkt#L62
```racket
     (λ (old)
       (match-define (tooltip seen results) old)
       (if (member e seen)
           ;; the car should be the latest stx for the location
           (if (equal? e (car seen))
               ;; combine types seen at the latest
               (tooltip seen ((combine t) results))
               old)
           (tooltip (cons e seen) t)))
```

I'm guessing that the error could come from here:
https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/types/type-table.rkt#L84

**Comment by takikawa** [comment]
I can't seem to reproduce this, but I supplied my own values for variables like `y-value?`, etc in your sample. Do you have a full program that can trigger the issue?

**Comment by AlexKnauth** [comment]
Not anymore.

**Comment by AlexKnauth** [comment]
It was a more complicated program and it had some other problems, and once I fixed those this internal error went away.

**Comment by takikawa** [comment]
This doesn't seem to be reproducible, so I'm going to go ahead and close it. Feel free to re-open if you can reproduce it again.
