### ISSUE TITLE
can a function with an optional positional & kw args be typed with TR 6.0?

### ISSUE THREAD

**Issue by mbutterick** [racket/typed-racket#143]
I’m attempting to type some code that promises 6.0 compatibility, thus I must rely on TR 6.0, which has no `->*` combinator.

I have a function with a required arg, an optional positional arg, and an optional keyword arg, like so:

```racket
#lang typed/racket
;; this won’t work
(: f : (String (Option String) [#:kw (Option String)]) -> String)
(define (f arg [opt-arg #f] #:kw [kwarg #f])
  "foo")
```

In TR 6, I figured out how to handle optional positional arguments by using `case->` and then `case-lambda` to separate each arity. But that approach doesn’t work here, because keyword arguments can’t be used with `case-lambda`:

```racket
#lang typed/racket
;; this won’t work either
(: f : (case->
        ((String [#:kw (Option String)]) -> String)
        ((String (Option String) [#:kw (Option String)]) -> String)))
(define f
  (case-lambda
    [(arg) 
     (f arg #f)]
    [(arg opt-arg) 
     (f arg opt-arg #:kw #f)]
    [(arg opt-arg #:kw kwarg) ;; error "case-lambda: not an identifier in: #:kw"
     "foo"]))
```

Is there another workaround, or is the combination of optional positional & keyword arguments just unreachable?

**Comment by mbutterick** [comment]
The best I’ve been able to do is 1) make a new function `f-prime` which is like `f`, but the optional positional argument has been converted to an optional keyword argument, and 2) replace `f` with a macro called `f`that inspects the arguments and sends them to `f-prime`. If it sees a second positional argument, it gets converted to a keyword argument.

This seems to preserve the existing untyped interface while being compatible with TR 6.0.

**Comment by AlexKnauth** [comment]
This works for me in 6.0:
```racket
#lang typed/racket
(: f : (case->
        [String [#:kw (Option String)] -> String]
        [String (Option String) [#:kw (Option String)] -> String]))
(define (f arg [opt-arg #f] #:kw [kwarg #f])
  "foo")
```

**Comment by mbutterick** [comment]
Hidden in plain sight.
