### ISSUE TITLE
Error in parse-type: for-each: all lists must have same size

### ISSUE THREAD

**Issue by jsmaniac** [racket/typed-racket#157]
Tested on racket 6.2.0.2 and 6.2.0.5 (latest nightly, downloaded minutes ago).

```racket
#lang typed/racket

(define-type (a T U)
  (-> (b T)))

(define-type (b T)
  (-> (a T Number)))

(define-type (c T)
  (a (c T) Number))
```

The example above gives:

     .../usr/local/racket-6.2.0.5/share/pkgs/typed-racket-lib/typed-racket/private/parse-type.rkt:564:7: for-each: all lists must have same size; arguments were: #<procedure:check-argument> (T Number) (#<syntax:/...)

If one removes the U from (a T U), and adjust the definitions of b and c accordingly:

```racket
#lang typed/racket

(define-type (a T)
  (-> (b T)))

(define-type (b T)
  (-> (a T)))

(define-type (c T)
  (a (c T)))
```

Then one gets the following error instead:

    Type Checker: Recursive type a cannot be applied at a different type in its recursive invocation in: (a (c T))

I think it should work in both cases (the error in the second case stays if we write (a (→ (c T))), so it's not an immediate-recursion problem).

**Comment by takikawa** [comment]
Thanks for the report! This should be fixed. Though the check is still conservative, but I think it should error conservatively in fewer cases.
