### ISSUE TITLE
define-struct avoids type->contract error

### ISSUE THREAD

**Issue by bennn** [racket/typed-racket#188]
The [docs](http://docs.racket-lang.org/reference/define-struct.html?q=define-struct#%28form._%28%28lib._racket%2Fprivate%2Fbase..rkt%29._define-struct%29%29) say that `define-struct` only adds a constructor, but if I use `(struct ... #:prefab)` I run into an error generating a contract for the struct type.

Changing to `(define-struct ... #:prefab)` works great.

```
#lang typed/racket/base

(module a typed/racket/base
  (struct foo ([x : Integer]) #:prefab)
  (define-struct bar ([x : Integer]) #:prefab)

  (provide foo bar))

(module b racket/base
  (require (submod ".." a))

  ;(foo 1) ;; Type Checker: contract generation not supported for identifier foo
  (bar 1) ;; Success!
)
```

**Comment by takikawa** [comment]
Looks like this is because TR incorrectly believes that `bar` is *not* a prefab struct type even though it is. You can see this by trying `(bar-x #s(bar 3))` which fails even though `(foo-x #s(foo 3))` succeeds. I'll fix that.

**Comment by takikawa** [comment]
Fixed now. Thanks!
