### ISSUE TITLE
function with optional keyword arg documentation is out of date

### ISSUE THREAD

**Issue by martindemello** [racket/typed-racket#195]
From http://mirror.racket-lang.org/releases/6.2.1/doc/ts-guide/types.html I found

````
(->* () (Number) Number)
(->* (String String) Boolean)
(->* (#:x Number) (#:y Number) (values Number Number))
````

but I could not manage to use `->*` to type 

`(define (foo #:a [#{a : Integer} 1] #:b [#{b : Integer} 2] #:c [#{c : Integer} 3]) (+ a b c))`

Playing with :print-type in the repl gave me the working but not in the docs annotation

````
(: foo (-> [#:a Integer] [#:b Integer] [#:c Integer] Integer))
(define (foo #:a [#{a : Integer} 1] #:b [#{b : Integer} 2] #:c [#{c : Integer} 3]) (+ a b c))
````

**Comment by samth** [comment]
I think the annotation you're looking for is

```
(: foo : (->* () (#:a Integer #:b Integer #:c Integer) Integer))
```

which is an instance of the third example, with no mandatory arguments and 3 optional ones. 

The full grammar is here [in the reference](http://mirror.racket-lang.org/releases/6.2.1/doc/ts-reference/type-ref.html#%28form._%28%28lib._typed-racket%2Fbase-env%2Fbase-types-extra..rkt%29._-~3e%29%29).
