### ISSUE TITLE
Incorrect behaviour for match: returns #f when with nested condition fails

### ISSUE THREAD

**Issue by jsmaniac** [racket/typed-racket#215]
When a match clause contains nested conditions (for example matching on the elements of a list), the match outputs #f in typed racket, both when there is a matching clause below, and when there is no matching clause.

This behaviour is different from what happens with untyped racket, and it is also a hole in the typesystem, because the type checker ignores that possible #f value.

```
#lang typed/racket
(ann (match '(b) [(list 'a) 42] [_ 43]) Number)
;; => outputs #f, despite the (ann … Number)
(ann (match '(b) [(list 'a) 42]) Number)
;; => outputs #f, despite the (ann … Number)
```

The same code in untyped racket gives the expected output:

```
(match '(b) [(list 'a) 42] [_ 43])
;; => outpute 43, which is correct
(match '(b) [(list 'a) 42])
;; => Gives error “match: no matching clause for (b)”
```

**Comment by samth** [comment]
What version of Racket are you using? I don't see these errors on HEAD.

**Comment by jsmaniac** [comment]
I'm using version 20151009-a2b213a, so it's a week old. I'll check with the latest nightly.

**Comment by jsmaniac** [comment]
@samth: I tested with today's nightly, version 20151016-6199f9a (v6.3.0.1) and after removing the ~/.racket folder, and I still get the same erroneous behaviour (i.e. match returns `#f`).

**Comment by samth** [comment]
Ah, I see it was my version that was too old. In fact, my version of TR on that machine is from July 30. So it's gone bad since then.

**Comment by jsmaniac** [comment]
I tested with some of the old versions I had installed, the bug is absent in racket-6.2.900.11, but is present in racket-6.2.900.17.

**Comment by samth** [comment]
Thanks, that helps narrow it down.

**Comment by samth** [comment]
The bug was introduced by eb93a2b571179e694b8d56a18631997d937b3334. Here's a smaller example that behaves badly:

```
#lang typed/racket
(let ((x (car '(b))))
  (if (equal? x 'a)
      42
      (+ 1 "foo")))
```
