### ISSUE TITLE
Separate struct names from type names with `#:type-name` keyword

### ISSUE THREAD

**Issue by jackfirth** [racket/typed-racket#261]
Racket style uses lowercase for struct names, but typed racket style uses uppercase for type names. Typed racket also uses the struct name as a type name. This can be worked around like so:

```racket
#lang typed/racket
(struct foo ([x : Any]))
(define-type Foo foo)
```

But that doesn't change the type shown in error messages. It would be nice if there was a `#:type-name` keyword argument that let you specify a different type name from the struct name:

```racket
#lang typed/racket
(struct foo ([x : Any]) #:type-name Foo)
```

This is purely cosmetic, but it's something that drives me up a wall.

**Comment by lexi-lambda** [comment]
I have an outstanding PR (#134) that did something like this, but used a different (non-keyword) syntax. It should be pretty easy to fix to use keywords, but I never got around to doing it. If you'd like, you could take a look at that PR and try and fix it up to use `#:type-name` (which is what @samth suggested in the first place).
