### ISSUE TITLE
Can't provide promise for polymorphic struct

### ISSUE THREAD

**Issue by jsmaniac** [racket/typed-racket#268]
The fix for GH bug #159 changed the contract for promises in `typed-racket-lib/typed-racket/static-contracts/combinators/structural.rkt` from `promise/c` to `(λ (x) (and/c (promise/c x) (not/c promise/name?)))`, but this caused a new bug:

    #lang typed/racket
    (struct (A) s ([f : Any]))
    (define p (delay (s "a")))
    (provide p)

The program above fails to generate the contracts for `p`, with the error message:

    ../../../usr/local/racket-6.3.0.8/share/pkgs/typed-racket-lib/typed-racket/private/type-contract.rkt:100:0: free-identifier=?: contract violation
      expected: identifier?
      given: #<syntax:/usr/local/racket-6.3.0.8/share/pkgs/typed-racket-lib/typed-racket/static-contracts/combinators/structural.rkt:156:30 (λ (x) (and/c (promise/c x) ...>
      argument position: 1st
      other arguments...:

**Comment by samth** [comment]
Fixed by #269.
