### ISSUE TITLE
define-predicate regression

### ISSUE THREAD

**Issue by takikawa** [racket/typed-racket#271]
This should be a contract gen error, but instead the contract gen succeeds and leads to an error in Racket:

````racket
#lang typed/racket
 
(define-predicate p? (All (A) (Listof A)))
 
(let ()
  (: x (U (Listof Integer) Integer)) (define x '(1 2 3))
  (if (p? x) 0 (add1 x)))
````

(found via the TR Guide)

**Comment by samth** [comment]
That program is a syntax error for me.

**Comment by samth** [comment]
But this program has the error you described, and is probably what the docs are doing:

```
#lang racket/load
(require typed/racket)

(define-predicate p? (All (A) (Listof A)))

(let ()
  (: x (U (Listof Integer) Integer)) (define x '(1 2 3))
  (if (p? x) 0 (add1 x)))
```

Also, the top-level is hopeless.

**Comment by takikawa** [comment]
This turns out to be a problem with how TR's top-level typechecking handles ignored expressions. I'm looking into a fix.

**Comment by takikawa** [comment]
Fixed already.
