### ISSUE TITLE
Missing type annotation for flatten from racket/list

### ISSUE THREAD

**Issue by lexi-lambda** [racket/typed-racket#277]
```racket
#lang typed/racket

(flatten '(1 2 3 (4 5 6)))

; Type Checker: missing type for identifier;
;  consider using `require/typed' to import it
;   identifier: flatten
;   from module: typed/racket in: flatten
```

**Comment by lexi-lambda** [comment]
My attempts to create a valid type for this have mostly been thwarted by TR inferring overly general types. I’ve been finding it difficult to create a type that is restrictive enough while still keeping the flexibility of untyped `flatten`.

This is the type I logically came up with for this function:

```racket
(All [a] ((Rec Flattenable (U a (Listof Flattenable))) -> (Listof a)))
```

This works great if manually instantiated:

```racket
> ((inst flatten Integer) '(1 2 3 (4 5 6)))
- : (Listof Integer)
'(1 2 3 4 5 6)
```

Unfortunately, the type is far too general, since `a` can just refer to the entire first argument, producing horribly incorrect result types:

```racket
> (flatten '(1 2 3 (4 5 6)))
- : (Listof
     (List
      One
      Positive-Byte
      Positive-Byte
      (List Positive-Byte Positive-Byte Positive-Byte)))
'(1 2 3 4 5 6)
```

I’m not sure how to fix this. Semantically, the issue seems to be that `a` should never be allowed to be a list, but encoding this in the type system doesn’t seem possible? Perhaps the only way to type this function would be to use a more restrictive type? Something like this:

```racket
(All [a] ((Listof (Listof a)) -> (Listof a)))
```

That type is actually wrong, though, because it will still be incorrect if a list of lists of lists is flattened:

```racket
> (flatten '(((1) (2)) ((4) (5))))
- : (Listof (List Positive-Byte))
'(1 2 4 5)
```

Is this function typeable with Typed Racket?

**Comment by AlexKnauth** [comment]
That more restrictive type is what `append*` does, which is sort of like `flatten` except exactly 2 levels deep. 

But `flatten` can go arbitrarily many levels deep, even with the base case of zero levels deep: `(flatten "something") = '("something")`. As you said, this would require that `a` can't be a any kind of list type, which can't be expressed with the current type system.

**Comment by samth** [comment]
Unfortunately, `flatten` can't be given a particularly useful type, as @AlexKnauth points out. But we should give it _some_ type, such as `((Listof Any) -> (Listof Any))`.

**Comment by AlexKnauth** [comment]
Should it be `Any -> (Listof Any)` instead, because `(flatten "not a list")` evaluates to `'("not a list")` ?

**Comment by lexi-lambda** [comment]
Yes, it would need to be one of those types, though I’d argue both of them are pretty much useless. `Any -> (Listof Any)` would be more accurate, I guess, but I don’t think it would be any more helpful. I suppose it would be better than having no type at all, though.
