### ISSUE TITLE
correct type signature for make-do-sequence

### ISSUE THREAD

**Issue by dented42** [racket/typed-racket#279]
Now that #266 lets the parser not freak out at multiple valued sequences, it would be nice for `make-do-sequence` to have a type that allows the construction of such sequences.

It seems to me that the type should be something like this:

```
(All (Pos Val ...)
     (-> (-> (values
              (-> Pos (Values Val ...))
              (-> Pos Pos)
              Pos
              (U False (-> Pos Boolean))
              (U False (-> Val ... Boolean))
              (U False (-> Pos Val ... Boolean))))
         (Sequenceof Val ...)))
```

But I'm not an expert in such things.

**Comment by stamourv** [comment]
That looks plausible. Want to give it a shot?
The current type for `make-do-sequence` is in typed-racket-lib/typed-racket/base-env/base-env.rkt. It's written in a type-definition DSL that's slightly different from the type surface syntax, but should be easy enough to figure out.

**Comment by dented42** [comment]
Sure thing. :) I'll take a look once I have WiFi.

**Comment by bennn** [comment]
#836
