### ISSUE TITLE
PolyDot arguments can't be used on sequences or vectors.

### ISSUE THREAD

**Issue by dented42** [racket/typed-racket#287]
While working on #279, I've needed to create a type in the base environment (typed-racket-lib/typed-racket/base-env/base-env.rkt) that translates to `(Sequenceof X ... Y)`. For lists and values that is accomplished with the `ValuesDots` and `ListDots` types. In order to produce a correct type for #279 I believe a `SequenceDots` type is required.

I also noticed that there isn't a`VectorDots` type, which might have something to do with why the type checker rejects `(All (A) (A ... A -> (Vector A ... A)))`.

I'm not familiar with the internals of typed racket, but now that there are four type constructors that do/should accept dotted type arguments, (is it possible|would it be wise) to abstract this so that it's easier to do in the future?

**Comment by bennn** [comment]
#836
