### ISSUE TITLE
file-position does not accept EOF as position.

### ISSUE THREAD

**Issue by e45lee** [racket/typed-racket#297]
Currently (file-position <port> eof) fails to typecheck.  The type signature of file-position should be something like:
(case-> (-> Port Nonnegative-Integer) (-> Port (U Integer EOF) Void))
instead of:
(case-> (-> Port Nonnegative-Integer) (-> Port Integer Void))

**Comment by takikawa** [comment]
Thanks! Closed by bad5a35291f0c78823b8f4071df60f0123636486.
