### ISSUE TITLE
regression: chaperoning mutable values

### ISSUE THREAD

**Issue by bennn** [racket/typed-racket#310]
This program should blame the untyped code, but on Racket 6.4.0.7 it blames the typed module.

```
#lang racket/base

(module u racket/base
  (define (unsafe x)
    (set-box! x "one")) ;; Should be a blame error
  (provide unsafe))

(module t typed/racket/base
  (require/typed (submod ".." u)
    (unsafe (-> (Boxof Integer) Void)))
  (: typed (-> (Boxof Integer) Integer))
  (define (typed x)
    (unsafe x)
    (unbox x)) ;; Should NOT be a blame error
  (provide typed))

(require 't)
(typed (box 1))
```

Here's the output for v6.4.0.7:
```
typed: broke its own contract
  promised: Integer
  produced: "hi"
  in: the content of
      the 1st argument of
      (-> (box/c Integer) any)
  contract from: 
      (/home/ben/code/gradual/retic-test/abuse.rkt
       t)
  blaming: (/home/ben/code/gradual/retic-test/abuse.rkt t)
   (assuming the contract is correct)
```

And the output for v6.4
```
unsafe: broke its own contract
  promised: Integer
  produced: "hi"
  in: the content of
      the 1st argument of
      (-> (box/c Integer) Void)
  contract from: (interface for unsafe)
  blaming: (interface for unsafe)
   (assuming the contract is correct)
```

Changing the box to a vector gives the same results. Also, the unit tests do not catch this problem.

**Comment by rfindler** [comment]
Is there an untyped, contract-only version of this program that you're
unsatisfied with?

**Comment by bennn** [comment]
Yes.

```
#lang racket/base

(module u racket
  (define (unsafe x)
    (set-box! x "hi"))
  (provide unsafe))

(module t racket
  (require (submod ".." u))
  (define (typed x)
    (unsafe x)
    (unbox x))
  (provide (contract-out [typed (-> (box/c integer?) void?)])))

(require 't)
(typed (box 1))
```

This works as expected if `unsafe` is guarded with an `(-> (box/c integer?) void?))` contract
(`unsafe` gets blamed.)

**Comment by samth** [comment]
@bennn, that program seems to work the same on 6.4 and 6.3 as on HEAD.

**Comment by bennn** [comment]
Oh, sorry about that. Then no, I haven't yet found an untyped, contract-only version I'm unsatisfied with.

**Comment by samth** [comment]
Do you see the same behavior on 6.4?

**Comment by bennn** [comment]
Yes, I do. HEAD, 6.4, and 6.3 all blame the `typed` function, which looking back makes sense because `typed` is the only function that assumed responsibility for the box.

**Comment by bennn** [comment]
Also, when I add a contract to `unsafe` in module `t` (simulating `require/typed`) then `unsafe` gets blamed correctly.

```
#lang racket/base

(module u racket
  (define (unsafe x)
    (set-box! x "hi"))
  (provide unsafe))

(module t racket
  (require (submod ".." u))
  (define u2 (contract (-> (box/c integer?) void?) unsafe #f #f))
  (define (typed x)
    (u2 x)
    (unbox x))
  (provide (contract-out [typed (-> (box/c integer?) integer?)])))

(require 't)
(typed (box 1))
```

**Comment by takikawa** [comment]
Did this get resolved and do we know if it's a TR level problem or Racket contract level problem?

**Comment by rfindler** [comment]
Last I heard it was not a contract problem. But I may have missed new
developments.

**Comment by samth** [comment]
@bennn, can you test this again? My recent changes may have fixed it.

**Comment by bennn** [comment]
Yep, it's fixed. Running the original program on `6.4.0.15` blames `untyped` instead of `typed`. (Just like 6.4 and 6.3 do.)

**Comment by samth** [comment]
Yeah, this was just brokenness in `simple-result->` which was my fault.
