### ISSUE TITLE
Error with hash-iterate-key+value in plot3d

### ISSUE THREAD

**Issue by gus-massa** [racket/typed-racket#311]
I got this error while building the documentation:

    raco setup: 1 making: <pkgs>/typed-racket-lib/typed-racket/typecheck
      share\pkgs\plot-lib\plot\private\plot3d\bsp-trees.rkt:13:2:
      Type Checker: missing type for identifier;
    consider using `require/typed' to import it
      identifier: hash-iterate-key+value
      from module: (quote #%kernel)
      in: (for/hasheq : (HashTable Integer BSP-Tree) (((layer ss) (in-hash structura
        l-shapes))) (values layer (build-bsp-tree ss)))
      compilation context...:
        C:\Users\Nadie\Desktop\Dropbox\Hg\Racket-Master-Scribble\plt\racket\share\
        pkgs\plot-lib\plot\private\plot3d\bsp-trees.rkt

I guess the problem is here, but if I'm wrong I can "move" thi issue to the plot package.

**Comment by stchang** [comment]
I can't seem to reproduce the error. Could it be using a stale typed-racket from the download cache? (I had that problem when doing my testing.)

[This commit](https://github.com/racket/typed-racket/commit/c35716d46144ffdec63711c15ea94de3d309565b) and [this commit](https://github.com/racket/typed-racket/commit/3a245a27e08b5d91fbaf20a43e5d4bf363c98084) were supposed to fix that error.

**Comment by gus-massa** [comment]
I found the problem. I was building with a script that used

    nmake win32-as-is

instead of

    nmake win32-in-place

so it didn't update the package.
