### ISSUE TITLE
Incorrect formatting of error message

### ISSUE THREAD

**Issue by jsmaniac** [racket/typed-racket#314]
### What version of Racket are you using?
6.4.0.4
### What program did you run?
```
#lang typed/racket

; (define-type ~> Number)
(: x ~>)
(define x 1)
```
### What should have happened?
The above code should print the error message
```
Type Checker: parse error in type;
 type name `~>' is unbound in: ~>
```
### If you got an error message, please include it here.
Instead it prints the message
```
/usr/share/racket/pkgs/typed-racket-lib/typed-racket/utils/tc-utils.rkt:191:0: format: ill-formed pattern string
  explanation: tag `~>' not allowed
  pattern string: "parse error in type;\n type name `~>' is unbound"
```

My guess is that the error message is constructed with string-append at some point, instead of using something like `(format "parse error in type;\n type name `~a' is unbound" '~>)`.

This error will only occur with rather unusual type names which contain `~` in their name, so feel free to close this if it's not worth invesitgating.

**Comment by samth** [comment]
I bet it's this call to `apply`: https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/utils/tc-utils.rkt#L198

**Comment by jsmaniac** [comment]
@samth Other calls to `tc-error/delayed` give format strings as the first argument, so I think the problem must be earlier.

The call graph is:

* parse-type.rkt:parse-type https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/private/parse-type.rkt#L607
* parse-type.rkt:parse-error https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/private/parse-type.rkt#L937
* tc-utils.rkt:tc-error/fields https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/utils/tc-utils.rkt#L206
* tc-error/delayed and tc-error/stx (https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/utils/tc-utils.rkt#L191 and https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/utils/tc-utils.rkt#L252), which both contain `(apply format msg rest)`, and are both called in other places with a format string (so I think the apply there is legit)

**Comment by takikawa** [comment]
It's likely `tc-error/fields` that needs to be fixed or worked around. The function has the following comment (that apparently I wrote but can't remember):

```
;; Produce a type error using modern Racket error syntax.
;; Avoid using format directives in the `msg`, `more`, and `field`
;; strings in the rest argument (may cause unexpected errors)
```
