### ISSUE TITLE
Can't use syntax parameters defined in a typed racket module in other typed racket modules

### ISSUE THREAD

**Issue by david-christiansen** [racket/typed-racket#324]
### What version of Racket are you using?

6.4
### What program did you run?

The program consists of two modules. The first is `param.rkt`:

```
#lang typed/racket

(require racket/stxparam)

(provide param)

(define-syntax-parameter param #f)
```

The second is `importer.rkt`:

```
#lang typed/racket

(require "param.rkt" racket/stxparam)

(syntax-parameterize ([param #t]) #f)
```
### What should have happened?

I would expect it to print `#f` when I load it, and if I change `param.rkt` to be in `#lang racket`, I do.
### If you got an error message, please include it here.

```
; /home/davidchr/tmp/importer.rkt:5:23: syntax-parameterize: not bound as a syntax parameter
;   at: param
;   in: (syntax-parameterize ((param #t)) #f)
```

**Comment by david-christiansen** [comment]
One additional fact that might be relevant: if I define the syntax parameter in an untyped Racket module, I can re-export it from a typed Racket module to another typed Racket module.

**Comment by samth** [comment]
See racket/racket#1286.

**Comment by david-christiansen** [comment]
Thanks!

**Comment by jsmaniac** [comment]
I tried this with Racket v6.9.0.1, and it seems to work, both with `param.rkt` using `#lang typed/rakcet` and `#lang racket`.

@david-christiansen can this closed or are there still some problems?

**Comment by david-christiansen** [comment]
Yes, this works for me in 6.9. Thanks for the follow-up!
