### ISSUE TITLE
Type information shown in mouse over tooltips is overly generic

### ISSUE THREAD

**Issue by jackfirth** [racket/typed-racket#325]
When running this program under racket version 6.4:

```
#lang typed/racket/base
(map bytes->string/utf-8 '(#"abc" #"ABC" #"123"))
```

I can mouse over expressions in DrRacket to see their type. However the displayed type of map is the general case variadic polymorphic type. It would be nice if the mouse over type used the type information inferred from the use site. The above example shows this when mousing over `map`:

```
(All (c a b ...)
  (case->
    (-> (-> a c) (Pairof a (Listof a)) (Pairof c (Listof c)))
    (-> (-> a b ... b c) (Listof a) (Listof b) ... b (Listof c))))
```

I'd like it to show this:

```
(-> (-> Bytes String)
    (Pairof Bytes (Listof Bytes))
    (Pairof String (Listof String)))
```

**Comment by takikawa** [comment]
Thanks! Now fixed.
