### ISSUE TITLE
Internal error when calling a (Values _ _) function which can also be something else

### ISSUE THREAD

**Issue by jsmaniac** [racket/typed-racket#342]
### What version of Racket are you using?
6.4.0.15

### What program did you run?
```
#lang typed/racket
(: f (case→ (→ (→ (Values Any Any)) Any)
            (→ 'sym Any)))
(define (f g)
  (g))
```

### What should have happened?
The program *should* give the following error, which is what happens when `g` in the first `case→` returns only one value, or when using an argument with type `(U (→ (Values Any Any)) 'sym)`:
```
Type Checker: Cannot apply expression of type 'sym, since it is not a function type in: (g)
```

### If you got an error message, please include it here.
… but it gives the following error (formatted here for easier reading):
```
../../nix/store/5h7j3m2nkdsdnhmh8i3i1lvxl1dal44s-racket-6.4.0.15/share/racket/pkgs/typed-racket-lib/typed-racket/utils/tc-utils.rkt:270:0:
Internal Typechecker Error: type table: number of values don't agree (Any Any) (Nothing)
while typechecking:
(#%app g)
originally:
(g)
```

**Comment by takikawa** [comment]
Fixed by 19e8efec0f960fbbe31b8468fb512ac3521189ac. Thanks for the report!
