### ISSUE TITLE
instantiate + #:no-optimize => internal typechecker error

### ISSUE THREAD

**Issue by bennn** [racket/typed-racket#343]
@maxsnew discovered that using `instantiate` in a typed module with `#:no-optimize` raises an internal typechecking error. @takikawa traced the problem to line 37 of [`tc-app-objects.rkt`](https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/typecheck/tc-app/tc-app-objects.rkt#L37). @stamourv, can you tell us what's going wrong with the optimizer?

### What version of Racket are you using?
6.4.0.15

### What program did you run?
```
#lang typed/racket/base #:no-optimize
(require typed/racket/class)

(define c%
  (class object%
    (init-field val)
    (super-new)))

(instantiate c% (3))
```

### What should have happened?
The program should compile. It does compile if you remove `#:no-optimize`.

### If you got an error message, please include it here.
```
Internal Typechecker Error: no type for (quote 3) at: /Users/ben/code/racket/etc/tr-noopt/main.rkt line 9 col 17
while typechecking:
(#%app do-make-object lifted.0 c% (#%app list (quote 3)) (#%app list))
originally:
(instantiate c% (3))
  compilation context...:
   /Users/ben/code/racket/etc/tr-noopt/main.rkt
  context...:
   /Users/ben/code/racket/fork/extra-pkgs/typed-racket/typed-racket-lib/typed-racket/utils/tc-utils.rkt:270:0: int-err
   /Users/ben/code/racket/fork/extra-pkgs/typed-racket/typed-racket-lib/typed-racket/typecheck/tc-app/tc-app-objects.rkt:35:29: for-loop
   /Users/ben/code/racket/fork/extra-pkgs/typed-racket/typed-racket-lib/typed-racket/typecheck/tc-app/utils.rkt:23:30: check155
   /Users/ben/code/racket/fork/extra-pkgs/typed-racket/typed-racket-lib/typed-racket/typecheck/tc-expr-unit.rkt:78:0: tc-expr/check
   loop
   /Users/ben/code/racket/fork/extra-pkgs/typed-racket/typed-racket-lib/typed-racket/typecheck/tc-toplevel.rkt:321:0: type-check
   /Users/ben/code/racket/fork/extra-pkgs/typed-racket/typed-racket-lib/typed-racket/typecheck/tc-toplevel.rkt:565:0: tc-module
   /Users/ben/code/racket/fork/extra-pkgs/typed-racket/typed-racket-lib/typed-racket/tc-setup.rkt:82:0: tc-module/full
   /Users/ben/code/racket/fork/extra-pkgs/typed-racket/typed-racket-lib/typed-racket/typed-racket.rkt:24:4
   /Users/ben/code/racket/fork/racket/collects/compiler/cm.rkt:358:0: compile-zo*
   /Users/ben/code/racket/fork/racket/collects/compiler/cm.rkt:566:26
   /Users/ben/code/racket/fork/racket/collects/compiler/cm.rkt:558:42
   /Users/ben/code/racket/fork/racket/collects/compiler/cm.rkt:630:2: do-check
   /Users/ben/code/racket/fork/racket/collects/compiler/cm.rkt:718:4
   /Users/ben/code/racket/fork/racket/share/pkgs/compiler-lib/compiler/commands/make.rkt:81:8: for-loop
   /Users/ben/code/racket/fork/racket/share/pkgs/compiler-lib/compiler/commands/make.rkt: [running body]
   ...
```

**Comment by takikawa** [comment]
More specifically, I suspect that that line should be guarded with a check to see if the optimizer is on. But I wasn't sure that was the right fix since I don't quite grok that bit of code.

**Comment by stamourv** [comment]
The invariant which that line in `tc-app-objects` is breaking is that only the optimizer looks at the contents of the type table. Line 73 of `types/type-table.rkt` relies on that invariant, and only populates the type table if the optimizer is enabled. That line was presumably originally added for performance reasons, which the (more recently added) tooltip code right above it would make moot.

So I think the right thing to do is to just always populate the type table. I'll do that.

**Comment by bennn** [comment]
go team!
