### ISSUE TITLE
Scribble documentation for identifiers from typed-racket-more are not properly set up for cross-referencing

### ISSUE THREAD

**Issue by lexi-lambda** [racket/typed-racket#345]
When attempting to write documentation for a library, I want to reference the `JSExpr` type from `typed/json`. So I include the necessary imports...

```
@(require (for-label typed/json))
This function returns a @racket[JSExpr].
```

And I get this:

```
WARNING: undefined tag in <pkgs>/some-package/some-docs.scrbl
  ((lib "typed/json.rkt") JSExpr)
```

<img width="263" alt="screen shot 2016-04-13 at 21 51 12" src="https://cloud.githubusercontent.com/assets/759911/14517404/e3417420-01c1-11e6-8873-37367be14947.png">

So, digging into the docs for typed-racket-more, I notice all the modules are declared with `@defmodule[#:no-declare ...]`, which means the identifiers are not properly associated with their exporting modules. Unfortunately, looking through the Scribble documentation, I don’t see any way to declare that an identifier is exported by a particular module without putting it in a section “owned” by that module.

I’m not sure how to fix this, or if it’s possible to solve from my end or if it needs to be fixed in TR (or even in Scribble).

**Comment by samth** [comment]
I'm not sure what the best way to fix this is. The easiest fix is to remove `#:no-declare`, but that currently requires adding a lot of new sections. @mflatt, is there a way I can do that without lots of new sections? The current page is here: http://docs.racket-lang.org/ts-reference/Libraries_Provided_With_Typed_Racket.html Every library that currently provides something would need to be its own section.

**Comment by mflatt** [comment]
I think you have to add new sections, but you can make the section titles hidden with `'hidden` plus `'toc-hidden`.

**Comment by samth** [comment]
Thanks, @mflatt. Turns out I wanted `'unnumbered` as well, but that all worked nicely.
