### ISSUE TITLE
TR should optimize tail calls with many unmodified parameters

### ISSUE THREAD

**Issue by jsmaniac** [racket/typed-racket#346]
### What version of Racket are you using?
6.4.0.15

### What program did you run?

```
(: f (→ Index Index … Index Index … Number))
(define (f n many-args … modified-arg many-args …)
  (if (= n 0)
      <return>
      (f (sub1 n) many-args … (add1 modified-arg) many-args …)))
(time (f …))
```

The function f has many parameters and performs tail-calls on itself, modifying just one of the parameters and keeping the others intact. A real-world example of this pattern is a (macro-generated) function dispatching the elements of a "source" list into many "destination" queues, where each iteration will `cons` an element in front of one of the queues, and leave the others untouched. For my use case, about a hundred arguments seems quite possible.

### What should have happened?

The tail call should just update the modified argument in-place, and not touch the others at all. Therefore the execution time should not depend on the number of arguments. I ran the following benchmark, and the results suggest that this is not the case, as if the function has 10x more arguments, the program runs about 30x slower:

```
10 arguments:
cpu time: 9 real time: 9 gc time: 0

100 arguments:
cpu time: 246 real time: 245 gc time: 0

1000 arguments:
cpu time: 8332 real time: 8332 gc time: 140
```

```
#lang typed/racket

(require (for-syntax racket/list racket/function syntax/stx))

(define-syntax (bench stx)
  (syntax-case stx ()
    [(_ max args)
     (with-syntax ([(a ...) (map (λ _ (gensym)) (range (syntax-e #'args)))]
                   [(b ...) (map (λ _ (gensym)) (range (syntax-e #'args)))])
       (with-syntax ([(ta ...) (stx-map (const #'Index) #'(a ...))]
                     [(tb ...) (stx-map (const #'Index) #'(b ...))])
         #'(begin
             (: f (→ Index ta ... Index tb ...
                     Number))
             (define (f n a ... x b ...)
               (if (= 0 n)
                   (+ n a ... x b ...)
                   (f (sub1 n) a ... (assert (add1 x) index?) b ...)))
             (time (f max
                      (begin 'a (if (> (random) 0.5) 5 6)) ...
                      0
                      (begin 'b (if (> (random) 0.5) 7 8)) ...)))))]))

(bench 1000000 10)
(bench 1000000 100)
(bench 1000000 1000)
;(time (bench 1000000 10000)) ;; Out of memory during compilation
```

What worries me too is the memory consumption of TR: it uses 800MB of RAM for the program above, and I couldn't get the 10000-arguments version to compile.

Since my use case shouldn't go much beyond 100 queues I suppose I shouldn't worry, though. Feel free to close this if it's not worth spending time optimizing this.

**Comment by samth** [comment]
I don't think this is particularly a TR problem. Here's the timing results for plain racket:

```
[samth@hermes:~ plt] r ~/tmp/big.rkt
cpu time: 8 real time: 8 gc time: 0
1000130
cpu time: 232 real time: 230 gc time: 0
1001303
cpu time: 9248 real time: 9234 gc time: 148
1013016
```

Racket (or I suppose TR) could transform `f` into something with a `let loop` that passed only 2 arguments, which would limit the space usage. But in general argument-passing for large numbers of arguments will allocate.

**Comment by jsmaniac** [comment]
@samth I thought untyped Racket would not be able to check that the tail call is done with the same number of arguments (and same types), so I filed this here. Is my assumption wrong?

**Comment by samth** [comment]
In this case, it's easy to see even without types that the function is called with the right number of arguments in the recursive call (which is the relevant one). I don't think that the type of the arguments is needed for the optimization.

What I'm suggesting is transforming to:

```
(define (f n a ... x b ...)
  (let loop ([n n] [x x])
     (if (= 0 n)
         (+ n a ... x b ...)
         (loop (sub1 n) (assert (add1 x) index?)))))
```

which the compiler could do without type information.

**Comment by jsmaniac** [comment]
@samth Oh, I see what you mean. In my case, the body of the function is a big `cond` where each clause updates a different argument, so this approach wouldn't really work.

Another way to see the problem I'm trying to solve here is that TR doesn't have uniqueness types, so it can't convert updates to immutable data structures into in-place updates (like Idris and a few other languages do).

Tail calls are a case where it's easy to see that the "list of arguments" is not shared, so I hoped that the feature could be misused as a cheap way to update a large immutable list.

I thought TR's type information might be needed in case some values are unboxed on the stack, and can't just be replaced as-is.

Should I move the issue to the Racket repository, or is this too much of an edge case?

**Comment by samth** [comment]
I don't think this is something that will be easy to do either in Racket or in TR, so I'm closing this.
