### ISSUE TITLE
#:type-name messes with subtyping

### ISSUE THREAD

**Issue by jackfirth** [racket/typed-racket#351]
Given this program in Racket 6.4:

``` racket
(struct foo () #:type-name Foo)
(struct bar foo () #:type-name Bar)
```

Typechecking fails with `Type Checker: parent type not a valid structure name: foo in: foo`. I don't see why this would be. Omitting the `#:type-name` alias and adding a `(define-type Foo foo)` works fine.

**Comment by lexi-lambda** [comment]
Mmm, it’s because I hadn’t the foggiest idea what I was doing when I implemented `#:type-name` and just kinda fixed things until it mostly worked. What I’m saying is: it’s my fault, but I don’t actually know why. I might try and take a look at it this weekend when I have some time, though.

**Comment by takikawa** [comment]
It looks like this will require the same technique @samth mentions in #322. Since TR doesn't know that `foo` is associated with the type `Foo` at all, it can't get the parent type it needs to check `bar`. Fixing these issues together would make sense.

**Comment by capfredf** [comment]
I can't reproduce the problem. I think it was fixed at some point after 2016. I think this technically won't happen after #1067. But if you come cross this bug, feel free to reopen the issue
