### ISSUE TITLE
Syntax contracts are unsound within union types

### ISSUE THREAD

**Issue by AlexKnauth** [racket/typed-racket#354]
##### What version of Racket are you using?

Version 6.5.0.4--2016-04-27
##### What program did you run?

These three files:
`untyped-lib.rkt`

``` racket
#lang racket/base
(provide accept-syntax)
(define (accept-syntax stx)
  (define e (syntax-e stx))
  (cond [(and (procedure? e)
              (procedure-arity-includes? e 1))
         (e "hello")]
        [else #f]))
```

`typed-lib.rkt`

``` racket
#lang typed/racket/base
(require/typed/provide "untyped-lib.rkt"
                       [accept-syntax (-> (U False (Syntaxof Any)) Any)])
```

`typed-use.rkt`

``` racket
#lang typed/racket/base
(require "typed-lib.rkt")
(accept-syntax
 (datum->syntax #f (λ ([x : Positive-Fixnum]) (- x 1))))
```
##### What should have happened?

The contract should have somehow prevented the typed function `(λ ([x : Positive-Fixnum]) (- x 1))` from being called with the string `"hello"` in the untyped code.
##### If you got an error message, please include it here.

No error message, just the printout `#<variable-code>`, which happened because the typed function was called with the string `"hello"`.

**Comment by takikawa** [comment]
My suspicion is that this is happening because static contracts in Typed Racket are optimized before their chaperone/flat constraints are checked. So TR thinks `(U False (Syntaxof Any))` is a flat contract (before checking this fact), and optimizes it away. If you take out the optimization pass, TR raises the error that you would expect.

Though the right fix may be to make TR not think `(U False (Syntaxof Any)` is flat to begin with.

**Comment by takikawa** [comment]
It turns out that this also happens with hashtable types.

Example:

```
#lang typed/racket

(module a racket
  (define (f x)
    ((caar (hash->list x)) "hello"))
  (provide f))

(require/typed 'a [f (-> (U False (HashTable Any Any)) Any)])
(f (hash (lambda ([x : Positive-Fixnum]) (sub1 x))
         3))
```

The commonality between hashes and syntaxes is that they both require flat contracts as arguments (like this  `((syntax/sc (#:covariant #:flat)) syntax/c #:flat)` in static-contracts/combinator/structural.rkt).

**Comment by AlexKnauth** [comment]
The unsoundness in this seems to be fixed now. My original Syntax example now fails with a contract generation error:
```
. typed-lib.rkt:4:38: Type Checker:
  Type (-> (U (Syntaxof Any) False) Any) could not be converted to a contract:
  required a flat contract but generated a chaperone contract
  in: (-> (U False (Syntaxof Any)) Any)
```
And @takikawa's Hash Table example fails with a higher-order value passed as `Any` error:
```
. . f: broke its own contract
  Attempted to use a higher-order value passed as `Any` in untyped code: #<procedure>
  in: the keys of
      the 2nd conjunct of
      the 2nd conjunct of
      a part of the or/c of
      the 1st argument of
      (->
       (or/c
        (and/c
         hash?
         (and/c
          "hash-equal? (because the key contract is not a flat contract)"
          (hash/c Any Any)))
        #f)
       any/c)
  contract from: (interface for f)
  blaming: (interface for f)
   (assuming the contract is correct)
```
