### ISSUE TITLE
strange error of (peeking-input-port)

### ISSUE THREAD

**Issue by wargrey** [racket/typed-racket#355]
### What version of Racket are you using?
6.5

### What program did you run?
(peeking-input-port (current-input-port))

### What should have happened?
#<input-port:...>

### If you got an error message, please include it here.
Type Checker: could not apply function;
 wrong number of arguments provided
  expected: 5
  given: 7

**Comment by takikawa** [comment]
Closed by 36610e62397954115daa156e77bef30a84ad475a. Thanks for the report!
