### ISSUE TITLE
Cannot typecheck hash-table pattern in match

### ISSUE THREAD

**Issue by e45lee** [racket/typed-racket#363]
### What version of Racket are you using?

6.5
### What program did you run?

-> (match-define (hash-table ('x y)) (make-immutable-hash (list (cons 'x 5))))
### What should have happened?

Program should have type-checked (or should not have failed with the following
cryptic error message)
### If you got an error message, please include it here.

; readline-input:3:0: Type Checker: Polymorphic function `hash-map' could not
;   be applied to arguments:
; Domains: HashTableTop (-> Any Any c)
;          (HashTable a b) (-> a b c)
; Arguments: (HashTable Symbol Integer) (All (a) (-> a \* (Listof a)))
;   in: (match-define (hash-table ((quote x) y)) (make-immutable-hash (list
;     (cons (quote x) 5))))
; [,bt for context]

**Comment by bennn** [comment]
Seems fixed; this program works for me on 6.5 and HEAD
