### ISSUE TITLE
If branch not skipped with empty intersection type (regression)

### ISSUE THREAD

**Issue by jsmaniac** [racket/typed-racket#366]
### What version of Racket are you using?

6.5.0.5 (20160524-42e27fb)

### What program did you run?

```racket
#lang typed/racket
(struct Parent () #:transparent)
(struct (A B) S0 Parent ([a : A] [b : B]) #:transparent)
(struct (B C) S1 Parent ([b : B] [c : C]) #:transparent)

(define v : (S1 'x Integer) (S1 'x 2))
(ann (if (S0? v)
         (S0-b v) ;; ERROR HERE
         (if (S1? v)
             (S1-b v)
             (void)))
     'x)
```

### What should have happened?

The program should typecheck, as the first branch is never taken

### If you got an error message, please include it here.

```
Type Checker: Polymorphic function `S0-b' could not be applied to arguments:
Argument 1:
  Expected: (S0 A B)
  Given:    (∩ #(struct:S1 ('x Integer)) #(struct:S0 (Any Any)))

Result type:     (B : ((! False @ (((S0 A B) - 1)) (0 0)) | (False @ (((S0 A B) - 1)) (0 0))) : (((S0 A B) - 1) (0 0)))
Expected result: 'x
```

This program compiled fine with Racket v6.4.0.15, I think the new (otherwise very cool! :) ) intersection types are at cause here.

**Comment by andmkent** [comment]
This regression was caused by commit 71f17f5cb28dea687f959f69348ec4f6eb2dfd43 and doesn't have anything to do with the new intersection types.

We have made ```overlap?``` a little too conservative it seems, and it can no longer tell these two structs do not overlap. Thoughts @takikawa ?

**Comment by takikawa** [comment]
Commit b338fc6b6465079e2dccadd2687a8798b9d91c67 should fix this. Thanks @jsmaniac for the report and thanks @andmkent for pointing out the commit that broke it.
