### ISSUE TITLE
cast table sometimes has non-syntax values

### ISSUE THREAD

**Issue by samth** [racket/typed-racket#375]
The cast table (in `private/cast-table.rkt`) can sometimes contain values which are not `syntax?`. This currently breaks the `wrap` and `measures-with-dimensions` packages. The relevant call is line 351 in `prims-contract.rkt`, and the offending `existing-type` value seems to always be a `Type?`.

**Comment by AlexKnauth** [comment]
Is that this call on [line 346](https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/base-env/prims-contract.rkt#L346)? When I wrote `Type-Stx` in the signatures in cast-table.rkt, I meant it in the sense of `Path-String`, where it's either a type or a syntax object representing a type. It might make sense to make it never a syntax object, always a proper type. 

The `contract-def` struct here on [line 248](https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/base-env/prims-contract.rkt#L284), is it supposed to only take syntax objects? I see it's passed to `parse-type` [here](https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/private/type-contract.rkt#L85). Should that be changed so that it only calls `parse-type` if it's not already a type?

**Comment by samth** [comment]
The contract -def struct indeed expects only syntax objects. This error comes from that syntax object being used in an error message constructed in type-contract.rkt.

**Comment by AlexKnauth** [comment]
Would wrapping it in 3d syntax ``#`#,`` fix this?

**Comment by samth** [comment]
No, that doesn't seem right to me. We need syntax that points to the
correct place in the program.

**Comment by AlexKnauth** [comment]
But this is a type that can be computed by the typechecker. Would it make sense to make the source location for the type syntax object point to the location of the expression that produced that type?

**Comment by samth** [comment]
That seems like a good idea to me. Have you managed to reproduce this on your machine?

**Comment by AlexKnauth** [comment]
Yes. I'll try wrapping it in a syntax object with the source location of ``#'v``.

**Comment by AlexKnauth** [comment]
I tried wrapping it in a syntax object but the file in `measures-with-dimensions` was still failing, although with a different (better) error message. This program is a simplified version:
```racket
#lang typed/racket
(define v (ann (vector 1) VectorTop))
(cast v Any)
```
This succeeded before my `cast` fix, but fails now, with the error
```
. . ../../Applications/Racket/2016-06-16/Racket v6.5.0.5/share/pkgs/source-syntax/source-syntax.rkt:78:2: syntax-source: contract violation
  expected: syntax?
  given: (VectorTop 940 (combined-frees (make-immutable-hasheq) empty) (combined-frees (make-immutable-hasheq) empty) false 'vector)
```
When I wrap the type in 3d syntax before storing it, it still fails, but with the message
```
. Type Checker: Type VectorTop could not be converted to a contract: contract generation not supported for this type in: v
```
Is a better failure message where it used to succeed (being unsound) okay?

**Comment by AlexKnauth** [comment]
It looks like `wrap` has the same problem, but with `HashTableTop` instead of `VectorTop`.

**Comment by AlexKnauth** [comment]
Would it make sense to generate something like `(and/c vector? any-wrap/c)` for `VectorTop`, and `(and/c hash? any-wrap/c)` for `HashTableTop`?

**Comment by rfindler** [comment]
I think you guys have an opportunity to explore backwards compatibility in
a serious way here. Sometimes it is better to be unsound than to be
backwards incompatible. Is there a way to think about this to let people
have an easy way to out out of soundness to be able to run their programs
for a time while they work out how to fix things?

**Comment by samth** [comment]
@alexknauth Those sound like the right contracts to me.

**Comment by AlexKnauth** [comment]
For a generalization of that, would it make sense to change the `only-untyped` function here ([typed-racket/private/type-contract.rkt line 347](https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/private/type-contract.rkt#L347)) to something like
```racket
      (define (only-untyped sc)
        (if (from-typed? typed-side)
            (and/sc sc any-wrap/sc)
            sc))
```
?

**Comment by AlexKnauth** [comment]
With that, a program like this
```racket
#lang typed/racket
(define v1 (vector 1))
(define v2 (ann v1 VectorTop))
(define v3 (cast v2 (Vectorof (U Integer String))))
(vector-set! v3 0 "hi!")
```
Typechecks, but raises a contract error when the `vector-set!` is evaluated, as it needs to for soundness. The error mentions `Any` though, which is a bit weird
```
. . ../../Applications/Racket/2016-06-16/Racket v6.5.0.5/collects/racket/contract/private/blame.rkt:159:0: #(1): contract violation
  Attempted to use a higher-order value passed as `Any` in untyped code: (vector 1)
  in: Any
  contract from: typed-world
  blaming: cast
   (assuming the contract is correct)
  at: unsaved-editor:4.11
```

**Comment by AlexKnauth** [comment]
A place where `wrap` had been failing is fine (`parse.rkt`), but another file (`scan.rkt`) is still failing with the error
```
. . ../../../../../../../../../../Applications/Racket/2016-06-16/Racket v6.5.0.5/collects/racket/private/generic.rkt:488:0: 
sc->constraints: not implemented for
(recursive-sc
 (list #<syntax scan1681546> #<syntax scan1681547> #<syntax scan1681548>)
 (list (or/sc2 (list (simple-contract #<syntax:/Applications/Racket/2016-06-16/Racket v6.5.0.5/share/pkgs/typed-racket-lib/typed-racket/private/type-contract.rkt...
```

**Comment by AlexKnauth** [comment]
What is `sc->constraints`? What does `recursive-sc` normally mean, and why isn't `sc->constraints` implemented for it?

**Comment by AlexKnauth** [comment]
What is `sc->constraints` and why wouldn't it be implemented for `recursive-sc` things???

I found the signature and purpose here:
https://github.com/racket/typed-racket/blob/812f1a8c79b92640aa5a7512e8e9560ff438000d/typed-racket-lib/typed-racket/static-contracts/structures.rkt#L108

And the lack of a definition here:
https://github.com/racket/typed-racket/blob/812f1a8c79b92640aa5a7512e8e9560ff438000d/typed-racket-lib/typed-racket/static-contracts/structures.rkt#L132

The constraints seem to have something to do with whether it generates a flat, chaperone, or impersonator contract, so could it be a good default to just say impersonator contract for recursive contracts?

**Comment by AlexKnauth** [comment]
These problems raised in this issue are now fixed:
 - types in the cast table are now wrapped in syntax objects with the right source location (#376)
 - there are contracts for `VectorTop`, `HashTableTop`, etc. (#377)
 - the `sc->constraints` internal error has been replaced with an actual contract-generation error when necessary, and success otherwise (#382)
 - the `wrap` and `measures-with-dimensions` packages typecheck now (#377, #382, #383)

So this issue can be closed now.
