### ISSUE TITLE
Internal error when cast is used in dead code

### ISSUE THREAD

**Issue by AlexKnauth** [racket/typed-racket#378]
In racket version 6.5.0.5, if I compile the program

``` racket
#lang typed/racket
(cond [#false (cast 1 Integer)]
      [else 2])
```

I get the error

```
. . ../../Applications/Racket/2016-06-16/Racket v6.5.0.5/share/pkgs/typed-racket-lib/typed-racket/utils/tc-utils.rkt:270:0: 
Internal Typechecker Error: contract-def-property: thunk called too early
  This should only be called after the type-checking pass has finished.
while typechecking:
here
originally:
here
```

I expected this to succeed and produce `2` when run.

This happens because the type-checker doesn't look for the `cast` expression in dead code, and the contract-generation pass was expecting the type-checker to supply a type for it.

Should we generate an `any-wrap/c` contract in these cases? Or should the type-checker traverse dead code specifically looking for the casted-expr property?

From John Clements' report on the mailing list:
https://groups.google.com/forum/#!topic/racket-users/LGnWkOvvWlY

**Comment by samth** [comment]
I think we should traverse the dead code.

As an alternative, we could generate a contract expression that always errors when used.

**Comment by AlexKnauth** [comment]
Like a contract for `Nothing`?

**Comment by samth** [comment]
`none/c` already exists, but we'd want to write a new one that could say that this should never happen (in case it does happen, as this bug report demonstrates for something else that shouldn't have happened).

**Comment by AlexKnauth** [comment]
So something in the `contract-def` struct could tell the contract-generation pass to make a `dead-code/c` contract. Or would it make sense to make a `Dead-Code` type or something like that?

**Comment by samth** [comment]
I think the former is the best solution.

**Comment by AlexKnauth** [comment]
Ok. But can we be sure that when the type is missing from the cast-table that it's because it's dead code?

**Comment by samth** [comment]
The alternative is that it's some other error where we failed to populate the table.

**Comment by AlexKnauth** [comment]
That seems like it would be really weird... maybe we do have to traverse the dead code. So if we did that, what would it put in the cast-table?

**Comment by samth** [comment]
I think we should generate a contract that says "internal TR error" in all cases -- executing dead code is also an internal error.

**Comment by AlexKnauth** [comment]
Yes, but it would be weird to get an internal error about dead code when it's really an internal error caused by something else.

**Comment by samth** [comment]
I don't think that matters so much -- the alternative of changing the source traversal is worse. We don't need to say "dead code" in the error message.

**Comment by AlexKnauth** [comment]
So then we change the `contract-def` struct for the cases where this happens?

**Comment by samth** [comment]
Why do we need to change the struct? You should generate a contract that raises an internal error if the table hasn't been filled in.

**Comment by AlexKnauth** [comment]
But the thunk in `base-env/prims-contract.rkt` needs to communicate that to the functions in `private/type-contract.rkt`, and the only way it can do that is through the struct. That's why I thought it might be a better idea to create a `Dead-Code` type (assigned when the typechecker traverses the dead code) so that this could be encoded into the type instead of in the `contract-def` struct, and so that other types of internal errors like this could be caught at compile time.

**Comment by samth** [comment]
Why does it need to communicate that? `Dead-Code` as a type doesn't make any sense.  We thought we could issue an internal error statically when the table wasn't filled in, but dead code suggests that isn't correct. I think we should therefore defer the error to execution time,by unconditionally generating a contract that raises the internal error. Why does that need any communication?

**Comment by AlexKnauth** [comment]
The thunk in `prims-contract.rkt` needs to return a `contract-def` struct because the functions in `type-contract.rkt` all expect that. That's all I meant by communication. And that `contract-def` struct now needs to have something that the `type-contract.rkt` functions will recognize as meaning generate a contract that generates this internal error.

**Comment by AlexKnauth** [comment]
I made it fill it with a new base type with the contract `(make-none/c 'Dead-Code)`, but I'm not getting any contract errors when I trick the typechecker into thinking stuff is dead code. Is it possible the contract-generation pass is trying to optimize it away?

**Comment by AlexKnauth** [comment]
It looks like contracts for `Base` types are [assumed to be flat](https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/private/type-contract.rkt#L390), which is fine. `dead-code/c` should be a flat contract. And it also looks like flat contracts going from typed to untyped are [optimized away](https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/static-contracts/optimize.rkt#L118), which is also fine. However, with those two together, the `dead-code/c` contract is being optimized away.

Is there a good way of avoiding this? Or is there a way mark a contract so that `trusted-side-reduce` won't throw it away? Or does this not need to be avoided?

**Comment by AlexKnauth** [comment]
We should fix the internal error for 6.6, right? So is it okay if this doesn't actually raise a contract error in the cases where TR is wrong about it being dead code?

**Comment by stamourv** [comment]
Re wrong about things being dead: ISTR issues/gnats bugs reporting such cases.

**Comment by bmastenbrook** [comment]
I just ran into this problem with a cast in a begin following an error:

```racket
#lang typed/racket

(define v : Integer
  (begin
    (error "hi")
    (cast (string->number "42") Integer)))
```

**Comment by samth** [comment]
@AlexKnauth can you take a look at this? I think we just need to do the same thing as #386 for control flow.

**Comment by samth** [comment]
Actually, I want to eliminate the possibility that this happens again -- we should stop having this internal error at all, and just generate a trivial contract.
