### ISSUE TITLE
any-wrap/c is unsound on opaque mutable structures

### ISSUE THREAD

**Issue by AlexKnauth** [racket/typed-racket#379]
In racket version 6.5.0.5, if I define an opaque mutable struct in typed code, and pass it as `Any` into either untyped code or a `cast` expression, the `any-wrap/c` contract allows it to be mutated with no way to check that the value coming in matches the type. This can lead to unsoundness, for example
```racket
#lang typed/racket
(struct (X) s ([i : X]) #:mutable)
(: s1 : (s Integer))
(define s1 (s 42))
(define s2 (ann s1 Any))
(define s3 (cast s2 (s (U Integer String))))
(set-s-i! s3 "unsound!")
(s-i s1) ; the string "unsound!" with the type Integer
```

I expected the mutation to raise an error like
```
#<s>: contract violation
  Attempted to use a higher-order value passed as `Any` in untyped code: #<s>
  in: Any
  contract from: typed-world
  blaming: cast
   (assuming the contract is correct)
  at: unsaved-editor:6.11
```
Instead, this program succeeds and produces the string `"unsound!"` with the type `Integer`.

**Comment by samth** [comment]
Can you demonstrate this with two modules, rather than with `cast`?

**Comment by AlexKnauth** [comment]
Yes:
```racket
#lang racket/base
(module untyped racket/base
  (provide f)
  (define (f x) x))
(module typed typed/racket
  (struct (X) s ([i : X]) #:mutable)
  (require/typed (submod ".." untyped)
                 [f (-> Any (s (U Integer String)))])
  (: s1 : (s Integer))
  (define s1 (s 42))
  (define s2 (ann s1 Any))
  (define s3 (f s2))
  (set-s-i! s3 "unsound!")
  (s-i s1) ; the string "unsound!" with the type Integer
  )
(require 'typed)
```

**Comment by samth** [comment]
Ugh. That means that #248 is wrong.

**Comment by samth** [comment]
Also, this applies to immutable structs with mutable data (or functions) in the fields. So that change in #248 is just all wrong. :(

**Comment by bennn** [comment]
Ok so we definitely need to chaperone all structs passed as `Any`. Can we give a useful chaperone without an inspector? Or, can we somehow get an inspector (maybe from the user)?

**Comment by samth** [comment]
No, we can't chaperone without an inspector. This might be an interesting thing to think about -- could there be a chaperone we can add sensibly without an inspector, and could it be strong enough?

I'm not sure how we'd get an inspector from the user. What do you have in mind.

**Comment by AlexKnauth** [comment]
Could we change typed-racket's `struct` form to use a special inspector that typed-racket defines and that it can use to chaperone it?

**Comment by samth** [comment]
That's an interesting idea. We'd need to make sure to set `(current-inspector)` to that inspector.

Note that this wouldn't work if you purposely create a new inspector to make your struct additionally opaque, but then you get what you ask for.

**Comment by bennn** [comment]
> What do you have in mind

Something like desugaring `(ann s1 Any)` or `(f s2)` to save `(current-inspector)` in a place where `any-wrap/c` can retrieve it.

**Comment by AlexKnauth** [comment]
But it's not the `ann` that generates the contract, it's the `require/typed` or the `cast`.

**Comment by samth** [comment]
Right, the consistent problem here is that the place where the upcast occurs is not where the information is needed.

**Comment by AlexKnauth** [comment]
> That's an interesting idea. We'd need to make sure to set `(current-inspector)` to that inspector.

Setting the `current-inspector` for the whole program would be wrong though (I think?), because that would make the struct transparent for the whole program. Is there a way to set the inspector only for the chaperones?

**Comment by AlexKnauth** [comment]
Wait, do we need an inspector to chaperone opaque structures?
```racket
#lang racket
(struct foo (a))
(foo 1) ; (foo ...)
(foo-a
 (chaperone-struct
  (foo 1)
  struct:foo
  foo-a
  (λ (this a) (error 'foo-a "this = ~v, a = ~v" this a))
  ))
;foo-a: this = (foo ...), a = 1
```

**Comment by samth** [comment]
Setting current-inspector won't make everything transparent, it'll just make sure that our inspector is a parent of the current one.
