### ISSUE TITLE
Adding types to untyped values contracted with case-> via a type environment causes function application to fail

### ISSUE THREAD

**Issue by lexi-lambda** [racket/typed-racket#38]
This simple program fails:

```racket
#lang racket

(module untyped racket
  (provide
   (contract-out
    [f (case-> (-> number? number? number?))]))
  (define (f x y)
    (expt x y)))

(module type-env typed-racket/base-env/extra-env-lang
  (require (submod ".." untyped))
  (type-environment
   [f (-> -Number -Number -Number)]))

(module typed typed/racket
  (require (submod ".." type-env))
  (f 2 4))
```

It generates the following error message, which I've been unable to comprehend.

```
Type Checker: could not apply function;
 wrong number of arguments provided
  expected: 2
  given: 1 in: (#%plain-app provide/contract-id-f (quote 4))
```

I ran into this bug when attempting to use `typed/pict`, which provides functions that have `case->` contracts. For example, the following fails to compile:

```racket
#lang typed/racket
(require typed/pict)
 
(scale (circle 20) 2)
```

**Comment by lexi-lambda** [comment]
I've begun looking into this, but the behavior is complicated, and I'm unfamiliar with the code used by `provide/contract` and `contract-out`. The relevant code appears to be in `racket/contract/private/provide.rkt`, and the issue appears to be related to how values are provided using a special `set!`-transformer.

What's intriguing to me is that this only occurs with `case->` contracts. Using ordinary `->` contracts does not produce this bug. Preliminary investigation into how the provided transformers operate indicates that there are indeed separate transformers used for arrow contracts and other contracts. That is, an arrow contract will be provided as a special `#<provide/contract-arrow-transformer>` instance, while other contracts are provided as `#<provide/contract-transformer>` instances.

However, `case->` contracts use the usual contract transformers, not arrow contract transformers. This seems likely as the candidate for the discrepancy between the behavior of the two types of contracts. Unfortunately, I'm not familiar with the differences and (perhaps more importantly) the rationale behind the different transformers. I believe @rfindler is the author of the relevant code—could you perhaps clarify or provide some general information about how these work that may be related to this particular bug?

Even if this issue is not caused by this particular difference, I'm interested in what the purpose of the `partially-applied-id` field is in these transformers. Could I request a simple explanation as to what these do?

**Comment by rfindler** [comment]
The arrow transformers are contracts that are statically known to be arrow
contracts and everything else (including possibly arrow contracts that are
not known to be arrows at compile time) is the other kind.

At a high level, the arrow transformers turn n-ary functions into n+1-ary
functions where the extra argument is the blame object. This enables the
contract system to create the wrapper on the server side (not the client /
require side) which means both less code and the chance for the racket
compiler to be more aggressive about inlining.

If you can make an example using only the contract library and not TR I can
investigate more.

Robby

**Comment by lexi-lambda** [comment]
@rfindler Thanks, that was enough information for me to track down the bug.

The issue is in `typed-racket/typecheck/tc-app/tc-app-contracts.rkt`. It makes assumptions about contracted function applications that don't hold for `case->` contracts. This is the relevant code:

```racket
(define-tc/app-syntax-class (tc/app-contracts expected)
  (pattern (ctc-id:id blame e ...)
    ;; check that this is an application from the contract system
    #:when (contract-rename-id-property #'ctc-id)
    (check-contract #'ctc-id #'(e ...) expected)))
```

It ignores the `blame` argument, but no such argument exists for `case->`-contracted values. I'm not sure what the best fix would be for this. Perhaps it should ensure that the value is, in fact, an arrow transformer?

**Comment by rfindler** [comment]
I can't really tell what that fragment of code is about but the contract
system has a function that accepts syntax and returns #t when it is know to
be one of these "add1 arity" contracts. That's what's gets updated when the
set grows.

Would calling that help?

(It is a little unclear to me why tr needs to know this detail tho. It
should be able to just tell the contract system to put contracts on and not
have to worry about how it is done.)

**Comment by samth** [comment]
@rfindler This isn't about TR putting contracts on things; it's about TR trying to typecheck the expansion of functions that have contracts on them.

That function sounds like the right thing to call in the `#:when` clause of that syntax pattern.

**Comment by lexi-lambda** [comment]
Yes, that would help. What function is that?

Anyway, as to why, it's not about TR *adding* contracts to values, it's about TR typechecking function applications that include this extra argument. TR looks at the application after it's been expanded, so it has to ignore the first argument.

**Comment by rfindler** [comment]
I see.

Look for "(define-values (arrow?" In Provide.rkt. Looks like it isn't
actually pulled out tho.

But it is useless iiuc. You need the contract system to leave a property of
something to say what it did right? That fn looks at the I expanded syntax.

Robby

**Comment by lexi-lambda** [comment]
@rfindler Yes, it would need to attach a syntax property, probably with an interface similar to the existing `contract-rename-id-property`, `contract-lifted-property`, and `contract-neg-party-property`.

**Comment by rfindler** [comment]
Can I help with this somehow or do you folk have the info you need? (The
line I pointed you to before is where the syntax property could be added I
suppose.)

**Comment by lexi-lambda** [comment]
Looks like such a property already existed, TR was just looking at the wrong one. Thanks for your help!

**Comment by samth** [comment]
@rfindler Can you look at the commit linked above, and see if that makes sense? Specifically, it uses the `contract-neg-party` property -- is that always/only used when there's an extra argument?

**Comment by samth** [comment]
@rfindler it seems that @takikawa added this property, so probably he's the right person to check.

**Comment by rfindler** [comment]
I don't see any commits linked above.

**Comment by rfindler** [comment]
Oh, I see the commit, sorry. I'm still not used to this.

Anyway, I have no idea if it makes sense! But the neg-party property is wrapped around all of the "extra" neg-party arguments in the contract system, I believe. So if that's the important invariant, then it should be good.
