### ISSUE TITLE
Regression (used to typecheck but doesn't anymore)

### ISSUE THREAD

**Issue by jsmaniac** [racket/typed-racket#403]
### What version of Racket are you using?
The program below used to typecheck with version 6.5.0.8, but typechecking never ends (eats up all memory until it gets killed) with version 6.6.0.1

### What program did you run?
```racket
#lang typed/racket
  
(define-type (List3-Maybe Start Mid End)
  (Listof* Start
           (U Null
              (Pairof Mid (Listof End)))))
  
(define-type (List3 Start Mid End)
  (Listof* Start
           (Pairof Mid (Listof End))))
  
(define-type (Listof* Start End)
  (Rec R (U (Pairof Start R)
            End)))
  
(: replace-first (∀ (A B1 B2 C D)
                    (case→
                     (→ C
                        (Listof (U A B1))
                        (→ (U A B1) Any : #:+ B1 #:- (! B1))
                        (List3-Maybe A C (U A B1)))
                     (→ C
                        (Listof* A (U Null (Pairof B2 D)))
                        (→ (U A B2) Any : #:+ (! A) ;; ∴ (and (! A) B2)
                           #:- (! B2))
                        (Listof* A (U Null (Pairof C D))))
                     (→ C
                        (Listof* A (Pairof B2 D))
                        (→ (U A B2) Any : #:+ (! A) ;; ∴ (and (! A) B2)
                           #:- (! B2))
                        (Listof* A (Pairof C D)))
                     (→ C
                        (Listof A)
                        (→ (U A B1) Any)
                        (List3-Maybe A C (U A B1)))
                     (→ A
                        C
                        (Listof A)
                        (List3-Maybe A C (U A B1)))
                     (→ A
                        C
                        (Listof A)
                        (→ A (U A B1) Any)
                        (List3-Maybe A C (U A B1))))))
(define (replace-first a1 a2 a3 [a4 eq?])
  (if (list? a3)
      (replace-first a2 a3 (λ ([x : (U A B1)]) (a4 a1 x)))
      (let ([to a1]
            [pred? a3])
        (let rec ([l a2])
          (if (null? l)
              '()
              (if (pred? (car l))
                  (cons to (cdr l))
                  (cons (car l)
                        (rec (cdr l)))))))))
```

### If you got an error message, please include it here.

When running `raco make` on the file above, it just eats up all available RAM until it gets killed (exit code 137, i.e. Out Of Memory).

The first branch of the `if` can be solved by using `inst` on `(replace-first a2 a3 (λ ([x : (U A B1)]) (a4 a1 x)))`, so that it becomes `((inst replace-first A B1 Nothing C Nothing) a2 a3 (λ ([x : (U A B1)]) (a4 a1 x)))`.

The problem is that the second branch of the `if` covers multiple `case→` cases, but they can't be distinguished by any predicate. I don't thing annotations can be added there to help the typechecker.

This was a pretty extreme use case of `case→` and recursive types, so I'm not too surprised that it doesn't work anymore.

My understanding is that TR verifies that the function body typechecks for all cases in the `case→`. Annotating values which have a different type in different cases is therefore difficult/impossible. Maybe in the far future we could have some form of conditional `ann`? It could be used to annotate a value with a different type for each case of the `case→`.

**Comment by andmkent** [comment]
Thanks for the report! Fixed by the following: add a current-seen parameter to overlap #404

**Comment by stamourv** [comment]
Is this regression in (what will become) 6.6?

**Comment by stamourv** [comment]
Nevermind, discussion on #406 kind of answers my question.
