### ISSUE TITLE
[improvement] Occurrence typing should work on #:prefab fields

### ISSUE THREAD

**Issue by jsmaniac** [racket/typed-racket#407]
### What version of Racket are you using?

6.6.0.1
### What program did you run?

``` racket
#lang typed/racket
(struct s ([x : (U 'a 'b)]) #:prefab)
(define v (s 'a))
(when (eq? (s-x v) 'a)
  (ann (s-x v) 'a))
```
### What should have happened?

Since the `s` struct is immutable, this program should in theory typecheck, as the value of `(s-x v)` won't change between the `eq?` and its use.
### If you got an error message, please include it here.

```
Type Checker: type mismatch
  expected: 'a
  given: (U 'a 'b) in: (s-x v)
```

**Comment by pnwamk** [comment]
Fixed by 7599aedf2c8ea354d1b4965ec129ea4dd85f8010.
