### ISSUE TITLE
(case) fail the typechecking 

### ISSUE THREAD

**Issue by wargrey** [racket/typed-racket#458]
### What version of Racket are you using?
- 6.7

### What program did you run?

```
(case 'λparser
     [(#:backing-scale) 'real]
     [(#:height #:thickness #:outline) 'real+%]
     [(#:material) 'keywords]
     [(#:trim?) 'boolean]
     [(#:color) 'css-color]
     [(text-icon) '(string font)]
     [(regular-polygon-icon) '(natural rational)]
     [(lock-icon) 'boolean?]
     [(running-stickman-icon) 'rational]
     [(clock-icon stopwatch-icon) '(integer real)])
```

It is okay when the count of cases is less than 11 no matter what datum is.

Maybe I have to say 11 is a magic number, once I encountered an [infinite typechecking](https://groups.google.com/forum/#!topic/racket-users/S9Qac0yTfiY), it is also the 11st match fails.

### If you got an error message, please include it here.
Type Checker: type mismatch
  expected: Integer
  given: Any

**Comment by AlexKnauth** [comment]
In untyped racket, the version with 10 clauses expands into the normal nested if statement you would expect. However, the version with 11 clauses expands into something much more complicated. I'd guess that once the number of clauses gets high enough the `case` macro does extra work to try to optimize it.

When `case` expands into something simple, typed racket can do type inference on the expanded code. But when the expanded code is complicated enough, it can't.

**Comment by wargrey** [comment]
Okay, thank you to make it clear.

For the situation, the expanded code is just a hashtable + binary search, in the same source there is another (case) with more clauses and it is okay. The problem may relate to the *combination* of  `Keyword`s and `Symbol`s, but the failure occurs in an indeterminable way.

Nonetheless, it is easy to work around.

**Comment by samth** [comment]
The code that `case` generates here should type check. The only problem is we're giving an overly-specific type to the symbol keys in hash table literals. I'll look into what the right fix is.

**Comment by AlexKnauth** [comment]
Isn't the problem that we don't have a heterogeneous type for the hash table?

**Comment by samth** [comment]
No, if you look at the expansion, and annotate the table with the type `(HashTable Any Integer)` it will type check.

**Comment by bennn** [comment]
The program seems to compile on 6.11 and up
