### ISSUE TITLE
Return type of in-query wrong for single-column queries?

### ISSUE THREAD

**Issue by typeundeclared** [racket/typed-racket#460]
Using Racket 6.7.

I am attempting to convert a small piece of racket code to typed racket.  For the moment, assume there is a tasks table with a text column 'program'.  I had a piece of code like so:

    (define (fetch-programs db-conn)
      (for/list ([p (in-query db-conn
                              "select program from tasks group by program")])
        p))
    
However, I had problems getting this to type-check in racket.  Trying to make things as simple as possible, I tried this repl:

    (sequence->list (in-query db-conn "select program from tasks group by program"))

I get back the following error:

    in-query: broke its own contract;
     promised a vector,
      produced: "a-sample-string"
      in: an element of
          the range of
          (->*
           (any/c any/c)
           (#:fetch
            any/c
            #:group
            any/c
            #:group-mode
            any/c)
           #:rest
           (listof Any)
           (sequence/c (vectorof Any)))
      contract from: (interface for in-query)
      blaming: (interface for in-query)
       (assuming the contract is correct)
      at: <pkgs>/typed-racket-more/typed/db/base.rkt:72.2
  
In a non-typed-REPL, that operation works (and returns a list of strings).  It appears as though in-query, when run with a query that returns a single column of values, doesn't return a sequence of vectors of length one, but instead returns a sequence of single values.

I'm relatively new to Typed Racket---am I missing something?  Thanks in advance for your help!

**Comment by wargrey** [comment]
Sorry, this is a limitation of Typed Racket when generating contract.

vector is a mutable data, therefore meanwhile, typed db API does not allow vectors as return value.

**Comment by wargrey** [comment]
Sorry, my fault. I have forgot why I left the `in-query` in the API with the wrong annotation.

Typed Racket cannot describe this function since it returns non-fixed multiple values, so you have to change your code to work with other query APIs, say `query-rows` which aways returns a list of vectors.

**Comment by typeundeclared** [comment]
Much appreciated (both the fix and the explanation).  I'll use query-rows going forward.
