### ISSUE TITLE
`for/flvector` and `for/extflvector` documented but not provided?

### ISSUE THREAD

**Issue by AlexKnauth** [racket/typed-racket#489]
The forms `for/flvector`, `for*/flvector`,`for/extflvector`, and `for*/extflvector` are documented as being provided by `typed/racket` and `typed/racket/base`, but they are not provided there.

Should they be removed from the documentation? Or should they be provided along with the `:` versions, `for/flvector:` etc, which are provided?

**Comment by AlexKnauth** [comment]
@samth Why was this issue closed? #490 addressed a separate issue, not this one.

**Comment by samth** [comment]
I'm confused. Why doesn't that address this issue?

**Comment by AlexKnauth** [comment]
Because those four identifiers are still documented but not provided.

**Comment by AlexKnauth** [comment]
Actually, the  typechecker can now handle the expansions of `for/flvector:` etc, so it would make sense to provide the renamed versions without the colons.

However, this will conflict with `(require racket/flonum)`, so if people have both that and `(require typed/racket)` in their program, this would cause an error.

**Comment by bestlem** [comment]
I am using 8.2 or 8.3 on macOS with #lang typed/racket 

And I get the error
for/flvector: unbound identifier in: for/flvector

And for/flvector is documented in 12 Legacy Forms ot typed racket https://docs.racket-lang.org/ts-reference/Legacy_Forms.html

How do I get this to work?
