### ISSUE TITLE
HashTable keyed by newly defined subtype gives `Any` if looked up at supertype

### ISSUE THREAD

**Issue by philnguyen** [racket/typed-racket#491]
### What version of Racket are you using?

v6.7.0.4.

### What program did you run?

```{racket}
#lang typed/racket/base

(define-new-subtype New-Int (new-int Integer))
(define m : (HashTable New-Int String) (hash (new-int 0) ""))
(hash-ref m 0)
```

### What should have happened?

This should be a type error because `0` is not a `New-Int`.

### If you got an error message, please include it here.

Program type checks with result of type `Any` instead of the hash table's range.

```{racket}
- : Any
""
```

**Comment by samth** [comment]
The problem here is that you can look anything up in a hash table, so this sort of thing is never a type error.

**Comment by AlexKnauth** [comment]
You get this unexpected result because one of the possible types of `hash-ref` is `HashTableTop a -> Any`. Since `m` can be treated as a `HashTableTop`, and it can infer that `a` is whatever, it's this case that it can use to return `Any`.

**Comment by philnguyen** [comment]
Oh I see. I didn't realize this was a design decision...
