### ISSUE TITLE
Pairof Union should be equivalent to Union Pairof

### ISSUE THREAD

**Issue by jsmaniac** [racket/typed-racket#492]
### What version of Racket are you using?

6.8.0.1

### What program did you run?

```
#lang typed/racket
(ann (ann '(a . c)
          (Pairof (U 'a 'b) 'c))
     (U (Pairof 'a 'c)
        (Pairof 'b 'c)))
```

### What should have happened?

The program should typecheck, as the two types are equivalent.

Worth noting: if the types are swapped, the program typechecks.
```
#lang typed/racket
(ann (ann '(a . c)
          (U (Pairof 'a 'c)
             (Pairof 'b 'c)))
     (Pairof (U 'a 'b) 'c))
```

### If you got an error message, please include it here.

```
Type Checker: type mismatch
  expected: (U (Pairof 'a 'c) (Pairof 'b 'c))
  given: (Pairof (U 'a 'b) 'c) in: (quote (a . c))
```

**Comment by pnwamk** [comment]
`(Pairof (U 'a 'b) 'c)` = `(U (Pairof 'a 'c) (Pairof 'b 'c))`

and

`(Pairof (U 'a 'b) (U 'c 'd))` = `(U (Pairof 'a 'c) (Pairof 'a 'd) (Pairof 'b 'c) (Pairof 'b 'd))`

and so on (i.e. you get the cartesian product), which can lead to quite a bit of blow up in the size of regularly occurring types (note that `(Pairof Number Number)` is really a pair with two very large unions in each field, and so if we were applying this strategy liberally that small, simple pair type would turn into a union of pairs with over 600 elements (if I'm not mistaken in my quick calculations)).

1. It would take some experimentation to figure out what the cost of naively applying this transformation everywhere would be to confirm/deny if it is in fact too costly (I believe it is, but I'm just guessing).

2. If the naive approach is too costly, perhaps there are some ways to add this expressiveness in a more "pay-as-you-go" fashion or in the cases where it is likely to actually cause issues (I'm not sure what these approaches would look like off the top of my head).

Maybe after some reflection and shower thought some ideas will come =)

**Comment by rfindler** [comment]
Surely this is not a new problem.​

**Comment by pnwamk** [comment]
@rfindler right -- this is not new behavior.

**Comment by rfindler** [comment]
What I meant was that the problem of how to represent logical formulas in a
compact manner to support equivalence checking (or some other more
type-system like formulation of the problem) is probably not a new problem.

**Comment by pnwamk** [comment]
Ha ha, yes, this problem is definitely not unique to Typed Racket or new in general =)

**Comment by rfindler** [comment]
:)

**Comment by pnwamk** [comment]
Skimming open issues, I'm pretty certain this shortcoming is the same as was noted in issue #433 -- I'll add the example to that issue.
