### ISSUE TITLE
`exact?` and `inexact?`'s types mismatch with untyped definitions

### ISSUE THREAD

**Issue by philnguyen** [racket/typed-racket#502]
### What version of Racket are you using?

Racket `v6.8.0.2`

### What program did you run?

The following programs will result in run-time errors, because `exact?` and `inexact?`'s domain are `Any`, but the untyped implementations expect `number?`. I looked into `base-env.rkt` but didn't figure out where to fix them. I'm guessing they're defined as predicates for `Exact-Number` somewhere...

```{racket}
(exact? #t)
(inexact? '())
```

**Comment by pnwamk** [comment]
https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/base-env/base-env-numeric.rkt#L731

**Comment by AlexKnauth** [comment]
Should it be changed to `(-> Number Boolean : Exact-Number)`?

```racket
(-> N B : (-PS (-is-type 0 -ExactNumber) (-not-type 0 -ExactNumber)))
```
? Or should the false proposition be `(-is-type 0 -InexactNumber)` or something else similar?

**Comment by samth** [comment]
Unfortunately, fixing this would be backwards-incompatible, and it's already a runtime error, so we're not going to make a change here.
