### ISSUE TITLE
Positive inference

### ISSUE THREAD

**Issue by elibarzilay** [racket/typed-racket#512]
This is in 6.7, so possibly different now.

First example:

    #lang typed/racket
    (: foo : Natural -> Natural)
    (define (foo n)
      (cond [(< n 2) n]
            [else n]))

the inferred type of the `n` on the last line is `Nonnegative-Integer`,
and if the condition is *weakened*:

    #lang typed/racket
    (: foo : Natural -> Natural)
    (define (foo n)
      (cond [(< n 1) n]
            [else n]))

then the type of the last `n` becomes `Positive-Integer`.  It would be
useful if the first example did the same.

**Comment by stamourv** [comment]
`1` is a singleton type, which makes it possible to have a special case that states that the `n` in the rhs of the first clause of the second example is `0`. That doesn't work with integers in general.

**Comment by pnwamk** [comment]
Singleton types aside, wouldn't an additional type in less-than's case-> such as the following produce the information @elibarzilay desired:
`(-> Real Positive-Real Boolean : #:- Positive-Real)`

i.e. if a real `n` is not less than a positive real, then `n` must at least be a positive real (and that combined w/ already known info about `n` would produce `Positive-Integer`)

Maybe I'm missing something, though.

**Comment by stamourv** [comment]
That case (a more precise one, even) is already there (line 602 of base-env-numeric), but it's not reached; a more specific fixnum-related case matches first.

This wouldn't be a problem if our intersection types did not just pick the first matching case, but combined all of them.

I'd rather not add additional clauses to the already-nightmarish comparison types.
