### ISSUE TITLE
Type Checker: I is not bound as a type in: here

### ISSUE THREAD

**Issue by jsmaniac** [racket/typed-racket#532]
### What version of Racket are you using?
6.9.0.1

### What program did you run?

I ran the program below, and typed at the REPL `(:print-type w1)`.

```
#lang typed/racket

(struct (A) I ([v : A]) #:transparent)
(struct (A) O ([v : A]) #:transparent)

(: worklist
   (∀ (A ...)
      (→ (List (Listof (∩ A (I Any))) ...)
         (List (→ (∩ A (I Any)) (∩ A (O Any))) ...)
         (List (Listof (∩ A (O Any))) ...))))

(define (worklist roots processors)
  (error "Not Implemented Yet"))

(define w1
  (inst worklist
        (U (I Number) (O String))
        (U (I Float) (O Boolean))))
```

### What should have happened?

The type of `w1` should be printed. If `I` was not bound as a type, the location should not be "here", but something more precise :) .

### If you got an error message, please include it here.

```
../../.racket/snapshot/pkgs/typed-racket-lib/typed-racket/utils/tc-utils.rkt:49:43: Type Checker: I is not bound as a type in: here
```

The error also occurs when typing the following code at the REPL, but this code does not cause any problem if I delete the definition of `w1` (which has nothing to do with the code below):

```
(ann (λ ([x : (I Number)])
         (O (number->string (I-v x))))
       (→ (∩ (U (I Number) (O String)) (I Any))
          (∩ (U (I Number) (O String)) (O Any))))
```

Also note that if I hover the `worklist` in the definition of `w1` with my mouse, I can see that it is given the following type (the `#(struct:I (Any))` and `#(struct:O (Any))` look suspicious):

```
(-> (List
     (Listof (∩ (U (I Number) (O String)) #(struct:I (Any))))
     (Listof (∩ (U (O Boolean) (I Flonum)) #(struct:I (Any)))))
    (List
     (-> (∩ (U (I Number) (O String)) #(struct:I (Any)))
         (∩ (U (I Number) (O String)) #(struct:O (Any))))
     (-> (∩ (U (O Boolean) (I Flonum)) #(struct:I (Any)))
         (∩ (U (O Boolean) (I Flonum)) #(struct:O (Any)))))
    (List
     (Listof (∩ (U (I Number) (O String)) #(struct:O (Any))))
     (Listof (∩ (U (O Boolean) (I Flonum)) #(struct:O (Any))))))
```

### Context:

I was trying to see if I could mimic multiple dotted polymorphic type variables with the same "length", by binding a single dotted type variable `A ...` to a series of tagged unions, and use intersections to select the right case of each union.

**Comment by pnwamk** [comment]
fixed via #549
