### ISSUE TITLE
Typed unit cannot use "identifier tainted by macro transformation"

### ISSUE THREAD

**Issue by philnguyen** [racket/typed-racket#536]
### What version of Racket are you using?
`v6.9.0.1`

### What program did you run?
```racket
#lang typed/racket/base

(require typed/racket/unit)

(define-syntax-rule (define* form ...) (define form ...))

(define-signature sig^
  ())

(define-unit sig@
  (import)
  (export sig^)

  (define* (id [x : Any]) : Any x))
```

### What should have happened?
Program typechecks

### If you got an error message, please include it here.
Error message:
```racket
; id: cannot use identifier tainted by macro transformation
;   in: id
```
(My original use case was that I had a `define/memo` form that transformed a function body into its memoization.)

**Comment by philnguyen** [comment]
(I just realized that if I used `define-simple-macro` and `syntax-parse` instead of `define-syntax-rule` and `syntax-rules`, this problem is gone. It's a temporary fix for me for now.)

**Comment by dfeltey** [comment]
I think I know what's going wrong with this and how to fix it, I should be able to get to it and push a fix later today.
