### ISSUE TITLE
(∩ A-Struct A) gives nonsensical type (Rec rec179895 rec179895)

### ISSUE THREAD

**Issue by jsmaniac** [racket/typed-racket#541]
### What version of Racket are you using?
6.9.0.1

### What program did you run?
```racket
#lang typed/racket
(struct Parent ())
(struct Child ())
(define-type τ (∀ (A) (→ (∩ Child A) Any)))
;; At the REPL:
;(:type (τ Parent))
```

This prints the following type, which is wrong, and contains a self-referential recursive type which does not make any sense:

```racket
(-> (Rec rec179895 rec179895) Any)
```

### What should have happened?

The type `(τ Parent)` should be equivalent to `(→ Child Any)`.

-----

Since this is an issue with intersection types and polymorphism, it might be related to #532 .

**Comment by pnwamk** [comment]
fixed via #549
