### ISSUE TITLE
Intersection type (∩ A (U 1 2)) is displayed as (U 1 2)

### ISSUE THREAD

**Issue by jsmaniac** [racket/typed-racket#545]
### What version of Racket are you using?
6.9.0.1

### What program did you run?
```
#lang typed/racket
(define-type τ (∀ (A) (→ (∩ A (U 1 2)) Void)))
;; At the REPL:
;(:type τ)
```

### What should have happened?
The type shown at the REPL should be:

```
(∀ (A) (→ (∩ A (U 1 2)) Void))
```

But instead the following is shown
```
(All (A) (-> (U 1 2) Void))
```

**Comment by pnwamk** [comment]
fixed via #551
