### ISSUE TITLE
Unsound intersection of function types

### ISSUE THREAD

**Issue by jsmaniac** [racket/typed-racket#548]
### What version of Racket are you using?
6.9.0.1

### What program did you run?

At the REPL:
```
(:type (∩ (case→ (→ Integer Void) (→ String Void))
            (case→ (→ Integer Void))))
```

This prints `(case→ (→ Integer Void) (→ String Void))` which is NOT the intersection of the two types.

### What should have happened?

The intersection type which is printed should be `(→ Integer Void)`.

------

The same problem arises with:

```
(:type (∩ (→ (U Integer String) Void)
            (→ Integer Void)))
```

which prints `(-> (U Integer String) Void)`.

**Comment by AlexKnauth** [comment]
How is this unsound?

**Comment by jsmaniac** [comment]
It's not unsound :) . We were two programmers to think that the result computed by TR is wrong. But after giving it more careful thought, indeed it is the correct answer.

This proves that thinking about intersection types is sometimes tricky :) . Sorry about the invalid report!
