### ISSUE TITLE
New HashTable types + poor inference == broken programs =(

### ISSUE THREAD

**Issue by pnwamk** [racket/typed-racket#573]
### What version of Racket are you using?
HEAD (f2bf1062bcdc2f9ead7e1c95c6d58355add6a002)
### What program did you run?
```racket
#lang typed/racket

(define h1 (make-hash '()))

(: hfun (-> (HashTable Any Any) (HashTable Any Any)))
(define (hfun h) h)

(define h2
  (for/fold : (HashTable Any Any)
    ([h h1]) ;; <-- error highlighting the 'h' here
    ([_ (in-range 42)])
    (hfun h)))

;; Type Checker: type mismatch
;;  expected: (Mutable-HashTable Any Any)
;;  given: (U (Immutable-HashTable Any Any)
;;            (Mutable-HashTable Any Any)
;;            (Weak-HashTable Any Any)) 
;; in: h
```

There's probably a more minimal version of this, but you get the idea =(

I ran into this while building the `acquire` game from the... gradual typing benchmarks(?) @bennn pointed me to many moons ago.

### What should have happened?
It should type check (it does on 6.9). I haven't dug into this in any detail, but at a glance it looks to me like this is caused by the combination of the recent c78a25d9f1d5ea76477932a8f577c5f66ff3fe56 (which allowed for more specific types for hash tables) and of of the following:

1. our poor type inference
2. our unorthodox(?) _find annotation_ code that 'guesses' annotations for lambdas
3. ¯\\\_(ツ)\_/¯

**Comment by samth** [comment]
I think we need a case in generalize for Mutable-Hashtable.

**Comment by pnwamk** [comment]
Nailed it, @samth! 

*applause*

Adding the following 3 cases to the match in `generalize.rkt`:

```racket
[(Mutable-HashTable: k v) (-HT k v)]
[(Immutable-HashTable: k v) (-HT k v)]
[(Weak-HashTable: k v) (-HT k v)]
```

Fixes the problem for each of the various potential hash tables (I tested each, and we need all three).

I'll make a PR.
