### ISSUE TITLE
Type annotations are ignored for functions with optional arguments, no keyword arguments, and a rest argument

### ISSUE THREAD

**Issue by lexi-lambda** [racket/typed-racket#58]
Reported by Matthew Butterick on [the users mailing list](http://lists.racket-lang.org/users/archive/2015-March/066431.html).

The following code typechecks, and the arguments are all given the type `Any`.

``` racket
(: f1 ([] [String] #:rest Symbol . ->* . Any))
(define (f1 [bool #t] . syms)
 bool
 syms)
```

This also occurs if the type annotation is explicitly wrapped around a lambda expression.

``` racket
(define f1
  (ann
   (λ ([bool #f] . syms) 
     bool
     syms)
   ([] [String] #:rest Symbol . ->* . Any)))
```

The type annotation appears to be completely ignored, but this bug does not occur with functions which include keyword arguments.

**Comment by bennn** [comment]
Racket 7.4 rejects both with "wrong arity"
