### ISSUE TITLE
Optimizations missed on List types with recursive members

### ISSUE THREAD

**Issue by mbutterick** [racket/typed-racket#60]
In the sample below, the TR optimizer will reach the first `(car x)` but not the other two, even though all three types guarantee that a first member will exist.

```racket

#lang typed/racket

(define-type foo (List Symbol Any))

(: foo-car (foo . -> . Symbol))
(define (foo-car x)
  (car x)) ; optimized


(define-type bar (List Symbol (U String bar)))

(: bar-car (bar . -> . Symbol))
(define (bar-car x)
  (car x)) ; not optimized


(define-type zam (Rec z (List Symbol (U String z))))

(: zam-car (zam . -> . Symbol))
(define (zam-car x)
  (car x)) ; not optimized

```

**Comment by mbutterick** [comment]
BTW, the Optimization Coach suggests that the problem is that the list could be empty. But adding a check for non-emptiness (see example below) still does not allow the `car` to be optimized. 

In this case, however, the optimizer **will** eliminate the `'error` branch in the conditionals below. So the optimizer seems to be aware that the type can’t be `null?`, but for some reason is only partially optimizing the code.

```racket
#lang typed/racket

(define-type foo (List Symbol Any))

(: foo-car (foo . -> . Symbol))
(define (foo-car x)
  (car x)) ; optimized


(define-type bar (List Symbol (U String bar)))

(: bar-car (bar . -> . Symbol))
(define (bar-car x)
  (if (not (null? x))
      (car x) ; car still not optimized
      'error)); branch eliminated


(define-type zam (Rec z (List Symbol (U String z))))

(: zam-car (zam . -> . Symbol))
(define (zam-car x)
  (if (not (null? x))
      (car x) ; car still not optimized
      'error)); branch eliminated
```

**Comment by mbutterick** [comment]
Another data point. In this example, I’ve created a copy of the `bar` type called `bar2`. `bar2` isn’t recursive, but it has the same definition as `bar`, so it will type the same way. This time, however, the `(car x)` (under `bar2-car`) is optimized.

```racket

#lang typed/racket

(define-type bar (List Symbol (U String bar)))

(: bar-car (bar . -> . Symbol))
(define (bar-car x)
  (if (not (null? x))
      (car x)  ; not optimized
      'error)) ; optimized


(define-type bar2 (List Symbol (U String bar)))

(: bar2-car (bar2 . -> . Symbol))
(define (bar2-car x)
  (if (not (null? x))
      (car x)  ; optimized
      'error)) ; optimized

```

**Comment by stamourv** [comment]
That's weird. Will have a look.

**Comment by stamourv** [comment]
Just pushed a fix. Thanks for the report!
