### ISSUE TITLE
unsoundness with 'define-struct' in TR

### ISSUE THREAD

**Issue by jbclements** [racket/typed-racket#601]
### What version of Racket are you using?
6.10.1.2--2017-09-23(-/f) [3m].

### What program did you run?

```racket
#lang racket

(module class-helpers typed/racket

  (provide look-in-struct
           (struct-out my-struct))

  ;; PROBLEM SPECIFIC TO 'define-struct':
  (define-struct my-struct ([a : Natural]))

  (: look-in-struct (my-struct -> Natural))
  (define (look-in-struct s)
    (my-struct-a s))

  )

(require 'class-helpers)

;; SHOULD FAIL: not a natural...
(define info (my-struct "not a natural..."))

;; RETURNS STRING, NOT NATURAL
(look-in-struct info)
```

### What should have happened?

a runtime error indicating that you can't create a "my-struct" with a string.

Instead, the structure is cheerfully created, and the function that's supposed to return a Natural actually returns a string. You can easily use this to cause a seg fault in racket; I have that code, too.

Note that this problem is specific to `define-struct`. Replacing it with `struct` solves the problem, and produces a program that signals the runtime error as expected.

### If you got an error message, please include it here.

Nope, it just does the unsound thing.

**Comment by bennn** [comment]
I think the issue is that TR doesn't believe `my-struct` is a function defined in this module. And I think the way to fix that is to change the `def-tbl` built [here](https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/typecheck/tc-toplevel.rkt#L411).

There's a similar problem with `#:extra-constructor-name`. I'm not sure how to fix that.

```
#lang racket/base

(module t typed/racket/base
  (provide (struct-out yolo))

  (struct yolo ([x : Symbol]) #:extra-constructor-name unsafe))

(require 't)

(unsafe 61)
;; #<yolo>
```

**Comment by bennn** [comment]
@llazarek ran into this on one of the `gtp-benchmarks`
https://github.com/bennn/gtp-benchmarks/blob/6ecf41f3cb2b1d0aa41e6a8d87dd816ea217b7b8/benchmarks/suffixtree/typed/data.rkt#L18
