### ISSUE TITLE
map string-trim

### ISSUE THREAD

**Issue by schackbrian2012** [racket/typed-racket#608]
### What version of Racket are you using?
6.10.1

### What program did you run?
`(map string-trim null)`

### What should have happened?
`'()`

### If you got an error message, please include it here.
```
Type Checker: Polymorphic function `map' could not be applied to arguments:
Types: (-> a b ... b c) (Listof a) (Listof b) ... b -> (Listof c)
       (-> a c) (Pairof a (Listof a)) #f * -> (Pairof c (Listof c))
Arguments: (->* (String) ((U Regexp String) #:left? Any #:repeat? Any #:right? Any) String) Null #f *
Expected result: AnyValues
 in: (map string-trim null)
```

**Comment by AlexKnauth** [comment]
I think this is a problem with how type inference deals with optional keyword arguments. Here's a simpler minimal example:
```racket
#lang typed/racket
(: f : (-> Integer [#:y Integer] Integer))
(define (f x #:y [y 0]) x)

(map f null)
```

**Comment by samth** [comment]
I've written a fix for this, so it should be done soon.

**Comment by schackbrian2012** [comment]
@AlexKnauth Yes, I think you're right –– it is caused by the optional keyword arguments. My workaround was (ann string-trim (-> String String)).

@samth Nice, thanks a lot!

**Comment by pnwamk** [comment]
@samth Is the change you alluded to here on our 6.11 short list?

**Comment by samth** [comment]
Yes.

**Comment by schackbrian2012** [comment]
@samth Thank you for the commit!
