### ISSUE TITLE
assert

### ISSUE THREAD

**Issue by schackbrian2012** [racket/typed-racket#609]
### What version of Racket are you using?
6.10.1

### What program did you run?
```
(define (a b)
  (assert b number?))
```

### What should have happened?
```
> a
- : (-> Number Number)
#<procedure:a>
```

### If you got an error message, please include it here.
```
> a
- : (-> Any Number)
#<procedure:a>
```

**Comment by schackbrian2012** [comment]
Similarly for ann in place of assert.

```
(define (a b)
  (ann b Number))
```

Expected Result:
```
> a
- : (-> Number Number)
#<procedure:a>
```

Actual Result:
```
Type Checker: type mismatch
  expected: Number
  given: Any in: b
```

**Comment by pnwamk** [comment]
Typed Racket assumes any unannotated arguments to functions are of type `Any`.

So the program

```racket
(define (foo x)
  (assert x number?))
```

accepts any value (i.e. `x` is of type Any), and then it immediately asserts `x` is a Number, which returns the value of x if it is a number (and the type system knows that `(number? x)` produced `#true` and so the return type would be `Number`, and if `(number? x)` produces `#false`, then the program errors (which does not influence the return type). Thus the return type is `Number`.

**Comment by schackbrian2012** [comment]
@pnwamk Am I correct in thinking that the type will propagate forwards after an occurrence of cast, assert, and ann but not backwards before the occurrence? Is there any reason that it couldn't also propagate backwards? You say that Racket assumes that unannotated arguments have the type Any. And the argument b is not annotated in the header of the function. But it is annotated in the body of the function. Racket says that my program has a type mismatch. Technically the mismatch is not between two types that I specified. Rather the mismatch is between the type that I specified (Number) and a different type that Racket inferred (Any). So the error is not in my program but in the inference.

**Comment by samth** [comment]
The `ann` form is an annotation of the expression inside of it, and `assert` is a runtime check on the argument to `assert`. Neither one of them is specifying the type of `x` for the whole function -- if you want to do that, you need to put the annotation on the function or on the argument in the argument list.

**Comment by schackbrian2012** [comment]
@samth Got it, thank you.
