### ISSUE TITLE
return type for `memf` too generous?

### ISSUE THREAD

**Issue by mbutterick** [racket/typed-racket#61]
```racket
> memf
- : (All (a) (-> (-> a Any) (Listof a) (U False (Listof a))))
```

This return type allows `Empty` as a possible result, because `Empty` is a subtype of every `Listof ...`. Right? 

But if `memf` isn’t `False`, then it returns a positive-length list tail. Right? 

If so, perhaps there’s no need to permit `Empty`, and `memf` could use a tighter type that reflects this, e.g.:

```racket
- : (All (a) (-> (-> a Any) (Listof a) (U False (List* a (Listof a))))
```

**Comment by lexi-lambda** [comment]
This sounds right to me, and I think it should also hold for `member`/`memv`/`memq`. @samth, any possible exceptions, or is this sound?

**Comment by stamourv** [comment]
@lexi-lambda: That sounds good to me.
