### ISSUE TITLE
Proposition error from typechecking simple varargs function definition

### ISSUE THREAD

**Issue by endobson** [racket/typed-racket#619]
I'm not sure if this is a bug since the syntax for varargs is always confusing, but this looks like the scoping of the propositions is off and it is not correctly recognizing `y` and `object (0 2)` as the same thing.

```
> (lambda ([x : String] y : String *) y)
- : (-> String String * (Listof String))
#<procedure>
> (define (f [x : String] y : String *) y)
readline-input:9.38
; readline-input:9:38: Type Checker: type mismatch;
;  mismatch in proposition and object
;   expected: `((! (0 2) False) | (: (0 2) False))' and `object (0 2)'
;   given: `(Top | Bot)' and `object y'
;   in: y
; [,bt for context]
> (version)
- : String
"6.10.1.1"
>
```

**Comment by pnwamk** [comment]
I can't reproduce in DrRacket or from the REPL using snapshot 20170930-ed5911e531 =\

I also struggle with the odd infix syntax and using an asterisk for rest args =(

What was the function `f` supposed to do? (i.e. what would it's `->*` contract look like?)

**Comment by endobson** [comment]
It was supposed to take one or more strings and return the list of all but the first.

I'm rebuilding at HEAD and seeing if I can still repro.

**Comment by endobson** [comment]
Doesn't repro at head.
