### ISSUE TITLE
Bad contract for case->

### ISSUE THREAD

**Issue by bennn** [racket/typed-racket#624]
### What version of Racket are you using?

tested on 6.10.1 and 6.7

### What program did you run?

```
#lang racket/base

(module a typed/racket/base
  (define f (case-lambda [([z : Zero]) z] [([o : One]) o]))
  (provide f))
(require 'a)

(f 1)
```

### What should have happened?

```
1
```

### If you got an error message, please include it here.

```
f: contract violation
  expected: 0
  given: 1
  in: the 1st argument of
      (-> 0 any)
  contract from: 
      (..../foo.rkt
       a)
  blaming: ..../foo.rkt
   (assuming the contract is correct)
```

Not sure if TR makes an incorrect contract (using `or/c` instead of `case->`?) or its a bad optimization.

Thanks to #517 for pointing this out to me

**Comment by samth** [comment]
If you look at the type of the function, you see that this is the correct
contract. The second clause is dead code, and I believe TR warns about it.

**Comment by bennn** [comment]
Ok sorry about the noise.

I don't see the dead code warning, but the type is definitely `(-> Zero Zero)`
