### ISSUE TITLE
logical refinements: Strange error with inference, expected types, and lists

### ISSUE THREAD

**Issue by AlexKnauth** [racket/typed-racket#640]
I'm getting strange behavior where type inference using the expected type seems to be messing up something that would otherwise typecheck. When I put an expression directly as the body:
```racket
(: f : ....)
(define (f ....)
  (lyst (+ (lyst-car a) (lyst-car b))))
```
It's a type error, but if I put the body in a definition:
```racket
(: lyst+ : ....)
(define (lyst+ a b)
  (define result
    (lyst (+ (lyst-car a) (lyst-car b))))
  result)
```
It typechecks fine. The expression by itself typechecks without the expected type, and the type that the typechecker figures out without that extra information matches the expected type. So it seems like the extra information from the expected type is messing it up somehow.

#### What version of Racket are you using?

Version 6.11.0.2--2017-10-29 (512910c83f/a)

#### What program did you run?

```racket
#lang typed/racket #:with-refinements

(: lyst : (-> ([arg : Integer])
               (Refine [result : (List Integer)]
                       (= (car result) arg))))
(define (lyst arg)
  (define result (list arg))
  (assert (= (car result) arg))
  result)

(: lyst-car : (-> ([lyst : (List Integer)])
                  (Refine [result : Integer]
                          (= result (car lyst)))))
(define (lyst-car lst)
  (car lst))

(: lyst+ : (-> ([a : (List Integer)]
                [b : (List Integer)])
               (Refine [result : (List Integer)]
                       (= (car result) (+ (car a) (car b))))))
(define (lyst+ a b)
  (lyst (+ (lyst-car a) (lyst-car b))))
```

#### What should have happened?

I expected it to typecheck, just like it actually does if I transform the last function into:
```racket
(define (lyst+ a b)
  (define result
    (lyst (+ (lyst-car a) (lyst-car b))))
  result)
```

#### If you got an error message, please include it here.

```
Type Checker: type mismatch
  expected: (Refine (a : (List Integer)) (= (+ (car a) (car b)) (car a)))
  given:    (Refine (b : (List Integer)) (= (+ z y) (car b)))
  in: (lyst (+ (lyst-car a) (lyst-car b)))
```

**Comment by AlexKnauth** [comment]
With some printfs in "tc-funnap.rkt", it looks like `res` is the same in both the program that typechecks and the one that errors:
```racket
(tc-results
 (list (tc-result (Refine (i : (List Integer)) (= (+ f b) (car i)))
                  (Top | Top)
                  -))
 #f)
```
However, I am wondering what `f` and `b` are in this, whether they will/should be substituted with something...

And in the program that errors, `expected` is
```racket
(tc-results
 (list (tc-result (Refine (l : (List Integer)) (= (+ (car a) (car b)) (car l)))
                  (Top | Top)
                  -))
 #f)
```

Since `res` is the same in both, it looks like the problem is not directly within `tc/funapp`. Maybe it's in something that calls `tc-funapp`, that compares the result with the expected. And is it possible that it's being caused by a substitution not happening correctly?

**Comment by AlexKnauth** [comment]
When `check-below` is checking subtypes on [line 111 of check-below.rkt](https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/typecheck/check-below.rkt#L109-L112), should it be taking the props `p1` and `p2` into account? The props contain important information that would be needed to check the refinement types against each other.

**Comment by pnwamk** [comment]
Sorry for the delay — busy day at work and now the power is out at our house =\

That sounds like it could very well be it (not taking the props into account). I can look more into it this weekend.

Thanks for investigating!!! =)

**Comment by pnwamk** [comment]
The primary difference between the version that works and the version that doesn't, is that in the version that works, that logical info relating the various fields has been propogated into the lexical type environment and is used to prove the subtyping relation. In the version that doesn't work, that info is there (i.e. in the type result) but wasn't being used.

I think the fix is, as you suggested, to make check-below able to leverage the propositions in the type result. I have a branch with tests running now.

**Comment by AlexKnauth** [comment]
Okay, that makes sense.

**Comment by pnwamk** [comment]
cd181f9d90a42c168ffff261c3c6dfc3f23b61ef
