### ISSUE TITLE
internal error (but still running 6.11.04)

### ISSUE THREAD

**Issue by mfelleisen** [racket/typed-racket#658]
### What version of Racket are you using?

 6.11.0.4--2017-12-18(-/f) [3m].

### What program did you run?

#lang typed/racket

(struct Node [{reachable : Edge}])
(struct Edge [{to : Symbol} {cost : Positive-Integer}])

(define-type Graph [Immutable-HashTable Symbol Node])

(: make-graph (Node *-> Graph))
(define (make-graph . lo-node)
  (make-immutable-hash))

### What should have happened?

TR should have signaled a parser error for the type. 

### If you got an error message, please include it here.

Internal Typechecker Error: erroneous syntax was not a syntax object: #f
 (error message: type cannot be applied
  type: Node
  arguments...: (Error Graph))
while typechecking:
#f
originally:
#f

**Comment by bennn** [comment]
I see the same error on v6.12.0.3
