### ISSUE TITLE
incorrect fixnum op type

### ISSUE THREAD

**Issue by pnwamk** [racket/typed-racket#659]
```racket
#lang typed/racket/base

(require racket/unsafe/ops)

(fixnum?
 ((ann unsafe-fx+ (-> Zero Integer Fixnum))
  0
  (expt 2 300)))
;; produces #f
```
`unsafe-fx+` does not always return a Fixnum when given zero and any integer...

**Comment by stamourv** [comment]
This is an unsafe operation. If you give it something outside of its intended domain (fixnums), what you get out is anyone's guess.

Now, this could be an argument for restricting its argument types to be `Fixnum` (well, `Index`, if we really want to be safe), but the ergonomics of that are really bad.

Or do you have another fix in mind?

**Comment by pnwamk** [comment]
Oh, oops -- I just now noticed that almost _all_ of the function types in the type for `unsafe-fx+` do not include the Fixnum requirement on the arguments (i.e. it's not just the zero case). Sorry for the oversight!

Based on (what I thought were) the semantics for `unsafe-fx+`

```
Like +, -, *, quotient, remainder, modulo, and abs, but constrained to 
consume fixnums and produce a fixnum result.
```

I had thought `(-> Fixnum Fixnum Fixnum)` (and subtypes of it of course) would be a (more) sensible type since that type exactly describes it's runtime behavior... right?

Anyway, just my brief two cents. Someone who has written more mathy code using unsafe ops in TR would probably have a better feel for the ideal types for those ops.
