### ISSUE TITLE
Guarding newly defined subtype with supertype's predicate makes typechecking unsound

### ISSUE THREAD

**Issue by philnguyen** [racket/typed-racket#662]
### What version of Racket are you using?
6.11

### What program did you run?
```racket
#lang typed/racket/base
(define-new-subtype New-Int (new-int Integer))
(: f : New-Int → Any)
(define (f x)
  (if (integer? x) (add1 "error") 'ok))
```

### What should have happened?
Error from `(add1 "error")`

### If you got an error message, please include it here.
Program typechecked

**Comment by pnwamk** [comment]
It's a bug in `overlap?` -- we currently don't recur into the underlying type to determine if there is an overlap or not. Fix inbound.

**Comment by pnwamk** [comment]
Fixed by https://github.com/racket/typed-racket/pull/663.
