### ISSUE TITLE
Problems with define-struct/exec

### ISSUE THREAD

**Issue by LiberalArtist** [racket/typed-racket#691]
As originally reported on the [email list](https://groups.google.com/d/topic/racket-users/7hL-zpOdaT0/discussion), there are some problems using applicable structures created with `define-struct/exec`. For example, the following program fails to typecheck:
```racket
#lang typed/racket

(define-struct/exec adder ([name : Symbol])
  [(λ (this n) (add1 n)) : (-> adder Number Number)])

(define v
  (adder 'v))

(apply v '(41))
```
with the error "Type Checker: Type of argument to apply is not a function type: 
adder". 

I thought that I might need to add a type annotation, but I also am confused about how to write the type of `v` in the above program. If I change the above program to one that does typecheck:
```racket
#lang typed/racket

(define-struct/exec adder ([name : Symbol])
  [(λ (this n) (add1 n)) : (-> adder Number Number)])

(define v
  (adder 'v))

(v 41)
```
the REPL prints the type of v as simply `adder`, but, hovering over the use of `v` in the last line, the tooltip in DrRacket shows the type as `(U (-> adder Number Number) adder)`. 

This seems to be wrong. That function type is the type of the value for `adder`'s prop:procedure, not the type of an `adder` instance when used as a function. Annotating `v` with `(: v (U (-> adder Number Number) adder))` causes the program to fail to typecheck.

But it isn't clear what type should be used to annotate `v`. Writing `(: v (U (-> Number Number) adder))` also causes typechecking to fail, as does experimenting with an intersection type or simply writing `(: v (-> Number Number))`.

**Comment by capfredf** [comment]
Just came across this issue while looking for other related to one problem with intersection types. 

The reason that `apply` doesn't work is it can't handle intersection types:

```
(define (foo [v : (Intersection (-> String String) (-> Integer Integer))]) : Void
  (apply v 10)
  (void))
```
