### ISSUE TITLE
Incorrect & incomplete type for `parse-command-line`

### ISSUE THREAD

**Issue by LiberalArtist** [racket/typed-racket#692]
This is an issue to track the fact that the type of `parse-command-line` from [racket/cmdline](http://docs.racket-lang.org/reference/Command-Line_Parsing.html#%28def._%28%28lib._racket%2Fcmdline..rkt%29._parse-command-line%29%29) is both incorrect and incomplete, as noted on the [email list](https://groups.google.com/d/topic/racket-users/7hL-zpOdaT0/discussion). The problem also affects the expansion of the `command-line` macro.

The current type reported for `parse-command-line` is:
```racket
(All (b a ...)
      (-> Path-String
          (U (Listof String) (Vectorof String))
          (Listof
           (U (Pairof 'ps (Listof String))
              (Pairof
               (U 'final 'help-labels 'multi 'once-any 'once-each)
               (Listof (Listof Any)))))
          (-> Any a ... a b)
          (Listof String)
          b))
```

The problems are:

1. Most significantly, the type for the `'help-labels`/`#:help-labels` specification is wrong: the `cdr` of the pair for such entries in the table must be `(Listof String)` (like `'ps` currently), not `(Listof (Listof Any))`.
2. Similarly, the `'usage-help`/`#:usage-help` specification is not supported by the current type. It should be handled the same way as `'ps` and `'help-labels`.
3. The current type also does not support the optional "help-proc" or "unknown-proc" arguments accepted by `parse-command-line`.

@samth identified https://github.com/racket/typed-racket/blob/c526f222c270d04fc2ec88bdb0737dc6338b7871/typed-racket-lib/typed-racket/base-env/base-env.rkt#L3084 as the spot that needs to be corrected.

The following program, which fails to typecheck, illustrates the `'usage-help` problem:
```racket
#lang typed/racket

(parse-command-line
 "example"
 #("-h")
 '([usage-help "here is some usage help"])
 void
 null)
```

This program should fail to typecheck, but currently, because of the `'help-labels` problem, typechecking succeeds but `parse-command-line` raises a runtime error:
```racket
#lang typed/racket

(parse-command-line
 "example"
 #("-h")
 '([help-labels ("this is a help label")])
 void
 null)
```
Conversely, this program should typecheck and run successfully, but it currently fails to typecheck because of the `'help-labels` problem:
```racket
#lang typed/racket

(parse-command-line
 "example"
 #("-h")
 '([help-labels "this is a help label"])
 void
 null)
```

**Comment by LiberalArtist** [comment]
I have been experimenting with a change to https://github.com/racket/typed-racket/blob/c526f222c270d04fc2ec88bdb0737dc6338b7871/typed-racket-lib/typed-racket/base-env/base-env.rkt#L3084 

I have a change that fixes the problems I mentioned, but I'm encountering some additional problems I don't know how to solve. Some of them have also revealed gaps in my understanding of Typed Racket.

This is the type I am currently giving to `parse-command-line`:
```racket
(let ([mode-sym (one-of/c 'once-each 'once-any 'multi 'final)]
      [label-sym (one-of/c 'ps 'help-labels 'usage-help)])
   (-polydots
    (b a) 
    (cl->* (->opt -Pathlike
                  (Un (-lst -String) (-vec -String))
                  (-lst (Un (-pair mode-sym
                                   (-lst (-lst* (-lst -String)
                                                top-func ;; see [Q3]
                                                (-pair (Un -String (-lst -String))
                                                       (-lst -String)))))
                            (-pair label-sym
                                   (-lst -String))))
                  (->... (list (-lst Univ)) [-String a] b) ;; see [Q2]
                  (-lst -String)
                  [(-> -String Univ)
                   (Un (->* (list -String) -String Univ) ;; see [Q1]
                       (-> -String Univ))]
                  b))))
```

For ease of reading, here is how `(:print-type parse-command-line)` renders it:
```racket
(All (b a ...)
  (->* (Path-String
        (U (Listof String) (Vectorof String))
        (Listof
         (U (Pairof
             (U 'final 'multi 'once-any 'once-each)
             (Listof
              (List
               (Listof String)
               Procedure
               (Pairof (U (Listof String) String) (Listof String)))))
            (Pairof (U 'help-labels 'ps 'usage-help) (Listof String))))
        (-> (Listof Any) String ... a b)
        (Listof String))
       ((-> String Any) (-> String Any)) ;; see [Q1]
       b))
```

My most general general questions are about testing and backwards-compatibility. I've written and run some informal tests, but I'm not sure how/where/whether to include unit tests for something like this. I'm also not sure how Typed Racket approaches backwards-compatibility considerations for a change that might make some code that used to typecheck successfully now fail to typecheck or require additional annotations. 

In some cases it seems inevitable to force users to change there code: for example, if someone's code only compiled because of the `'help-labels` issue, it always would have had a run-time error anyway. But there are might be cases where a user has a correct program, but making the type more specific could require more annotations to satisfy the typechecker. For example, for pairs with a car of 'once-each`, `'once-any`, `'multi`, or `'final`, the type for the cdr had previously been `(Listof (Listof Any))`, but I have made the type more specific about the shape of a flag specification list. Personally I like this—if I'm choosing to use Typed Racket, I want typechecking errors instead of potential runtime errors—but I don't know what the stance is on such changes in general.

Then there are some more specific questions:

## [Q1] The type of "unknown-proc" prints incorrectly

The final optional argument to `parse-command-line` is a function that is called when there is an unknown command-line flag: it may either accept one string argument, in which case it is called with the offending flag, or else it must accept an unlimited number of string arguments, in which case it is given the flag and everything that follows it. (Note that the [contract given in the docs](http://docs.racket-lang.org/reference/Command-Line_Parsing.html#%28def._%28%28lib._racket%2Fcmdline..rkt%29._parse-command-line%29%29) is wrong and the prose, which says that "it must at least accept one argument (the unknown flag), but it may also accept more arguments", is confusing: a function that accepts, say, three arguments would be rejected by `parse-command-line`'s contract.) The return value is ignored: it is expected, but not required, to raise an exception.

I have written this type as `(Un (->* (list -String) -String Univ)  (-> -String Univ))`, which I believe is equivalent to `(U (-> String Any) (-> String String * Any))`, but, while it seems to be enforced correctly, the type is printed at the REPL as just `(-> String Any)`.

This issue seems to go beyond `parse-command-line`: in the following program:
```racket
#lang typed/racket

(: accept-and-call (-> (U (-> String Any) (-> String String * Any))
                       Any))
(define accept-and-call void)
```
the type of `accept-and-call` is printed as `(-> (-> String Any) Any)`.

Trying to write the above `accept-and-call` also revealed that Typed Racket doesn't seem to support the sort of occurrence typing of procedures by arity that `parse-command-line` uses. The following program, in addition to being clumsy, fails to typecheck with the confusing error, "Type of argument to apply is not a function type: (-> String Any)":
```racket
(: accept-and-call (-> (U (-> String Any) (-> String String * Any))
                       Any))
(define (accept-and-call proc)
  ;; types are not provided for normalize-arity or arity=?
  (define arity
    (procedure-arity proc))
  (cond
    [(or (arity-at-least? arity)
         (and (list? arity)
              (findf arity-at-least? arity)))
     ;; use apply to try to evade the typechecker
     (apply proc '("multi" "a" "b" "c"))]
    [else
     (proc "single")]))
```
I also noticed that the type of `apply`, `(All (a b) (-> (-> a * b) (Listof a) b))`, doesn't support non-list arguments that are implicitly `cons`ed onto the list, let alone the keyword argument case.

Using `cast` I could get `accept-and-call` to typecheck as follows, but it still enforced the type `(-> String Any)` with a runtime contract, so the following program raises a runtime error:
```racket
#lang typed/racket

(: accept-and-call (-> (U (-> String Any) (-> String String * Any))
                       Any))
(define (accept-and-call proc)
  (define arity
    (procedure-arity proc))
  (cond
    [(or (arity-at-least? arity)
         (and (list? arity)
              (findf arity-at-least? arity)))
     ((cast proc (-> String String * Any)) "multi" "a" "b" "c")]
    [else
     (proc "single")]))

(accept-and-call list)
```

## [Q2] The type of "finish-proc" permits some bad arguments

`parse-command-line` has a whole lot of requirements about its arguments that can't practically be enforced by typechecking—it would probably have a very different API if it were written with a type system in mind—but, to the extent possible, I wanted to try to be specific and rule out things that would cause runtime errors.

To that end, I changed the type of the "finish-proc" argument from `(-> Any a ... a b)` to `(-> (Listof Any) String ... a b)`, which seems to be an improvement. 

However, the following program, which I would have hoped would have failed to typecheck, actually typechecks successfully but raises a runtime error in terms of `add1`:
```racket
#lang typed/racket #:no-optimize

(parse-command-line
 "example"
 #("arg1-value" "arg2-value")
 null
 (λ ([from-flags : (Listof Any)]
     [arg1 : String]
     [arg2 : Natural 1])
   (add1 arg2)
   'finish-result)
 `("arg1" "arg2"))
```

Note that, if `arg2` were not optional, the program would indeed fail to typecheck, which is the improvement over the old type for "finish-proc".

From my experiments exploring this and my next question, I think I don't actually understand "dotted type variables" introduced by `All` very well, and the only documentation I can find on them is the brief guide section on [Non-Uniform Variable-Arity Functions](http://docs.racket-lang.org/ts-guide/types.html#%28part._.Non-.Uniform_.Variable-.Arity_.Functions%29): the reference entry for [All](http://docs.racket-lang.org/ts-reference/type-ref.html#%28form._%28%28lib._typed-racket%2Fbase-env%2Fbase-types-extra..rkt%29._.All%29%29) doesn't even mention them beyond the enty in the grammar.

## [Q3] The type for flag-handling procedures isn't very useful

Per the documentation for `parse-command-line`, "a handler procedure’s arity must either be a number or an arity-at-least value" (i.e. not a list). It must accept at least one argument (the flag string), and any additional arguments will also be strings.

However, I can't figure out a type that would successfully check any of those requirements other than that it must be a procedure. (I am currently using the type `Procedure`, which I have confirmed works despite the [warning in the docs](http://docs.racket-lang.org/ts-reference/type-ref.html#%28form._%28%28lib._typed-racket%2Fbase-env%2Fbase-types..rkt%29._.Procedure%29%29) that "the type-checker cannot allow values of this type to be applied", presumably because @samth [said](https://groups.google.com/d/msg/racket-users/7hL-zpOdaT0/nDQBaeqIBwAJ) that "Typed Racket doesn't actually generate a 
contract for `parse-command-line` (or for other built-in functions like `+` or `list`)". 

In particular, my attempts at using dotted type variables to create a type similar to that of the "finish-proc" didn't work, which is part of why I think that I may not understand dotted type variables properly.

**Comment by samth** [comment]
Thanks, this is excellent work. 

In general, I think we should not try to make the type of `parse-command-line` super-precise. There are a few reasons for this. One is backwards-compatibility -- we don't want to break people's code that type checked unless we really have to (such as because otherwise the type system would be unsound). But the bigger reason is that `parse-command-line` is mostly used via `command-line` and thus has significant checking done by the macro, and many potential problems can be avoided.

So I would overall answer your questions by looking for things that make the maximum number of uses of `command-line` type check without introducing unsoundness. 

On to the individual questions:

##### Q1

As you noticed, TR doesn't refine procedure arguments by arity. What you see with the union type not printing is that `(U (A -> B) (A * -> B))` is actually the same as `(A -> B)` from the perspective of checking the input to `parse-command-line`. The only requirement on the user is providing a `(String -> Any)` function, so it's fine to just use that as the type.

##### Q2

The problem here is that you can use a function with an optional argument as if it doesn't have that argument, so the type checker allows providing `((Listof Any) String [Natural] -> Any)` when it needs `((Listof Any) String -> Any)`. This is important because adding an optional argument shouldn't break places where you don't use it. The problem is then that the implementation of `parse-command-line` passes extra arguments, which don't turn out to be an arity error. 

This is a fairly serious problem in some sense -- as you note, there's potential unsoundness here. But it's not at all easy to fix, and it's already there in the current type for `parse-command-line`, so I don't think you should need to fix it in this issue.

##### Q3

Just using `Procedure` will allow everything, because the code calling the function is untyped (and not contracted, as you note). But that will fail to protect the function passed in, just as with the issue in Q2. So I think we should do the same thing as in `finish-proc`, or just not improve them.

Thanks again for taking a look at this (somewhat tricky) issue.

**Comment by LiberalArtist** [comment]
Thanks for the quick reply.

**Q2**

The explanation makes sense and is basically what I figured in terms of optional arguments.

I had expected the typed procedure to be protected by a contract when it flowed into untyped code, but maybe that is another effect of the fact that contracts aren't actually generated for built-in functions.

**Q3**

In terms of doing "the same thing as in `finish-proc`", I had tried writing `(-polydots (c) (->... (list -String) [-String c] Univ))` where I currently have `top-func`, but it didn't seem to actually work, and I don't really understand why: programs like the following would fail to typecheck:
```racket

#lang typed/racket #:no-optimize

(parse-command-line
 "example"
 #("--one-arg-flag" "single-arg")
 `([once-each . ([("--one-arg-flag") 
                  ,(λ ([flag : String] [arg : String])
                     arg)
                  ("takes a <single-arg>" "single-arg")])])
 void
 null)
```

If the answer is complicated, I'll just make a PR with `Procedure`.

For ease of reading, this is how the type of `parse-command-line` prints with the change for that example:
```racket
(All (b a ...)
  (->* (Path-String
        (U (Listof String) (Vectorof String))
        (Listof
         (U (Pairof
             (U 'final 'multi 'once-any 'once-each)
             (Listof
              (List
               (Listof String)
               (All (c ...) (-> String String ... c Any))
               (Pairof (U (Listof String) String) (Listof String)))))
            (Pairof (U 'help-labels 'ps 'usage-help) (Listof String))))
        (-> (Listof Any) String ... a b)
        (Listof String))
       ((-> String Any) (-> String Any))
       b))
```

**Comment by samth** [comment]
The problem is that the `All` quantifier is in the wrong place -- your type requires the user to supply a polymorphic function, instead of what you intended. That's why the other `All` is at the top.  However, just doing that here won't help, because then all the different functions would have to have the _same_ number of string arguments.

Instead I suggest putting an explicit union with the first few possible arities: `(U (String -> Any) (String String -> Any) ......)`. It's unfortunate that we don't have a better solution, but as you say this interface isn't really designed for typing.
