### ISSUE TITLE
Missing optimization of flat contract

### ISSUE THREAD

**Issue by samth** [racket/typed-racket#713]
This program should generate an `any` result contract for `f`, but doesn't:

```
#lang typed/racket
(struct: splice ())
(define-type T (U Bytes splice #f))
(: f :  -> T)
(define (f) #f)
(provide f)
```

Removing any components of the type `T` makes the problem go away. 

Thanks to @tonyg for the original example.

**Comment by bennn** [comment]
fixed via #716
