### ISSUE TITLE
New version of TR renders import of Sexp unusably slow

### ISSUE THREAD

**Issue by jbclements** [racket/typed-racket#722]
In the most recent versions of DrR built from source, a change to TR has introduced a slowdown in my code that renders it unusable.

Fortunately, the example that demonstrates this is well-behaved and stable.

Specifically, it appears that using typed/require to import a value using the “Sexp” type results in computation that is exponential in the length of the list. 

With the file below, you can try commenting out suffixes of the defined datum to see what the performance looks like. For a list of length zero, it’s basically compile time, and it winds up being about 1.7 seconds. However, as the length of the list increases, the time taken to run the file (a.k.a. the gap between printing “a” and “b”) skyrockets, and by the time you get to a list of length 32, it takes about 22 seconds. I ran out of patience for timing it, but it certainly looks exponential.

Here’s the timing data I collected:

(define timing-data
  '((0  (1.68 1.66 1.67))
    (4  (1.92 1.96 1.93))
    (8  (2.28 2.25 2.30))
    (12 (2.72 2.71 2.72))
    (16 (3.83 3.85 3.80))
    (20 (5.57 5.58 5.60))
    (24 (8.29 8.23 8.27))
    (28 (13.88 13.90 13.90))
    (32 (22.10 22.31 22.32))))

It’s worth noting that there’s a super-simple workaround: importing the datum with the type “(Listof Sexp)” rather than “Sexp” appears to eliminate the exponential slowdown completely.

### What version of Racket are you using?

version 6.90.0.29--2018-05-14(-/f) [3m]. (built from head)

### What program did you run?

Here's the file bad-schedule.rkt:

```racket
#lang typed/racket


(printf "b\n")

(require/typed "schedule-2188.rkt"
               [datum (Listof (Listof Sexp))]
               )

(printf "c\n")
```

Here's the file schedule-2188.rkt:

```racket
#lang racket/base

(provide datum)

(define datum

  '((v0 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v1 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v2 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v3 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v4 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v5 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v6 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v7 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v8 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v9 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v10 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v11 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v12 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v13 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v14 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v15 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v16 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v17 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v18 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v19 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v20 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v21 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v22 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v23 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v24 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v25 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v26 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v27 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v28 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v29 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v30 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v31 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v32 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v33 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v34 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v35 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v36 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v37 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v38 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v39 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v40 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v41 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v42 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v43 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v44 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v45 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v46 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v47 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v48 (f 423 12 42) (w 23 11) (s 78 123 4))
  (v49 (f 423 12 42) (w 23 11) (s 78 123 4)))
)
```

### What should have happened?

printout of 
```racket
a
b
```
in about two seconds.

**Comment by samth** [comment]
Do you know which version introduced this slowdown (even by a day)?

**Comment by samth** [comment]
I think the two most likely culprits are d6cdb811ba06c10b6bb73e614f43e9d13cd1c62e (by @bennn) and racket/racket@0b3f4b627e748847ed239d7f0d3f69b424e469b1 (by @rfindler). The latter of these is known to cause slowdowns in some other contracts, so that may well be the issue here.

**Comment by rfindler** [comment]
If you can make a program with just contracts, that would be helpful.

**Comment by rfindler** [comment]
Actually, probably better to just wait. This is may be the same bug that I'm looking into that makes timeouts in drdr currently.

**Comment by jbclements** [comment]
YES! I was hoping that this might be related to timeouts in DrDr.

Always happy to not have work to do,

John
