### ISSUE TITLE
infer: very slow constraint generation / solving

### ISSUE THREAD

**Issue by bennn** [racket/typed-racket#743]
### What version of Racket are you using?

6.90.0.30

### What program did you ~run~ try to compile?

```
#lang typed/racket/base

;; Adapted from the 'math' library.

(require racket/fixnum)

(define-predicate exact-zero? Zero)

(: vector-ref! (All (A B) ((Vectorof (U A B)) Integer (-> A) (Any -> Boolean : B) -> A)))
(define (vector-ref! vs i thnk nothing?)
  (define n (vector-length vs))
  (cond [(and (fixnum? i) (i . fx>= . 0) (i . fx< . n))
         (define v (vector-ref vs i))
         (if (nothing? v)
             (let ([v  (thnk)])
               (vector-set! vs i v)
               v)
             v)]
        [else
         (raise-range-error 'vector-ref! "Vector" "" i vs 0 n #f)]))

(define-type (Containerof T) (U (Listof T) (Vectorof T)))

(: container-ref!
   (All (A B) ((Containerof (U A B)) Integer (-> A) (Any -> Boolean : B) -> A)))
(define (container-ref! c i t p)
  (if (vector? c)
    (vector-ref! c i t p)
    (raise-user-error 'cref!)))

(define num-global-bs 2)
(define local-bs : (Containerof Exact-Rational)
  (make-vector num-global-bs 0))

(: bs-ref! (Integer (-> Exact-Rational) -> Exact-Rational))
(define (bs-ref! n thnk)
  (container-ref! local-bs (- n num-global-bs) thnk exact-zero?))
```

This takes at least 5 minutes to compile. (I'm waiting for it to finish. EDIT: killed it, too slow & too much memory to wait.)

### Test case

Here's a small test case for `typed-racket-test/unit-tests/infer-tests.rkt`:

```
 (infer-t (Un (-pair -Rat (-val null))
              (-vec -Rat))
          (Un (-pair (Un (-v a) (-v b)) (-val null))
              (-vec (Un (-v a) (-v b))))
          #:vars '(a b))
```

**Comment by pnwamk** [comment]
@bennn did you happen to do any poking to figure out whether it is indeed just slow or whether it is an infinite loop?

**Comment by bennn** [comment]
Not for the program above, but I think its just slow because:

- the test case finishes in ~15 seconds
- a similar program is slow with PR #575 (using `(U (Mutable-Vectorof ...) (Immutable-Vectorof ...))`) and that one finishes

**Comment by pnwamk** [comment]
@bennn "csets" I believe are constraint sets. From "I don't think it makes a difference" I don't think that comment is suggesting that it's bad (or it is perhaps ambivalent about the observation?). Anyway, it's a really old comment. I think it was added about 8 years ago (before my time ;-): https://github.com/racket/typed-racket/commit/c10334cfb0695a9891428463030cfaac67c33bc5

I _believe_ what it is saying is that it seems like it should be sound to just use the first constraint that is successfully generated (i.e. similar to how when checking if `t` is a subtype of `(U s ...)`, once you find _any_ `s_i` in `s` s.t. `t` is a subtype of `s_i` you can stop), but that they weren't sure so they span the whole union and join the results (which should also be sound).
