### ISSUE TITLE
Downcasting from Procedure produces an unhelpful error message

### ISSUE THREAD

**Issue by lexi-lambda** [racket/typed-racket#763]
I think this program should work, but it doesn’t:

```racket
#lang typed/racket
(define (g [x : Number]) (- x 100))
(define f : Procedure g)
((cast f (-> Number Number)) 50)
```

Instead, it fails with the following error:

```racket
g8: arity mismatch;
 the expected number of arguments does not match the given number
  given: 1
  arguments...:
   50
```

The error occurs both on HEAD and Racket v6.12. I have not tested other versions.

**Comment by samth** [comment]
That program is not intended to work. The `cast` form checks the source as well as the destination type, and the contract for `Procedure` is a function that can never be called. If you change `g` to be `(lambda ([x : String]) (string-length x))` then it's hopefully clearer why this is needed.

**Comment by lexi-lambda** [comment]
Okay, that makes sense, but if that’s the case, then the `cast` should fail with a more useful error message, then, no? An uninvokable procedure fails the first-order check for `(-> number? number?)` and signals a contract violation immediately when the contract is attached, before the function is ever invoked. For example:

```racket
#lang racket
(define/contract f
  (-> number? number?)
  (case-lambda))
```

**Comment by samth** [comment]
I think what's going on here is the same as in this program:

```
((contract (-> number? number?)
          (contract (case->) values 'a 'b) 'c 'd)
 1)
```

which has a very similar arity error message.

**Comment by rfindler** [comment]
Maybe the same as this program, too?

```
((contract (case->) void 'a 'b) 1)
```

**Comment by samth** [comment]
@rfindler yes, the second contract just demonstrates the lack of first-order contract error there (which is what I think @lexi-lambda wants).

**Comment by rfindler** [comment]
There are a lot of contracts where the arity isn't preseved (but it is shrunk, like this case). Eg:

```
(contract (-> integer? integer?)
          (lambda args (car args)) 'x 'y)
```

**Comment by lexi-lambda** [comment]
Right, *morally* the arity isn’t preserved, but it is according to `procedure-arity`:

```racket
> (procedure-arity
   (contract (-> integer? integer?)
             (lambda args (car args)) 'x 'y))
(arity-at-least 0)
```

This makes me wonder somewhat why `impersonate-procedure` demands that the arity according to `procedure-arity` remain unchanged, given that the arity checks can easily just be pushed into the function.

**Comment by rfindler** [comment]
oic. Dunno.

As for the error message, I think I'll punt this one down the line, as it seems to be coming from here:
```
> (define f (case-lambda))
> (f 1)
; f: arity mismatch;
;  the expected number of arguments does not match the given number
;   given: 1
; [,bt for context]
```

**Comment by rfindler** [comment]
I guess I do see why: it is important that chaperone contracts return values that are `equal?` (that's the main guarantee, after all) and it should probably also be the case that if `(and (procedure? x) (equal? x y))` is true, then `(equal? (procedure-arity x) (procedure-arity y))` ought to be true.

And this isn't really about contracts per se, because `x` and `y` could be bound to a function like this: `(lambda (x) (if (zero? (random 10)) (car) (car '(1))))`

**Comment by rfindler** [comment]
(I mean, both bound to that *one* function)

**Comment by lexi-lambda** [comment]
> it should probably also be the case that if `(and (procedure? x) (equal? x y))` is true, then `(equal? (procedure-arity x) (procedure-arity y))` ought to be true

Personally, I’m not totally convinced that checking `equal?`-ness on procedures ever makes any sense, anyway, but maybe it’s useful for things with `prop:procedure` on them or something. That’s a debate I don’t intend to step into, though. It just seems to me that if you can do this:

```racket
(impersonate-procedure f (lambda args (apply raise-arity-error 'f '() args)))
```

…there’s little reason you should be disallowed from doing this:

```racket
(impersonate-procedure f (case-lambda))
```

…but I think that’s a conversation that belongs on the racket/racket repo rather than here. Maybe I’ll open an issue there, instead.

**Comment by rfindler** [comment]
That's not a github discussion, I don't think. :)

**Comment by lexi-lambda** [comment]
Okay, then maybe I won’t do that. :) In any case, I think this issue can be closed.

**Comment by samth** [comment]
Note that there's no particular reason to restrict `impersonate-procedure` here, even though `chaperone-procedure` should be restricted.

**Comment by lexi-lambda** [comment]
Why? I understand the moral reason for restricting `chaperone-procedure` more than restricting `impersonate-procedure`, but it’s just as easy to do the same trick above using `raise-arity-error` using `chaperone-procedure`. If `chaperone-procedure` also banned exceptions from being raised inside the dynamic extent of the call to *`wrapper-proc`*, then preventing arity changes would, I think, clearly be the right thing to do. It is less clear to me that it’s meaningful for the version of `chaperone-procedure` we have.

**Comment by samth** [comment]
I think @rfindler's point about `equal?` and `procedure-arity` is right. I agree that this guarantee is fairly weak, but that seems inevitable for chaperones on higher-order values.

**Comment by lexi-lambda** [comment]
In that case, given that both `impersonate-procedure` and `chaperone-procedure` preserve `equal?`-ness, I think that would still imply that `impersonate-procedure` can’t be different here, so I’m not sure what exactly you’re arguing for.
