### ISSUE TITLE
typed/json doesn't account for json-null

### ISSUE THREAD

**Issue by LiberalArtist** [racket/typed-racket#768]
The `json` library is tricky to type (or protect by contract) because most functions take an optional `#:null` argument that defaults to the current value of `(json-null)`, which may be of any type and is recognized by `eq?`. The default value is `'null`, which of course works as a type for `JSExpr`.

The current `typed/json` interface partially addresses this by not permitting `#:null` arguments. However, it doesn't go far enough, and it is possible to provoke errors from untyped code that blame the interface:
```racket
#lang racket

(module flawed typed/racket
  (require typed/json)
  (provide parse)
  (: parse (-> String JSExpr))
  (define (parse str)
    (string->jsexpr str)))

(require json 'flawed)

(parameterize ([json-null '|something odd|])
  (parse "null"))
```

**Comment by samth** [comment]
Fortunately, this can't provoke unsoundness in Typed Racket, since the `typed/json` library is just another Typed Racket program. I don't see a way to do better here, unfortunately -- do you have a suggestion? If not, we should just document that this won't work.

**Comment by mfelleisen** [comment]
Why is _this_ not a general problem, where _this_ is 

 (1) require typed/foo a wrapper for foo 
 (2) require foo, too 

Use functions from the latter to circumvent the former’s invariants and cause havoc?

**Comment by mfelleisen** [comment]
@LiberalArtist wrote "it doesn't go far enough, and it is possible to provoke errors from untyped code that blame the interface:"

This is the beauty of "gradual typing" and is an incredibly beautiful example of how the Wadler slogan  "blame the untyped code" is complete nonsense. On occasion it's the type that we assign to untyped code that's to be blamed.

**Comment by samth** [comment]
@mfelleisen We shouldn't let ourselves off so easily: "the typed portion of the program can’t go wrong;
only the untyped portions may trigger run-time exceptions" is a quote from our paper.

**Comment by LiberalArtist** [comment]
One alternative I've thought of is that `typed/json` could implement wrapper functions that always supply `#:null 'null`. That would make the variants exported by `typed/json` actually have the types they currently claim to, and it would fit will the current decision to always use the type `'null` in `JSExpr`.

For example:
```racket
#lang racket

(module ignore-parameter typed/racket
  (provide JSExpr
           (rename-out
            [string->jsexpr* string->jsexpr]))
  (require (only-in typed/json JSExpr))
  (require/typed
   json
   [string->jsexpr (-> String #:null 'null JSExpr)])
  (: string->jsexpr* (-> String JSExpr))
  (define (string->jsexpr* str)
    (string->jsexpr str #:null 'null)))

(require (only-in json json-null)
         'ignore-parameter)

(parameterize ([json-null '|something odd|])
  (string->jsexpr "null"))
```

I think in any case it would need to be documented, but it seems easy to communicate the idea that the variants from `typed/json` are like the ones from `json` except that they always expect and produce `'null` for the null value.

**Comment by samth** [comment]
Ah, that's a nice idea.

**Comment by mfelleisen** [comment]
:-(
