### ISSUE TITLE
No type detected after (unless (list? x) (error))

### ISSUE THREAD

**Issue by gus-massa** [racket/typed-racket#782]
### What version of Racket are you using?
7.0

### What program did you run?
    #lang typed/racket

    (define  x (read))
    (unless (list? x)
      (error "not a list" x))
    (length x) ;<-- type error here

### What should have happened?
I think it should typecheck, because after the check it's sure that `x` is a list.  

This works if `x` is defined in a `let` or if `x` is the argument of a function, so probably the problem is that `x` is a module variable.

### If you got an error message, please include it here.

> Type Checker: Polymorphic function `length' could not be applied to arguments:
> Argument 1:
>   Expected: (Listof a)
>   Given:    Any
> 
> Result type:     Index
> Expected result: AnyValues
>  in: (length x)

**Comment by pnwamk** [comment]
Just a quick note: this idiom works when it is not at the module-level, i.e. this works:

```racket
#lang typed/racket 

(let ()
  (define  x (read))
  (unless (list? x)
    (error "not a list" x))
  (length x))
```

So my suspicion is that all of the `(call-with-values blah print-values)` that get wrapped around expressions at the module-level during expansion is mucking up the type checker's reasoning.

**Comment by samth** [comment]
My suspicion is that it's because we treat top-level variables differently than lexical variables.
