### ISSUE TITLE
indecipherable error message for match on struct outside union 

### ISSUE THREAD

**Issue by jbclements** [racket/typed-racket#789]
### What version of Racket are you using?

git HEAD: Welcome to DrRacket, version 7.1.0.8--2018-12-03(-/f) [3m].

### What program did you run?

```
#lang typed/racket

;; NB: I left StrC out of ExprC! Oops!
(define-type ExprC (U NumC Primop ))
(struct NumC ([n : Real]) #:transparent)
(struct StrC ([s : String]) #:transparent)

(define-type Primop (Real Real -> Real))

(define (type-check [e : ExprC]) : Real
  (match e
    [(NumC n) 12]
    [(StrC s) 13]   
    [_ 14]))
```

### What should have happened?

In a perfect world, TR tells me that the StrC clause is not reachable. More plausibly, TR regards the StrC clause as dead code. Or, really, any error message that makes sense in non-expanded-user-world.

### If you got an error message, please include it here.

Type Checker: cannot apply a function with unknown arity;
 function `unsafe-struct-ref' has type Procedure which cannot be applied in: (match e ((NumC n) 12) ((StrC s) 13) (_ 14))
> 

### Discussion

I did a little digging, and I see that unsafe-struct-ref crops up all over the place, but presumably in other places, TR understands what's going on because the use is guarded by a predicate that is known to TR. There's also something funny going on with the 'Primop' in the type union; taking it out results in the code compiling fine. I don't quite see the connection.

**Comment by samth** [comment]
The problem is that (a) TR doesn't realize that `Primop` and `StrC` can't overlap, so the type of `e` after the predicate test was `(Intersect Primop StrC)` and then (b) the code for handling `unsafe-struct-ref` (which has to be special) didn't know anything about intersections. The PR I just opened fixes (b) which makes the program type check.

**Comment by jbclements** [comment]
So fast! Many thanks!

**Comment by jbclements** [comment]
Should have mentioned: thanks to @eskirk for discovering this bug.
