### ISSUE TITLE
`is-a?` doesn't support occurrence typing

### ISSUE THREAD

**Issue by lwhjp** [racket/typed-racket#792]
For example:
```
#lang typed/racket
(define with-field%
  (class object%
    (init-field that)
    (super-new)))

(define (maybe-that o)
  (if (is-a? o with-field%)
      (get-field that o)
      #f))

(maybe-that (make-object with-field% 'bingo))
```

This fails typecheck with:
```
Type Checker: type mismatch;
 expected an object value for get-field
  given: Any in: (get-field that o)
```
Whereas I'd expect the last line to return `bingo`.

Presumably `is-a?` should have a type something like `(All (A) (-> Any A Boolean : (Instance A)))`, if that expression makes sense in TR.

**Comment by samth** [comment]
Unfortunately, this doesn't work. You can see a discussion of why not [here](http://drops.dagstuhl.de/opus/volltexte/2015/5215/pdf/5.pdf) on p12-13.

**Comment by lwhjp** [comment]
Ah, I see! Thank you.

I don't know if that counts as "resolved", but I'm happy to close this issue.

**Comment by bennn** [comment]
It would be good to have an explanation in the Typed Racket guide (under "Caveats and Limitations") too.

Lets leave this open as a documentation request?
