### ISSUE TITLE
internal TC error "Tried to move vars to dbound that already exists"

### ISSUE THREAD

**Issue by pnwamk** [racket/typed-racket#82]
``` racket
#lang typed/racket

(: f (-> One (List One String Char) : #:object (0 0)))
(define (f [x : One])
  (let ([f (plambda: (a ...) [w : a ... a] w)])
    (f x "hello" #\c)))
```

throws an internal error:

Welcome to DrRacket, version 6.2.0.2--2015-04-02(9481e39/a) [3m].
Language: typed/racket; memory limit: 128 MB.

../../Applications/Racket v6.2.0.2/share/pkgs/typed-racket-lib/typed-racket/utils/tc-utils.rkt:263:0: Internal Typechecker Error: Tried to move vars to dbound that already exists
while typechecking:
(#%app f x (quote hello) (quote c))
originally:
(f x hello c)

**Comment by takikawa** [comment]
I've seen this error before with a different example: http://bugs.racket-lang.org/query/?cmd=view audit-trail&database=default&pr=14616

In the audit trail there, I identified a commit that originated the error from a git bisect.

**Comment by samth** [comment]
The relevant commit is now 0a46a278934caaa85a62f30a82f1d460fb96685b.

**Comment by capfredf** [comment]
The bug has been fixed. I can't reproduce it in Racket 8.0 or later
