### ISSUE TITLE
TR type of math function floor should have Integer output?

### ISSUE THREAD

**Issue by maueroats** [racket/typed-racket#822]
### What version of Racket are you using?
7.3

### What program did you run?
```racket
#lang typed/racket
(define (example [x : Real] [y : Real]) : Integer
  (remainder (floor (+ x y))
             10))
```
### What should have happened?
Program accepted by type-checker because mathematically, `floor` outputs an integer.

### If you got an error message, please include it here.
```
Type Checker: type mismatch
  expected: Integer
  given: Real in: (floor (+ x y))
```

### Other notes
Also affects other functions like `ceiling`, `round`, `truncate`.

Note for me: In `typed-racket-lib/typed-racket/base-env/base-env-numeric.rkt` there are a lot of similar types relating to rounding and flooring functions, change one they all should change?

In the [Racket Reference](https://docs.racket-lang.org/reference/generic-numbers.html), we find

```
(floor x) → (or/c integer? +inf.0 -inf.0 +nan.0)
--
x : real?
```

The signature of this function is kind of gross from a usability point of view. Is there a way to clean it up? It seems like in practice you're going to need to cast the result? 

Is there any different type signature that makes sense to use for `floor`?

**Comment by samth** [comment]
The `Integer` type includes only exact integers, whereas `integer?` includes numbers such as `3.0`.  The `integer?` predicate doesn't correspond to a type with an useful properties that I know of, unfortunately.

**Comment by maueroats** [comment]
Other people who have this problem: use `exact-floor` and friends, not plain `floor`.
