### ISSUE TITLE
value serialization loops forever in TR

### ISSUE THREAD

**Issue by jbclements** [racket/typed-racket#823]
## Summary

It appears to me that certain cyclic Typed Racket values cause check-equal?'s error message to loop infinitely. I think that this is probably actually a racket bug, so I haven't tried to minimize the bug at all. If one of y'all can confirm that a) there aren't any known isssues around infinite-time printing of cyclic values, and b) this is probably a Racket problem rather than a TR problem, I'll submit this as a Racket bug instead.

### What version of Racket are you using?

7.3

### What program did you run?

[lab7.txt](https://github.com/racket/typed-racket/files/3218207/lab7.txt)

### What should have happened?

The test case failure should have been displayed in finite time and memory.

**Comment by samth** [comment]
Do you know that this loops in the error printing from `check-equal?`? Could it be a contract error/a type error/a compilation time issue/something else?

**Comment by bennn** [comment]
Here's a smaller program --- without rackunit --- that also seems to loop.  It does a `(require/typed racket/base (displayln (-> Any Void)))` and tries to display a value

[smaller-typed.txt](https://github.com/racket/typed-racket/files/3219560/smaller-typed.txt)

When I hit Ctrl-C, the "user break" context points to:
```
typed-racket-lib/typed-racket/utils/any-wrap.rkt:118:2: any-wrap/traverse
```

so I think this is a TR contract generation problem.


I also made an untyped version. It works.
[smaller-untyped.txt](https://github.com/racket/typed-racket/files/3219563/smaller-untyped.txt)

**Comment by samth** [comment]
That probably means an infinite loop in the any-wrap/c contract on circular
data.
