### ISSUE TITLE
Untyped code requiring struct from `require/typed`

### ISSUE THREAD

**Issue by camoy** [racket/typed-racket#837]
### What version of Racket are you using?

`7.3--2019-06-14`

### What program did you run?

```rkt
(module a racket/base
  (struct foo ())
  (provide (struct-out foo)))

(module b typed/racket/base
  (require/typed (submod ".." a) [#:struct foo ()])
  (provide (struct-out foo)))

(module c racket/base
  (require (submod ".." b))
  (provide (struct-out foo)))
```

### What should have happened?

No error.

### If you got an error message, please include it here.

```
struct-out: identifier is not bound to struct type information in: foo
```

**Comment by camoy** [comment]
The problem seems to be the use of `#:type-only` in `dtsi*` on [L554 here](https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/base-env/prims-contract.rkt#L554), but I doubt simply omitting this keyword argument is a general purpose fix.

**Comment by samth** [comment]
The struct type information should be defined here: https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/base-env/prims-contract.rkt#L549 so that's surprising.

**Comment by camoy** [comment]
Since `#:type-only` is set, the [`parsed-struct` field](https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/typecheck/tc-structs.rkt#L35) has `type-only` set to `#t` for the required struct. So when [`register-parsed-struct-bindings!`](https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/typecheck/tc-structs.rkt#L395) is called the bindings are not registered.

When the provide form [checks the binding](https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/typecheck/provide-handling.rkt#L85), it treats the struct type transformer as regular syntax and not as a struct info. It then gets erroneously bound to the transformer that raises the "macro from typed module used in untyped code."

**Comment by bennn** [comment]
probably related: #926
