### ISSUE TITLE
please add label "good first issue"

### ISSUE THREAD

**Issue by spdegabrielle** [racket/typed-racket#856]
Only four issues in /typed-racket are currently using the "good-first-bug" label. 

Switching to "good first issue" would make is easier for volunteers to find these tasks.

Search: type:issue org:racket state:open label:"good first issue"
e.g. 
https://github.com/search?q=type:issue+org:racket+state:open+label:%22good+first+issue%22

**Comment by bennn** [comment]
I renamed the label, looked over the open issues, and added it to a few.
