### ISSUE TITLE
Add Unquoted-Printing-String to base environment

### ISSUE THREAD

**Issue by LiberalArtist** [racket/typed-racket#859]
### What version of Racket are you using?
7.4 CS & 7.4.0.5 traditional
### What program did you run?
```racket
#lang typed/racket/base

(require/typed
 racket/base
 [#:opaque Unquoted-Printing-String unquoted-printing-string?]
 [unquoted-printing-string-value (-> Unquoted-Printing-String String)]
 [unquoted-printing-string (-> String Unquoted-Printing-String)])

(unquoted-printing-string-value
 (unquoted-printing-string "a"))
```
### What should have happened?
These types should be provided by the base environment. Attempting to define them as above produces a warning (to become an error) because `unquoted-printing-string?` does not satisfy `struct-predicate-procedure?/c`. I can try to make a PR if no one gets to it first.

I'm not sure if it's intentional that `unquoted-printing-string?` answers false to `struct-predicate-procedure?`, but the message for https://github.com/racket/racket/commit/cbfcc90 suggests it may be necessary for cooperation with `raise-arguments-error`. The relevant definitions seem to be [here for CS](https://github.com/racket/racket/blob/8284dfa1b18e2583f32d0333d69b0120a9b5b05b/racket/src/cs/rumble/error.ss#L441-L442), [here for the C-implemented type](https://github.com/racket/racket/blob/a80952e05f7e992782e3a30d04fed6b9d815283a/racket/src/racket/src/type.c#L271), and [here for the C-implemented predicate](https://github.com/racket/racket/blob/8f85df64d930b3b9997275db0578819a6b583ca9/racket/src/racket/src/error.c#L2227-L2232).

### If you got an error message, please include it here.
```
unquoted-printing-string?: contract violation
  any-wrap/c: Unable to protect opaque value passed as `Any`
  value: a
  This warning will become an error in a future release.
  in: the 1st argument of
      a part of the or/c of
      (or/c
       struct-predicate-procedure?/c
       (-> Any boolean?))
  contract from: 
      (interface for unquoted-printing-string?)
  blaming: anonymous-module
   (assuming the contract is correct)
  at: unsaved-editor:5.36
```

**Comment by LiberalArtist** [comment]
As a workaround, you can write:
```racket
(require/typed
 typed/racket/base
 [unquoted-printing-string (-> String Any)])
```

**Comment by samth** [comment]
It's not a `struct-predicate-procedure?` because unquoted-printing strings aren't structs, the same way vectors aren't structs. On Racket CS the implementation could change pretty easily so that it answered `#t` anyway (and similarly for many other simple predicates). I'm unsure if that's a good change to make. Alternatively the contract check there could just have a list of functions to check as well.

**Comment by LiberalArtist** [comment]
> Alternatively the contract check there could just have a list of functions to check as well.

Are there functions that would make sense to include in such a list other than predicates for primitive types? (In the sense that "unquoted-printing string" is a disjoint type in the runtime system, despite not having a corresponding Typed Racket type.)
