### ISSUE TITLE
Unsound function types with rest and opt arguments

### ISSUE THREAD

**Issue by yjqww6** [racket/typed-racket#862]
### What version of Racket are you using?
7.4
### What program did you run?
```racket
#lang typed/racket

(define (f [a : Integer 1] b : Integer *)
  (cons a b))

(add1 (cdr (f 1 2)))
```
### What should have happened?
a type error
### If you got an error message, please include it here.
```
  add1: contract violation
  expected: number?
  given: '(2)
```

**Comment by capfredf** [comment]
Interesting. I have never used variable arguments when defining functions in Typed Racket.
I think the bug has something to do with type annotation for b in this case.
```
#lang typed/racket

(define (f [a : Integer 1] b : Integer *)
  b)

(f 1 2)
```
produces:
```
- : Integer
'(2 3)
```
@samth can we say `b : Integer *` is equivalent to `b : (Listof Integer)`?
