### ISSUE TITLE
require/typed of hash-union contract failure

### ISSUE THREAD

**Issue by pinicarus** [racket/typed-racket#865]
### What version of Racket are you using?
7.3

### What program did you run?
```racket
#lang typed/racket/base

(require/typed racket/hash
  [hash-union (All (K V) (->* ((HashTable K V))
                              #:rest (HashTable K V)
                              (HashTable K V)))])

(define h1 : (HashTable Integer Integer) (hash 1 2))
(define h2 : (HashTable Integer Integer) (hash 3 4))

(hash-union h1 h2)
```

### What should have happened?
Program should display `'#hash((1 . 2) (3 . 4))`

### If you got an error message, please include it here.
```
hash/c: contract violation
  expected: chaperone-contract?
  given: K4
  context...:
   /usr/share/racket/collects/racket/contract/private/guts.rkt:284:0: coerce-chaperone-contract
   /usr/share/racket/collects/racket/contract/private/hash.rkt:61:0: hash/c7
   /usr/share/racket/pkgs/typed-racket-lib/typed-racket/utils/hash-contract.rkt:28:0: hash/c/check-key5
   /usr/share/racket/pkgs/typed-racket-lib/typed-racket/utils/hash-contract.rkt:13:0: typed-racket-hash/c
   /usr/share/racket/collects/racket/contract/private/parametric.rkt:26:36
   /usr/share/racket/collects/racket/contract/private/parametric.rkt:82:7: wrap
   "weird.rkt": [running body]
   temp37_0
   for-loop
   run-module-instance!125
   perform-require!78
```

**Comment by bennn** [comment]
`hash/c` won't accept an impersonator contract for a hash key, but `(All (K V) ....)` generates an impersonator contract. I'm not sure what to do about that in general.

If you only care about `hash-union` (and not the mutable version), then you can use immutable hash tables & the `Any` type:
```
#lang typed/racket/base

(define-type (IHash K V) (Immutable-HashTable K V))

(require/typed racket/hash
  [hash-union (All (V) (->* ((IHash Any V))
                              #:rest (IHash Any V)
                              (IHash Any V)))])

(define h1 : (IHash Integer Integer) (hash 1 2))
(define h2 : (IHash Integer Integer) (hash 3 4))

(hash-union h1 h2)
```

**Comment by pinicarus** [comment]
Removing the type constraint on keys makes it harder to use the function in more complex situations because it introduces a need to cast parameters and return values.

How unsafe would it be to use `unsafe-require/typed` to type check hash-union as a parametric type on both the keys and values but not generating a contract?

**Comment by samth** [comment]
That would only be unsafe if hash-union does not meet that specification. Note that this can be tricky to predict sometimes, especially with polymorphism.

**Comment by pinicarus** [comment]
I'm confident in the implementation of `hash-union` so I'll go with `unsafe-require/typed` (though it'd be cool to be able to type such function properly in the future).
