### ISSUE TITLE
is it possible (or even sensible) to make unit tests for typechecking?

### ISSUE THREAD

**Issue by mbutterick** [racket/typed-racket#87]
What’s the best practice for writing unit tests for typing? For instance when I’m using `typed/rackunit`, I’ve wondered if I can make checks for types that are analogous to `check-not-exn` and `check-exn` for contracts — e.g., something like `typecheck-passes` and `typecheck-fails`:

```racket
#lang typed/racket
(require typed/rackunit)

(: proc (CustomFooType . -> . CustomFooType))
(define (proc a) a)

(typecheck-passes (proc custom-foo-value)) ;; returns silence
(typecheck-fails (proc not-a-foo-value)) ;; also returns silence
```  

I appreciate that `typed/rackunit` operates at runtime and typechecking happens at compile-time. OTOH I don’t see why in principle the check itself couldn't happen at compile-time, so long as it has the ability to a) detect success or failure and b) suppress failure (i.e., stop an error from bubbling up the chain of handlers).

**Comment by rmculpepper** [comment]
You may be interested in `convert-compile-time-error` from `unstable/macro-testing`, although I'm not sure how easy it will be to use with TR.

**Comment by samth** [comment]
I guess I'm not sure why you want to test that something fails to type check. For things that should successfully type check, just writing a regular test will also fail if they don't type check.

**Comment by mbutterick** [comment]
> I'm not sure why you want to test that something fails to type check

To insure that a custom-defined type is including the values it ought to, and excluding the rest. Recursive types especially — it’s easier to validate the logic using test cases.

> just writing a regular test will also fail if they don't type check

Yes, but one benefit of `rackunit` is its ability to treat failure as success. For instance, if I change the example above to this:

```racket
#lang typed/racket
(require typed/rackunit)

(: proc (Integer . -> . Integer))
(define (proc a) a)

(check-exn exn:fail? (λ _ (/ 1 0)))
(check-exn exn:fail? (λ _ (proc 'sym)))
```

The division error in `(/ 1 0)` is intentional, but `check-exn` a) verifies the failure and then b) suppresses it. Whereas the intentional type error in `(proc 'sym)` is detected but not suppressed.

**Comment by rfindler** [comment]
Wow. Get thee behind me Satan!

:)

**Comment by samth** [comment]
Unfortunately, it would be hard to make `convert-compile-time-error` work in Typed Racket, because of how it raises type errors. Here's a brief snippet of code that should show how to use `eval` explicitly to do what you want, though:

```racket
#lang typed/racket

(require typed/rackunit typed/racket)

(define-namespace-anchor ns)

(define (E v) (eval (cons '#%top-interaction v) (namespace-anchor->namespace ns)))

(check-exn exn:fail:syntax?
           (λ () (call-with-values (λ () (E '(+ 'foo))) (λ vals (car vals)))))
```

**Comment by mbutterick** [comment]
Thanks for the tip. Works very nicely.

```racket
#lang typed/racket
(require typed/rackunit)

(define-syntax (check-typing-base stx)
  (syntax-case stx ()
    [(_ wants-to-fail? expr)
     (let* ([wants-to-fail? (syntax->datum #'wants-to-fail?)]
            [λ-arg 'v]
            [eval-string (if wants-to-fail? `(cons '#%top-interaction ,λ-arg) λ-arg)]
            [check-string (if wants-to-fail? '(curry check-exn exn:fail:syntax?) 'check-not-exn)])
       #`(begin
           (define-namespace-anchor ns)
           (let ([E (λ(#,λ-arg) (eval #,eval-string (namespace-anchor->namespace ns)))])
             (apply #,check-string (list (λ _ (call-with-values (λ _ (E 'expr)) (λ vals (car vals)))))))))]))

(define-syntax-rule (check-typing-fails expr)
  (check-typing-base #t expr))

(define-syntax-rule (check-typing expr)
  (check-typing-base #f expr))

(check-typing-fails (+ 'foo))
(check-typing-fails (+ "bar"))

(check-typing (+ 1))
(check-typing (+ 2.0))
```

**Comment by jsmaniac** [comment]
For future reference, what @mbutterick used does not work for the `check-typing` case, it does not perform the type checking. I'm using this instead (just always wrap with `#%top-interaction`, including for check-typing):

```
#lang typed/racket
(require typed/rackunit)

(define-syntax (check-typing-base stx)
  (syntax-case stx ()
    [(_ wants-to-fail? expr)
     (let* ([wants-to-fail? (syntax->datum #'wants-to-fail?)]
            [check-string (if wants-to-fail?
                              '(curry check-exn exn:fail:syntax?)
                              'check-not-exn)])
       #`(begin
           (define-namespace-anchor ns)
           (let ([E (λ (e)
                      ;; Discard the type printed by the REPL
                      (parameterize ([current-output-port (open-output-nowhere)])
                        (eval (cons '#%top-interaction e)
                              (namespace-anchor->namespace ns))))])
             (#,check-string
              (λ _ (call-with-values (λ _ (E 'expr))
                                     (λ vals (car vals))))))))]))

(define-syntax-rule (check-typing-fails expr)
  (check-typing-base #t expr))

(define-syntax-rule (check-typing expr)
  (check-typing-base #f expr))

(check-typing-fails (+ 'foo))
(check-typing-fails (+ "bar"))

(check-typing (+ 1))
(check-typing (+ 2.0))
(check-typing (ann 'foo 1)) ;; rightfully throws an error
```

I also added `(parameterize ([current-output-port (open-output-nowhere)]) eval…)` around the eval, so that the type printed by the REPL is discarded. This has the undesirable side-effect of also discarding the output of the test, if any.
