### ISSUE TITLE
#:forall and optional keyword arguments

### ISSUE THREAD

**Issue by bdeket** [racket/typed-racket#940]
### What version of Racket are you using?
Welcome to DrRacket, version 7.7.0.7 [3m].

### What program did you run?
```
#lang typed/racket/base

(struct (A) foo ([a : (Listof A)]))


(define #:forall (A) (bar [a : (Listof A)]
                          #:test1 [b : (foo A)(foo '())]
                          #:test2 [c : String]) : (foo A)
  (foo a))
```

### What should have happened?
type-check
### If you got an error message, please include it here.
```
. Type Checker: parse error in type;
 type name `A' is unbound in: A
. Type Checker: type mismatch
  expected: (Listof (Pairof Struct-Type-Property Any))
  given: (List (List* Struct-Type-Property 'bar (-> Any (Listof Error) Any))) in: (#%module-begin (define-values (bar) (-lambda #:forall (A) (a #:test1 (b (foo (quote ()))) #:test2 c) (ann (foo a) (foo A)))))
. Type Checker: Summary: 2 errors encountered in:
  A
  (#%module-begin (define-values (bar) (-lambda #:forall (A) (a #:test1 (b (foo (quote ()))) #:test2 c) (ann (foo a) (foo A)))))
```
------------------
using (: bar (All (A) (->* ... etc works

**Comment by samth** [comment]
This is a _very_ bad error report (cc @capfredf for the `Struct-Type-Property`) but the actual problem is that you don't have a default value for `test2`. If I add that, it works.

**Comment by bdeket** [comment]
Sorry.
How should I have reported it better?

If I look at [define](https://docs.racket-lang.org/ts-reference/special-forms.html?q=define#%28form._%28%28lib._typed-racket%2Fbase-env%2Fprims..rkt%29._define%29%29) I don't see why I can't mix kw-arguments with and without default values.

since annotating with (: bar ...) works I was expecting that it is also the intention that this would work with forall

**Comment by samth** [comment]
Ah, you were intending to have that be required. It certainly ought to work to do that.

**Comment by AlexKnauth** [comment]
This same error message can be triggered without `struct foo` needed, and without optional keyword arguments at all, only a mandatory keyword argument.
```racket
#lang typed/racket
(define #:forall (A) (bar [a : (Listof A)] #:mand [mand : Integer]) : Integer
  0)
```
Triggers the error message
```
Type Checker: parse error in type;
 type name `A' is unbound in: A
Type Checker: type mismatch
  expected: (Listof (Pairof Struct-Type-Property Any))
  given: (List (List* Struct-Type-Property 'bar (-> Any (Listof Error) Any))) in: #%module-begin
Type Checker: Summary: 2 errors encountered in:
  A
  #%module-begin
```
