### ISSUE TITLE
Performance issue with generic (List?) data types

### ISSUE THREAD

**Issue by juszczakn** [racket/typed-racket#958]
### What version of Racket are you using?

7.6 through 7.8, CS and Reg.

### What program did you run?

```
#lang typed/racket

(: xs (Listof Integer))
(define xs
  (list
   1 2 3 4 5 6 7 8 9 0
    ;; repeat n times
    ))
```

I used the above snippet and just created lists of size 100, 300, and 600.
Timed how long each ran using 7.6 cs, 7.7 cs, and 7.8 [cs/reg] multiple times.

Below are my fastest timings with 7.8 CS over multiple runs. All other versions tested had comparable timings. 

```
time ~/opt/racket-7-8/bin/racket 100.rkt 

real	0m1.832s
user	0m1.696s
sys	0m0.137s
```
```
time ~/opt/racket-7-8/bin/racket 300.rkt 

real	0m4.831s
user	0m4.671s
sys	0m0.160s
```

```
time ~/opt/racket-7-8/bin/racket 600.rkt 

real	0m26.152s
user	0m26.001s
sys	0m0.184s
```

### What should have happened?

This increase in runtime seems like it should be at worst linear, not exponential like it appears to be currently.

This appears like it might be similar/related to issue #722, perhaps? Like that issue, this is maybe not a problem in Typed/Racket itself, so maybe this issue should be in racket/racket instead?

This also appears to be specific to `Listof`. I simplified my test to `Listof Zero` and saw no changes in perf. I then Changed it from a `List` to a `Vector`, and the performance problem seemingly went away.

### If you got an error message, please include it here.

N/A

**Comment by capfredf** [comment]
Thank you for reporting this issue. This is a performance issue of the type checker, but doesn't actually cause any runtime penalty. I guess this has something to do with how a recursive type is checked.

To get around this issue, you can use `raco make <your program>` before actually run your program.
The following is a side-by-side comparison between running a similar program with and without `raco make`:
```
➜   time racket hello3.rkt
racket hello3.rkt  9.52s user 0.36s system 98% cpu 10.055 total
➜  raco make hello3.rkt
➜  time racket hello3.rkt
racket hello3.rkt  0.44s user 0.11s system 97% cpu 0.563 total
```
The `hello3.rkt`, similar to your code snippet, has a list of 460 zeroes.

**Comment by juszczakn** [comment]
Yea, that's kinda what I figured. I found the same thing with building with raco make, forgot to update the issue, oops. 

Unfortunately, this really affects REPL based workflows (eg. emacs racket-mode), which was how I was noticing. I suppose the easiest way to get around that for now might be to move any large lists to their own files and compile and require them, instead of having them in the same file under dev.

I'd be really interested to know where the bottleneck is coming from. I took a little bit of time to try to track it down, but quickly got lost lol.

**Comment by capfredf** [comment]
Another workaround I forgot to mention is try
`((inst list Integer) 1 2 3 4 5 6 7 8 9 0 ................................)`

w/o `inst`
```
➜  typed-racket git:(fix-987) ✗ time racket hello3.rkt
racket hello3.rkt  9.81s user 0.44s system 98% cpu 10.444 total
```

w/ `inst`
```
➜  typed-racket git:(fix-987) ✗ time racket hello3.rkt
racket hello3.rkt  1.62s user 0.32s system 98% cpu 1.970 total
```
Hope this help in your workflows

**Comment by capfredf** [comment]
With the new fix, it takes less than 2 seconds to check a list of 670 numbers on my machine:
```
➤ time racket hello3.rkt

________________________________________________________
Executed in    1.47 secs   fish           external
   usr time  1239.57 millis  110.00 micros  1239.46 millis
   sys time  209.88 millis  501.00 micros  209.38 millis
````
