### ISSUE TITLE
Internal error when using sequence

### ISSUE THREAD

**Issue by bdeket** [racket/typed-racket#965]
### What version of Racket are you using?
version 7.8.0.9--2020-08-25(80ad628/a) [3m].

### What program did you run?
```
#lang typed/racket/base

(require racket/sequence)

(define (fun [vs : (U (Listof Real)
                      (Listof (Listof Real)))])

  (for/fold ([a : (Option (Listof (Listof Real))) '()])
            ([s vs])
    (define l (sequence->list s))
    (cond
      [(and (list? l) (= (length l) 2) (sequence? (car l)))
       (cons (cons (sequence->list (car l))
                   (sequence->list (cadr l)))
             a)]
      [else #f])))

```

### What should have happened?
typecheck (or understandable error message)

### If you got an error message, please include it here.
racket-7.8.0.9/share/pkgs/typed-racket-lib/typed-racket/infer/promote-demote.rkt:32:0: Rep-variances: contract violation:
expected: Rep?
given: #f
argument position: 1st

### extra
In this example, changing `(define l (sequence->list s))` to `(define l s)` makes the error go away, and typechecks

**Comment by yjqww6** [comment]
I have just made a pull request for the right error message, which would be
```
Type Checker: Polymorphic function `sequence->list' could not be applied to arguments:
Argument 1:
  Expected: (Sequenceof a)
  Given:    (U (Listof Real) Real)
 in: (sequence->list s)
``` 
It fails because numbers other than Exact-Nonnegative-Integer could not be used as sequences.

**Comment by bdeket** [comment]
Thanks,
I found that that was indeed a problem, but didn't realize it was the reason for this error.
