### ISSUE TITLE
typed/pict has out-of-date signatures.

### ISSUE THREAD

**Issue by Lazerbeak12345** [racket/typed-racket#971]
### What version of Racket are you using?
7.5

### What program did you run?

```racket
#lang typed/racket
(require typed/pict)
(disk 16
      #:color "white"
      #:border-color "lightgrey"
      #:border-width 5)
```

### What should have happened?

While the program doesn't (technically) do anything, it should run, after generating a disc pict.

### If you got an error message, please include it here.

```txt
test.rkt:3:0: Type Checker: Unexpected keyword argument #:border-color
  in: (disk 16 #:color "white" #:border-color "lightgrey" #:border-width 5)
  location...:
   test.rkt:3:0
  context...:
   do-raise-syntax-error
   /usr/racket/share/pkgs/typed-racket-lib/typed-racket/typecheck/tc-toplevel.rkt:359:0: type-check
   /usr/racket/share/pkgs/typed-racket-lib/typed-racket/typecheck/tc-toplevel.rkt:602:0: tc-module
   /usr/racket/share/pkgs/typed-racket-lib/typed-racket/tc-setup.rkt:94:0: tc-module/full
   /usr/racket/share/pkgs/typed-racket-lib/typed-racket/typed-racket.rkt:23:4: module-begin
  apply-transformer-in-context
  apply-transformer52
  dispatch-transformer41
  ensure-module-begin34
  expand-module16
  expand-capturing-lifts
  temp118_0
  temp91_0
  compile15
  temp85_0
  standard-module-name-resolver
  ...
```

### Here's what the problem likely is

Version 1.4 of pict-lib added a bunch of new optional keyword arguments (and I am trying to use some of them above).
There's actually a _ton_ of functions that got new arguments in that version, and I would have just done a pull request, but I'm not familiar enough with `#lang s-exp typed-racket/base-env/extra-env-lang` to feel comfortable supplying a test without a good way to test it (as I also don't have a development environment for this repo set up on my computer yet either).

**Comment by yjqww6** [comment]
update to a recent version should solve this problem

**Comment by Lazerbeak12345** [comment]
I took a look at the new signatures, and that looks like it'd work. Thanks!
