### ISSUE TITLE
A problem caused by Recursive Parameter Type

### ISSUE THREAD

**Issue by NoahStoryM** [racket/typed-racket#973]
### What version of Racket are you using?
v7.8

### What program did you run?
```
#lang typed/racket/base
(define-type Type1 (U Number (Parameter Type1)))
(define-type Type2 (U Type1 Symbol))
(ann (ann 123 Type1) Type2)
```

```
#lang typed/racket/base
(define-type Type1 (U Number (Parameter Type2)))
(define-type Type2 (U Type1 Symbol))
(ann (ann 123 Type1) Type2)
```

### What should have happened?
```123```

### If you got an error message, please include it here.
The code all failed with the following message:
```
Type Checker: type mismatch
  expected: Type2
  given: Type1
  in: 123
```

**Comment by capfredf** [comment]
This issue has nothing to do with recursive types. It is due how TR treats a parameter type internally. but I have a [quick fix](https://github.com/capfredf/typed-racket/commit/ef5ba83c03793d2a83358ae5a8a82f1e1217e8da), but I still need to sleep on it
